// The phone's cell placement over Steam's sheets.
//
// The Steam build rebuilt its UI for a widescreen desktop: its cell banks place and
// size things for screens this port does not draw, and its sheets are larger than the
// phone's by different factors per asset. Both builds keep the same cells in the same
// order, though, and each Steam OAM's sheet rectangle covers the same picture as the
// phone's at Steam's pixel size. So when a cell bank comes from a Steam install, the
// placement in Data/ff3-steam-cells.json - the phone's x, y, w, h and flags - replaces
// what the file said, and the sheet rectangle the file gave stays as the source, drawn
// at the phone's size. Nothing of Square's ships with the client for this: the table is
// a few hundred positions, generated by Tools/gen_steam_cells.py.
//
// Only cell banks that differ between the builds are in the table; identical ones and
// Steam-only ones are drawn as they are.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json.Nodes;
using FF3.Content;

namespace FF3
{
	internal static class SteamCells
	{
		private static Dictionary<string, List<List<short[]>>> _banks;
		private static bool _loaded;
		private static readonly HashSet<string> _reported = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

		/// <summary>Whether the content in front is a Steam FF3 install, which is when the table applies.</summary>
		private static bool Applies => GameArchive.Chain != null && GameArchive.Chain.Shipped is LooseContentSource
			&& GameArchive.Game == "ff3" && string.IsNullOrEmpty(Options.Get("steam-cells-off"));

		private static void Load()
		{
			if (_loaded)
			{
				return;
			}
			_loaded = true;
			_banks = new Dictionary<string, List<List<short[]>>>(StringComparer.OrdinalIgnoreCase);
			string path = Path.Combine(AppContext.BaseDirectory, "Data", "ff3-steam-cells.json");
			if (!File.Exists(path))
			{
				Log.Write(LogChannel.File, "steam cells: no table at " + path);
				return;
			}
			try
			{
				JsonNode root = JsonNode.Parse(File.ReadAllText(path));
				foreach (KeyValuePair<string, JsonNode> bank in root["banks"].AsObject())
				{
					List<List<short[]>> cells = new List<List<short[]>>();
					foreach (JsonNode cell in bank.Value["cells"].AsArray())
					{
						List<short[]> oams = new List<short[]>();
						foreach (JsonNode oam in cell.AsArray())
						{
							JsonArray a = oam.AsArray();
							// x, y, w, h, flags.
							oams.Add(new[] { (short)(int)a[0], (short)(int)a[1], (short)(int)a[2], (short)(int)a[3], (short)(int)a[4] });
						}
						cells.Add(oams);
					}
					_banks[bank.Key] = cells;
				}
				Log.Write(LogChannel.File, "steam cells: " + _banks.Count + " cell banks in the table");
			}
			catch (Exception ex)
			{
				Log.Write(LogChannel.File, "steam cells: table unreadable: " + ex.Message);
			}
		}

		/// <summary>
		/// Rewrites a loaded cell bank's OAM placement to the phone's, keeping each OAM's
		/// sheet rectangle from the Steam file as its source. No-op for banks not in the
		/// table, or when the content is not a Steam install.
		/// </summary>
		public static void Apply(string ncerName, GlobalScope.NNSG2dCellDataBank bank)
		{
			if (bank == null || string.IsNullOrEmpty(ncerName) || bank.pCellDataArrayHead == null || !Applies)
			{
				return;
			}
			Load();
			string key = Path.GetFileName(ncerName);
			if (!_banks.TryGetValue(key, out List<List<short[]>> cells))
			{
				return;
			}
			int count = Math.Min(cells.Count, bank.pCellDataArrayHead.Length);
			for (int c = 0; c < count; c++)
			{
				GlobalScope.NNSG2dCellData cell = bank.pCellDataArrayHead[c];
				List<short[]> oams = cells[c];
				int n = Math.Min(oams.Count, cell.pOamAttrArray?.Length ?? 0);
				for (int i = 0; i < n; i++)
				{
					short[] o = oams[i];
					// Steam's rectangle on Steam's sheet stays the source; the phone's
					// placement is the destination. drawImage takes the two sizes separately.
					cell.pOamAttrArray[i].place(o[0], o[1], o[2], o[3], o[4]);
				}
			}
			lock (_reported)
			{
				if (_reported.Add(key))
				{
					Log.Write(LogChannel.File, "steam cells: phone placement applied to " + key);
				}
			}
		}
	}
}
