// Generated by Tools/gen_menu_backgrounds.py - do not edit.
//
// What is drawn behind each menu screen. Followed through the game rather
// than matched by name: buildMenu("<screen>") says which class owns a
// screen, m_pCurrent[i] = m_MenuX fixes that class as WMENU_KIND i, and
// main_bg_nscr[i] is the cell bank for it.
//
// The bank is drawn from a shared sheet - bgLoad names menu_bg_01.NCGR for
// all of them - which is why these never appeared: the cell reader looks
// for a sheet of the same name and there is none.

using System;
using System.Collections.Generic;

namespace FF3.ContentTool.Editor
{
	internal static class MenuBackgrounds
	{
		/// <summary>Screen name in a .xbn to the cell bank drawn behind it.</summary>
		public static readonly IReadOnlyDictionary<string, string> ForScreen =
			new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
			{
				{ "equip", "files/menu_003_soubi_01.NSCR" },   // CWMenuEquip, kind 2
				{ "job", "files/menu_006_job.NSCR" },   // CWMenuJob, kind 5
				{ "magic", "files/menu_002_magic.NSCR" },   // CWMenuMagic, kind 1
				{ "main_menu", "files/menu_000_main.NSCR" },   // CWMenuMain, kind 9
				{ "menu_item", "files/menu_001_item.NSCR" },   // CWMenuItem, kind 0
				{ "status", "files/menu_004_status.NSCR" },   // CWMenuStatus, kind 3
			};

		// Left out on purpose. These classes build more than one screen,
		// and which background belongs to which is not in this chain - the
		// class only pins down one WMENU_KIND:
		//   CWMenuConfig (kind 6, menu_010_config.NSCR) builds config, tips_list
		//   CWMenuSuspend (kind 7, menu_008_tyudan.NSCR) builds now_suspending, suspend_, suspend_end, suspend_write_failed
		//   CWMenuSave (kind 8, menu_009_save.NSCR) builds suspend_failed, suspend_write_failed
	}
}
