using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.IsolatedStorage;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.GamerServices;
using Microsoft.Xna.Framework.Graphics;
using OpenFF.Platform;
using OpenFF.Resources;

internal static partial class GlobalScope
{
	public static partial class itm
	{
		public const int NormalItemMax = 384;

		public const int ImportantItemMax = 64;

		private const int ConsumptionItemMax = 256;

		private const int WeaponItemMax = 256;

		private const int ProtectionItemMax = 256;

		private const int MagicItemMax = 256;

		public const CATEGORY CATEGORY_ERR = CATEGORY.CATEGORY_ERR;

		public const CATEGORY CATEGORY_CONSUMPTION = CATEGORY.CATEGORY_CONSUMPTION;

		public const CATEGORY CATEGORY_WEAPON = CATEGORY.CATEGORY_WEAPON;

		public const CATEGORY CATEGORY_PROTECTION = CATEGORY.CATEGORY_PROTECTION;

		public const CATEGORY CATEGORY_MAGIC = CATEGORY.CATEGORY_MAGIC;

		public const CATEGORY CATEGORY_IMPORTANT = CATEGORY.CATEGORY_IMPORTANT;

		public const CATEGORY CATEGORY_MAX = CATEGORY.CATEGORY_MAX;

		public const WEAPON_SYSTEM WEAPON_UNARMED = WEAPON_SYSTEM.WEAPON_UNARMED;

		public const WEAPON_SYSTEM WEAPON_KNIFE = WEAPON_SYSTEM.WEAPON_KNIFE;

		public const WEAPON_SYSTEM WEAPON_SWORD = WEAPON_SYSTEM.WEAPON_SWORD;

		public const WEAPON_SYSTEM WEAPON_CLUB = WEAPON_SYSTEM.WEAPON_CLUB;

		public const WEAPON_SYSTEM WEAPON_MACE = WEAPON_SYSTEM.WEAPON_MACE;

		public const WEAPON_SYSTEM WEAPON_STICK = WEAPON_SYSTEM.WEAPON_STICK;

		public const WEAPON_SYSTEM WEAPON_ROD = WEAPON_SYSTEM.WEAPON_ROD;

		public const WEAPON_SYSTEM WEAPON_BOW = WEAPON_SYSTEM.WEAPON_BOW;

		public const WEAPON_SYSTEM WEAPON_ARROW = WEAPON_SYSTEM.WEAPON_ARROW;

		public const WEAPON_SYSTEM WEAPON_BOOK = WEAPON_SYSTEM.WEAPON_BOOK;

		public const WEAPON_SYSTEM WEAPON_CLAW = WEAPON_SYSTEM.WEAPON_CLAW;

		public const WEAPON_SYSTEM WEAPON_HAMMER = WEAPON_SYSTEM.WEAPON_HAMMER;

		public const WEAPON_SYSTEM WEAPON_AXE = WEAPON_SYSTEM.WEAPON_AXE;

		public const WEAPON_SYSTEM WEAPON_SPEAR = WEAPON_SYSTEM.WEAPON_SPEAR;

		public const WEAPON_SYSTEM WEAPON_THROW = WEAPON_SYSTEM.WEAPON_THROW;

		public const WEAPON_SYSTEM WEAPON_BELL = WEAPON_SYSTEM.WEAPON_BELL;

		public const WEAPON_SYSTEM WEAPON_HARP = WEAPON_SYSTEM.WEAPON_HARP;

		public const WEAPON_SYSTEM WEAPON_DARKSWORD = WEAPON_SYSTEM.WEAPON_DARKSWORD;

		public const WEAPON_SYSTEM WEAPON_NINJA_STAR = WEAPON_SYSTEM.WEAPON_NINJA_STAR;

		public const WEAPON_SYSTEM WEAPON_SYSTEM_MAX = WEAPON_SYSTEM.WEAPON_SYSTEM_MAX;

		public const WEAPON_SYSTEM NON_WEAPON = WEAPON_SYSTEM.NON_WEAPON;

		public const PROTECTION_SYSTEM PROTECTION_SHIELD = PROTECTION_SYSTEM.PROTECTION_SHIELD;

		public const PROTECTION_SYSTEM PROTECTION_HELMET = PROTECTION_SYSTEM.PROTECTION_HELMET;

		public const PROTECTION_SYSTEM PROTECTION_ARMOR = PROTECTION_SYSTEM.PROTECTION_ARMOR;

		public const PROTECTION_SYSTEM PROTECTION_GAUNTLET = PROTECTION_SYSTEM.PROTECTION_GAUNTLET;

		public const PROTECTION_SYSTEM PROTECTION_SYSTEM_MAX = PROTECTION_SYSTEM.PROTECTION_SYSTEM_MAX;

		public const PROTECTION_SYSTEM NON_PROTECTION = PROTECTION_SYSTEM.NON_PROTECTION;

		public const MAGIC_SYSTEM MAGIC_WHITE = MAGIC_SYSTEM.MAGIC_WHITE;

		public const MAGIC_SYSTEM MAGIC_BLACK = MAGIC_SYSTEM.MAGIC_BLACK;

		public const MAGIC_SYSTEM MAGIC_SUMMONS = MAGIC_SYSTEM.MAGIC_SUMMONS;

		public const MAGIC_SYSTEM MAGIC_SONG = MAGIC_SYSTEM.MAGIC_SONG;

		public const MAGIC_SYSTEM MAGIC_FENG_SHUI = MAGIC_SYSTEM.MAGIC_FENG_SHUI;

		public const MAGIC_SYSTEM MAGIC_ENEMY = MAGIC_SYSTEM.MAGIC_ENEMY;

		public const MAGIC_SYSTEM MAGIC_SYSTEM_MAX = MAGIC_SYSTEM.MAGIC_SYSTEM_MAX;

		public const TARGET_SELECT TARGET_SELECT_NONE = TARGET_SELECT.TARGET_SELECT_NONE;

		public const TARGET_SELECT TARGET_SELECT_ENEMY = TARGET_SELECT.TARGET_SELECT_ENEMY;

		public const TARGET_SELECT TARGET_SELECT_ENEMY_GROUP = TARGET_SELECT.TARGET_SELECT_ENEMY_GROUP;

		public const TARGET_SELECT TARGET_SELECT_ENEMY_ALL = TARGET_SELECT.TARGET_SELECT_ENEMY_ALL;

		public const TARGET_SELECT TARGET_SELECT_RANDOM_ENEMY = TARGET_SELECT.TARGET_SELECT_RANDOM_ENEMY;

		public const TARGET_SELECT TARGET_SELECT_RANDOM_ENEMY_GROUP = TARGET_SELECT.TARGET_SELECT_RANDOM_ENEMY_GROUP;

		public const TARGET_SELECT TARGET_SELECT_SELF = TARGET_SELECT.TARGET_SELECT_SELF;

		public const TARGET_SELECT TARGET_SELECT_FRIEND = TARGET_SELECT.TARGET_SELECT_FRIEND;

		public const TARGET_SELECT TARGET_SELECT_FRIEND_GROUP = TARGET_SELECT.TARGET_SELECT_FRIEND_GROUP;

		public const TARGET_SELECT TARGET_SELECT_FRIEND_ALL = TARGET_SELECT.TARGET_SELECT_FRIEND_ALL;

		public const TARGET_SELECT TARGET_SELECT_RANDOM_FRIEND = TARGET_SELECT.TARGET_SELECT_RANDOM_FRIEND;

		public const TARGET_SELECT TARGET_SELECT_RANDOM_FRIEND_GROUP = TARGET_SELECT.TARGET_SELECT_RANDOM_FRIEND_GROUP;

		public const TARGET_SELECT TARGET_SELECT_ALL = TARGET_SELECT.TARGET_SELECT_ALL;

		public const TARGET_POSITION TARGET_POSITION_ENEMY = TARGET_POSITION.TARGET_POSITION_ENEMY;

		public const TARGET_POSITION TARGET_POSITION_ENEMY_ABNORMAL = TARGET_POSITION.TARGET_POSITION_ENEMY_ABNORMAL;

		public const TARGET_POSITION TARGET_POSITION_SELF = TARGET_POSITION.TARGET_POSITION_SELF;

		public const TARGET_POSITION TARGET_POSITION_FRIEND = TARGET_POSITION.TARGET_POSITION_FRIEND;

		public const TARGET_POSITION TARGET_POSITION_FRIEND_ABNORMAL = TARGET_POSITION.TARGET_POSITION_FRIEND_ABNORMAL;

		public const ITEM_ATTRIBUTE ATTRIBUTE_RECOVERY = ITEM_ATTRIBUTE.ATTRIBUTE_RECOVERY;

		public const ITEM_ATTRIBUTE ATTRIBUTE_POISON = ITEM_ATTRIBUTE.ATTRIBUTE_POISON;

		public const ITEM_ATTRIBUTE ATTRIBUTE_ABSORPTION = ITEM_ATTRIBUTE.ATTRIBUTE_ABSORPTION;

		public const ITEM_ATTRIBUTE ATTRIBUTE_THUNDER = ITEM_ATTRIBUTE.ATTRIBUTE_THUNDER;

		public const ITEM_ATTRIBUTE ATTRIBUTE_ICE = ITEM_ATTRIBUTE.ATTRIBUTE_ICE;

		public const ITEM_ATTRIBUTE ATTRIBUTE_BLAZE = ITEM_ATTRIBUTE.ATTRIBUTE_BLAZE;

		public const ITEM_ATTRIBUTE ATTRIBUTE_WATER = ITEM_ATTRIBUTE.ATTRIBUTE_WATER;

		public const ITEM_ATTRIBUTE ATTRIBUTE_MUD = ITEM_ATTRIBUTE.ATTRIBUTE_MUD;

		public const ITEM_ATTRIBUTE ATTRIBUTE_HOLY = ITEM_ATTRIBUTE.ATTRIBUTE_HOLY;

		public const ITEM_ATTRIBUTE ATTRIBUTE_SKY = ITEM_ATTRIBUTE.ATTRIBUTE_SKY;

		public const ITEM_ATTRIBUTE ATTRIBUTE_DARK = ITEM_ATTRIBUTE.ATTRIBUTE_DARK;

		public const ITEM_ATTRIBUTE ATTRIBUTE_GHOST = ITEM_ATTRIBUTE.ATTRIBUTE_GHOST;

		public const ITEM_ATTRIBUTE ATTRIBUTE_HP_RECOVERY = ITEM_ATTRIBUTE.ATTRIBUTE_HP_RECOVERY;

		public const ITEM_ATTRIBUTE ATTRIBUTE_CURE = ITEM_ATTRIBUTE.ATTRIBUTE_CURE;

		public const ITEM_ATTRIBUTE ATTRIBUTE_REVIVAL = ITEM_ATTRIBUTE.ATTRIBUTE_REVIVAL;

		public const ITEM_ATTRIBUTE ATTRIBUTE_MP_RECOVERY = ITEM_ATTRIBUTE.ATTRIBUTE_MP_RECOVERY;

		public const ITEM_ATTRIBUTE ITEM_ATTRIBUTE_MAX = ITEM_ATTRIBUTE.ITEM_ATTRIBUTE_MAX;

		public const ITEM_CONDITION CONDITION_PARALYSIS = ITEM_CONDITION.CONDITION_PARALYSIS;

		public const ITEM_CONDITION CONDITION_SLEEP = ITEM_CONDITION.CONDITION_SLEEP;

		public const ITEM_CONDITION CONDITION_CONFUSION = ITEM_CONDITION.CONDITION_CONFUSION;

		public const ITEM_CONDITION CONDITION_STONY = ITEM_CONDITION.CONDITION_STONY;

		public const ITEM_CONDITION CONDITION_FROG = ITEM_CONDITION.CONDITION_FROG;

		public const ITEM_CONDITION CONDITION_SILENCE = ITEM_CONDITION.CONDITION_SILENCE;

		public const ITEM_CONDITION CONDITION_LILLIPUT = ITEM_CONDITION.CONDITION_LILLIPUT;

		public const ITEM_CONDITION CONDITION_DARKNESS = ITEM_CONDITION.CONDITION_DARKNESS;

		public const ITEM_CONDITION CONDITION_POISON = ITEM_CONDITION.CONDITION_POISON;

		public const ITEM_CONDITION CONDITION_DEATH = ITEM_CONDITION.CONDITION_DEATH;

		public const ITEM_CONDITION CONDITION_NEAR_DEATH = ITEM_CONDITION.CONDITION_NEAR_DEATH;

		public const ITEM_CONDITION ITEM_CONDITION_MAX = ITEM_CONDITION.ITEM_CONDITION_MAX;

		public const MAGIC_USE_KIND MAGIC_USE_KIND_ATTACK = MAGIC_USE_KIND.MAGIC_USE_KIND_ATTACK;

		public const MAGIC_USE_KIND MAGIC_USE_KIND_RECOVERY = MAGIC_USE_KIND.MAGIC_USE_KIND_RECOVERY;

		public const MAGIC_USE_KIND MAGIC_USE_KIND_ASSIST = MAGIC_USE_KIND.MAGIC_USE_KIND_ASSIST;

		public const MAGIC_USE_KIND MAGIC_USE_KIND_SPECIAL = MAGIC_USE_KIND.MAGIC_USE_KIND_SPECIAL;

		public const MAGIC_USE_KIND MAGIC_USE_KIND_MAX = MAGIC_USE_KIND.MAGIC_USE_KIND_MAX;

		public static int LIMIT_OF_ITEM = 99;

		public static int FINE_POWER = 9999;

	}
}
