// Generated from the decompiled command table - see Docs/Events.md.
//
// The engine dispatches a 16 bit opcode through a 298 entry table, and each handler
// reads its operands off the instruction stream. This table is those handlers' names
// and the operands each one reads, in order, which is what makes the bytecode
// walkable: an instruction is the opcode word plus the bytes its operands occupy.
//
// Do not edit by hand - run Tools/gen_opcodes.py, which rebuilds it from the sources.

namespace FF3.ContentTool
{
	internal enum Operand
	{
		Byte,
		Word,
		Dword,
		String
	}

	internal sealed class ScriptOp
	{
		public readonly string Name;
		public readonly Operand[] Operands;

		/// <summary>
		/// True where the handler reads operands inside a branch, so the instruction's
		/// length would depend on state the disassembler does not have. None of the 298
		/// currently do, which is why a linear walk is exact.
		/// </summary>
		public readonly bool Variable;

		/// <summary>
		/// Index of the operand the handler passes to engine.jump(), or -1. Not simply
		/// the first Dword: a conditional jump reads its flags first, and some read a
		/// whole coordinate box before the destination.
		/// </summary>
		public readonly int JumpOperand;

		/// <summary>
		/// True where the destination is chosen among several operands rather than being
		/// one of them - LabelRandomJump reads six addresses and takes one at random.
		/// </summary>
		public readonly bool JumpsToAny;

		public ScriptOp(string name, Operand[] operands, bool variable, int jumpOperand,
			bool jumpsToAny = false)
		{
			Name = name;
			Operands = operands;
			Variable = variable;
			JumpOperand = jumpOperand;
			JumpsToAny = jumpsToAny;
		}
	}

	internal static class ScriptOps
	{
		public const int Count = 298;

		private static readonly Operand[] None = new Operand[0];

		public static readonly ScriptOp[] Table =
		{
			new ScriptOp("NOPCommand", None, false, -1),
			new ScriptOp("NOPCommand", None, false, -1),
			new ScriptOp("NOPCommand", None, false, -1),
			new ScriptOp("NOPCommand", None, false, -1),
			new ScriptOp("NOPCommand", None, false, -1),
			new ScriptOp("endCommand", None, false, -1),
			new ScriptOp("flagOnEndCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("flagOffEndCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("waitCommand", new[] { Operand.Word }, false, -1),
			new ScriptOp("waitFlagOnCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("waitFlagOffCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("jumpCommand", new[] { Operand.Dword }, false, 0),
			new ScriptOp("flagOnJumpCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, 2),
			new ScriptOp("flagOffJumpCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, 2),
			new ScriptOp("callCommand", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("flagOnCallCommand", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("flagOffCallCommand", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("returnCommand", None, false, -1),
			new ScriptOp("flagOnReturnCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("flagOffReturnCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("flagOnCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("flagOffCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("flagReverseCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("setValueCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("incValueCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("decValueCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("addValueCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("mulValueCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("divValueCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ifValueJumpCommand", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, 4),
			new ScriptOp("startLogicCommand", new[] { Operand.Word }, false, -1),
			new ScriptOp("stopLogicCommand", new[] { Operand.Word }, false, -1),
			new ScriptOp("jumpIfLogicEnableCommand", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("jumpIfLogicDisableCommand", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_EventStart", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_EventEnd", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_FadeIn", new[] { Operand.Dword, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_FadeOut", new[] { Operand.Dword, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_DisplayMaskOn", new[] { Operand.Dword, Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_DisplayMaskOff", new[] { Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_BootCharacter", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_BootCharacter_AbsoluteCoordination", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_BootCharacter_RelativeCoordination", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_DeleteCharacter", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_DisplayCharacter", new[] { Operand.Word, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_GravityCharacter", new[] { Operand.Word, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_StartMotionCharacter", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_EndMotionCharacter", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_MoveCharacter_AbsoluteCoordination", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_MoveCharacter_RelativeCoordination", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_MoveCharacter_EndAutoIdle", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_MoveCharacter_StartRandom", new[] { Operand.Word, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_MoveCharacter_EndRandom", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_AbsoluteAngle", new[] { Operand.Word, Operand.Dword, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_RelativeAngle", new[] { Operand.Word, Operand.Dword, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_AbsoluteCoordination", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_LookCharacter", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_Init", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_StartLoop", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_EndLoop", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_EndAutoIdle", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetNextMessageAlignment", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_EndMessage", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_ChangeFontSize", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_CheckPlayer_State", new[] { Operand.Dword, Operand.Dword }, false, 1),
			new ScriptOp("ff3Command_AlterPlayer_State", new[] { Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_BootEventBattle", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_MapWarp", new[] { Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_AddItem", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetTreasureItem", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetRecovery", new[] { Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_BootShop", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_MoveCamera_AbsoluteCoordination", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_MoveCamera_RelativeCoordination", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_MoveCamera_LookPlayer", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_BootMovei", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_WithInCharacterJump", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, 7),
			new ScriptOp("ff3Command_WithOutCharacterJump", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, 7),
			new ScriptOp("ff3Command_BootEffect_AbsoluteCoordination", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_BootEffect_RelativeCoordination_Foolow", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_DeleteEffect", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_PauseEffect", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetEffect_Scale", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_Spring", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_FadeEndWait", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCamera_AbsoluteGaze", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCamera_RelativeGaze", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_ChangeCamera_Mode", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCamera_Type", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCamera_Angle", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_Scale", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_PlayBGM", new[] { Operand.Word, Operand.Byte, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_StopBGM", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_PlaySE", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_StartCamera_Vibration", new[] { Operand.Byte, Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_StartMessageWindow", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_DeleteMessageWindow", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_EndMessageWindow", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_WaitEndOfMessageJump", new[] { Operand.Word, Operand.Dword, Operand.Word }, false, 1),
			new ScriptOp("ff3Command_DeleteNameWindow", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_StartMessage2", new[] { Operand.Word, Operand.Dword, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_DeleteMessage2", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetTreasureMoney", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetNPCAiType", new[] { Operand.Word, Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_AddPartyPC", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SubPartyPC", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_AddPartyNPC", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SubPartyNPC", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_ChangePartyPC", new[] { Operand.Word, Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_CheckPartyAverageLevel", new[] { Operand.Dword, Operand.Byte, Operand.Dword }, false, 2),
			new ScriptOp("ff3Command_CheckPartyMemberNum", new[] { Operand.Dword, Operand.Byte, Operand.Dword }, false, 2),
			new ScriptOp("ff3Command_CheckPartyMemberRow", new[] { Operand.Word, Operand.Byte, Operand.Dword }, false, 2),
			new ScriptOp("ff3Command_PartyMemberFine", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_BootInn", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_CheckTurnType", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SubItem", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_UseItem_FlagOnJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("ff3Command_UseItem_FlagOffJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("ff3Command_CheckUseItem_Id", new[] { Operand.Word, Operand.Dword }, false, 1),
			new ScriptOp("ff3Command_CheckItem_Num", new[] { Operand.Word, Operand.Dword, Operand.Byte, Operand.Dword }, false, 3),
			new ScriptOp("ff3Command_TouchOnJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("ff3Command_TouchOffJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("ff3Command_ButtonOnJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("ff3Command_ButtonOffJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("ff3Command_SelectEndWait", new[] { Operand.Dword }, false, 0),
			new ScriptOp("ff3Command_SetCharacter_TalkMotion", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_MoveCamera_LookPlayer2", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCamera_PositionOffset", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCamera_TargetOffset", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCamera_ZoomOnOff", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCamera_ZoomState", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCamera_ZoomDegree", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCamera_ZoomMax", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCamera_ZoomMin", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCamera_ZoomSpeed", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCamera_BeforeEvent", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_Collision", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_GroundCollision", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_WallCollision", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_CharaCollision", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_MapJump", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_FixedTurn", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_StartBalloon", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_EndBalloon", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_PartyTalkEventOnJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("ff3Command_PartyTalkEventOffJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("ff3Command_CheckCharacterStatusJump", new[] { Operand.Word, Operand.Dword, Operand.Dword }, false, 2),
			new ScriptOp("ff3Command_CheckPartyPCMemberEnaleOnJump", new[] { Operand.Word, Operand.Dword }, false, 1),
			new ScriptOp("ff3Command_CheckPartyPCMemberEnaleOffJump", new[] { Operand.Word, Operand.Dword }, false, 1),
			new ScriptOp("ff3Command_CheckParty_NPCMemberEnaleOnJump", new[] { Operand.Word, Operand.Dword }, false, 1),
			new ScriptOp("ff3Command_CheckParty_NPCMemberEnaleOffJump", new[] { Operand.Word, Operand.Dword }, false, 1),
			new ScriptOp("ff3Command_AddJob", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SubJob", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_MotionSpeed", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_Alpha", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_BootNameEntry", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_CheckCharacter_StatusJump", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, 5),
			new ScriptOp("ff3Command_StartPartyTalk", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_EndPartyTalk", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_AbsoluteAngle2", new[] { Operand.Word, Operand.Dword, Operand.Word, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_RelativeAngle2", new[] { Operand.Word, Operand.Dword, Operand.Word, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_AbsoluteCoordination2", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_LookCharacter2", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_TurnCharacter_StartLoop2", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_ShadowAlpha", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_TurnTargetCharacter", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_StartMotionCharacterDX", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_WorldMapWarp", new[] { Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetMapJumpFlag", new[] { Operand.Byte, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetMapJumpFlagJump", new[] { Operand.Byte, Operand.Dword }, false, 1),
			new ScriptOp("ff3Command_StartWaorldPartyTalk", new[] { Operand.String, Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_EndWaorldPartyTalk", None, false, -1),
			new ScriptOp("ff3Command_SetPartyPCEquipItem", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetMapRotation", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_ChangeFaceEye", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_ChangeFaceMouth", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_MessagePermission", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_MessageWait", None, false, -1),
			new ScriptOp("ff3Command_EndMotionCharacterDX", new[] { Operand.Word, Operand.Byte, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetVehiclePosition", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCharacter_ItemEvent", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetBattleEscape", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetUpCharacter_FaceData", new[] { Operand.Word, Operand.String }, false, -1),
			new ScriptOp("ff3Command_CleanUpCharacter_FaceData", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCameraMargin", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCharacterDetectionRadius", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_StopSE", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetPartyMember_AllParameter", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetPartyMember_DefaultParameter", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetPartyMember_PhysicsAttackParameter", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetPartyMember_PhysicsDefenseParameter", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetPartyMember_MagicDefenseParameter", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetPartyMember_SkillParameter", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCharacterCollisionRadius_Sphere", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCharacterCollisionRadius_Box", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCharacterTouchRadius_Sphere", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCamera_Collision", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetUpBGM_Data", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_CleanUpBGM_Data", None, false, -1),
			new ScriptOp("ff3Command_SetHalfWayBGM_Save", None, false, -1),
			new ScriptOp("ff3Command_SetHalfWayBGM_Play", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetUpSE_Data", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_CleanUpSE_Data", None, false, -1),
			new ScriptOp("ff3Command_SetBGM_Volume", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetHalfWayBGM_Start", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetUpEffectData", new[] { Operand.String }, false, -1),
			new ScriptOp("ff3Command_CleanUpEffectData", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_LabelRandomJump", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1, true),
			new ScriptOp("ff3Command_SetRecovery2", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetConditionRecovery", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetMessagePosition", new[] { Operand.Dword, Operand.Word, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetMessageShadow", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetMessageStyle", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_CheckMapName", new[] { Operand.String, Operand.Dword, Operand.Dword }, false, 2),
			new ScriptOp("ff3Command_SetMapJump_SE", new[] { Operand.Byte, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCamera_PositionOffset2", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCamera_TargetOffset2", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetCamera_FOV", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetDispSelect", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetMessageColor", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_StartConnectionMenu", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_DisplayMapName", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_HideMapName", None, false, -1),
			new ScriptOp("ff3Command_LoadWorldBG", new[] { Operand.String }, false, -1),
			new ScriptOp("ff3Command_SetPositionWorldBG", new[] { Operand.Byte, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_AddPositionWorldBG", new[] { Operand.Byte, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetScrollWorldBG", new[] { Operand.Byte, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetVisibleWorldBG", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_FadeoutSub", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_FadeinSub", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_InputCheckJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("ff3Command_LoadWorldOBJ", new[] { Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("ff3Command_SetPositionWorldOBJ", new[] { Operand.Byte, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_AddPositionWorldOBJ", new[] { Operand.Byte, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetAlphaWorldOBJ", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetAutoAlphaWorldOBJ", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetVisibleWorldOBJ", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_AssginBGForMessage", new[] { Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetAutoAlphaMessage", new[] { Operand.Byte, Operand.Byte, Operand.Word, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetAutoBrightnessWorldBG", new[] { Operand.Byte, Operand.Byte, Operand.Word, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetBattleType", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetCamera_NearFarClip", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_ChangeStage", new[] { Operand.String }, false, -1),
			new ScriptOp("ff3Command_DisplayAllMessage", None, false, -1),
			new ScriptOp("ff3Command_ChangeColorCharacter", new[] { Operand.Word, Operand.String }, false, -1),
			new ScriptOp("ff3Command_GoToTitle", None, false, -1),
			new ScriptOp("ff3Command_MoveFixedSpeedCharacter_AbsoluteCoordination", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_MoveFixedSpeedCharacter_RelativeCoordination", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetCanBoardVehicle", new[] { Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetSendMessage", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_WaitInputSendMessage", None, false, -1),
			new ScriptOp("ff3Command_SetSignEffect", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetAreaChangeShutterFlag", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_CustomFadeSetting", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_StartRotateMove", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_EndRotateMove", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_StartWaveGravity", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_EndWaveGravity", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetPlayerLevel", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_ReleaseStageMap", None, false, -1),
			new ScriptOp("ff3Command_SetVehicleFieldNo", new[] { Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_MoveCharacter_AbsoluteCoordination2", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetItemUseMenuManager", None, false, -1),
			new ScriptOp("ff3Command_RestrictionItemUse", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_ChocoboBank", None, false, -1),
			new ScriptOp("ff3Command_BootPlainCharacter", new[] { Operand.Word, Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("ff3Command_CreateBindObject", new[] { Operand.Word, Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("ff3Command_BindMotion", new[] { Operand.Word, Operand.String }, false, -1),
			new ScriptOp("ff3Command_SetVisibleBindObject", new[] { Operand.Word, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_PlayStream", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_StopStream", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_ResetFollowNPCState", None, false, -1),
			new ScriptOp("ff3Command_CallSpecialMode", None, false, -1),
			new ScriptOp("ff3Command_CallSave", None, false, -1),
			new ScriptOp("ff3Command_CancelSetupMapSound", None, false, -1),
			new ScriptOp("ff3Command_RemoveMotion", new[] { Operand.Word, Operand.String }, false, -1),
			new ScriptOp("ff3Command_BootCharacterAsTopPlayer", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_CheckTopPlayerJob", new[] { Operand.Dword, Operand.Dword }, false, 1),
			new ScriptOp("ff3Command_CheckToPlayerJobLevel", new[] { Operand.Byte, Operand.Dword }, false, 1),
			new ScriptOp("ff3Command_CheckTopPlayer", new[] { Operand.Byte, Operand.Dword }, false, 1),
			new ScriptOp("ff3Command_SetShowWorldMap", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetRestartAfterBattle", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_CheckJob", new[] { Operand.Byte, Operand.Dword, Operand.Dword }, false, 2),
			new ScriptOp("ff3Command_CheckJobLevel", new[] { Operand.Byte, Operand.Dword, Operand.Byte, Operand.Dword }, false, 3),
			new ScriptOp("ff3Command_PlayNaviSE", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetEnableVehicleCamHeight", new[] { Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetPartyMember_JobLevel", new[] { Operand.Word, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetHalfWayBGM_Start2", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_SetPreRideVehicle", new[] { Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_SetBeforeFieldNameJumpIndex", new[] { Operand.String, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_SetEnableViewVolumeClip", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("ff3Command_WithInCharacterJump2", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, 7),
			new ScriptOp("ff3Command_WithOutCharacterJump2", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, 7),
			new ScriptOp("ff3Command_SetPosition", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("ff3Command_StartRotateMoveSyncRotate", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Byte, Operand.Word }, false, -1),
			new ScriptOp("ff3Command_AllEffectFinishWait", None, false, -1),
			new ScriptOp("ff3Command_StartMotionToRideVehicle", new[] { Operand.Word }, false, -1),
			new ScriptOp("ff3Command_InAppPurchase", None, false, -1),
		};

		public static ScriptOp Get(int opcode)
		{
			return opcode >= 0 && opcode < Table.Length ? Table[opcode] : null;
		}
	}
}
