// Generated from libff4.so's dispatch table and handlers - see Docs/Editor.md.
//
// FF4 3D runs FF3's script engine with its own command table: 500 entries, 222 of them
// FF3's command at FF3's number, 48 of those reading different operands, and 255 that
// FF3 does not have. Each handler's operand reads were listed from its machine code,
// which is the same evidence gen_opcodes.py takes from FF3's source.
//
// Do not edit by hand - run Tools/gen_opcodes_ff4.py <libff4.so>, which rebuilds it.

namespace FF3.Script
{
	internal static class ScriptOpsFf4
	{
		public const int Count = 500;

		/// <summary>FF4's exit declaration: trigger, map, arrival x y z, facing, box corners.</summary>
		public const int SetInsideMapJump = 333;

		private static readonly Operand[] None = new Operand[0];

		public static readonly ScriptOp[] Table =
		{
			new ScriptOp("NOPCommand", None, false, -1),
			new ScriptOp("NOPCommand", None, false, -1),
			new ScriptOp("NOPCommand", None, false, -1),
			new ScriptOp("NOPCommand", None, false, -1),
			new ScriptOp("NOPCommand", None, false, -1),
			new ScriptOp("endCommand", None, false, -1),
			new ScriptOp("flagOnEndCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("flagOffEndCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("waitCommand", new[] { Operand.Word }, false, -1),
			new ScriptOp("waitFlagOnCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("waitFlagOffCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("jumpCommand", new[] { Operand.Dword }, false, 0),
			new ScriptOp("flagOnJumpCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, 2),
			new ScriptOp("flagOffJumpCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, 2),
			new ScriptOp("callCommand", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("flagOnCallCommand", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("flagOffCallCommand", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("returnCommand", None, false, -1),
			new ScriptOp("flagOnReturnCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("flagOffReturnCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_FlagON", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("flagOffCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("flagReverseCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("setValueCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("incValueCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("decValueCommand", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("addValueCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("mulValueCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("divValueCommand", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("ifValueJumpCommand", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, 4),
			new ScriptOp("startLogicCommand", new[] { Operand.Word }, false, -1),
			new ScriptOp("stopLogicCommand", new[] { Operand.Word }, false, -1),
			new ScriptOp("jumpIfLogicEnableCommand", new[] { Operand.Word, Operand.Dword }, false, 1),
			new ScriptOp("jumpIfLogicDisableCommand", new[] { Operand.Word, Operand.Dword }, false, 1),
			new ScriptOp("babilCommand_EventStart", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_EventEnd", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_FadeIn", new[] { Operand.Dword, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_FadeOut", new[] { Operand.Dword, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_DisplayMaskOn", new[] { Operand.Dword, Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_DisplayMaskOff", new[] { Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_BootCharacter", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BootCharacter_AbsoluteCoordination", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BootCharacter_RelativeCoordination", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_DeleteCharacter", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_DisplayCharacter", new[] { Operand.Word, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_GravityCharacter", new[] { Operand.Word, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_StartMotionCharacter", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_EndMotionCharacter", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_BattleResultJump", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, 2),
			new ScriptOp("babilCommand_MoveCharacter_RelativeCoordination", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_MoveCharacter_EndAutoIdle", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_MoveCharacter_StartRandom", new[] { Operand.Word, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_MoveCharacter_EndRandom", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_GlayScaleCharacter", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_GlayScaleMap", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetFormation", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetMemberForOrder", new[] { Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_AddDesionList", new[] { Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_ClearDesionList", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_TurnCharacter_EndLoop", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_TurnCharacter_EndAutoIdle", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetNextMessageAlignment", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_EndMessage", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_ChangeFontSize", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_CheckPlayer_State", new[] { Operand.Dword, Operand.Dword }, false, 1),
			new ScriptOp("babilCommand_AlterPlayer_State", new[] { Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_BootEventBattle", new[] { Operand.Word, Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_MapWarp", new[] { Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_AddItem", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetTreasureItem", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_VramRefresh", None, false, -1),
			new ScriptOp("babilCommand_BootShop", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_MoveCamera_AbsoluteCoordination", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_MoveCamera_RelativeCoordination", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_ResurrectionDeadMember", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BootMovei", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BootProgram", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_GlayScaleCharaAll", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_BootEffect_AbsoluteCoordination", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BootEffect_RelativeCoordination_Foolow", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_DeleteEffect", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_PauseEffect", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetEffect_Scale", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_ClippingBBSetting", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_FadeEndWait", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCamera_AbsoluteGaze", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCamera_RelativeGaze", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_ChangeCamera_Mode", None, false, -1),
			new ScriptOp("babilCommand_ConditionRecoveryByCharacter", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_DisarmamentByID_SiteSpecification", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCharacter_Scale", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_PlayBGM", new[] { Operand.Word, Operand.Byte, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_StopBGM", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_PlaySE", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_StartCamera_Vibration", new[] { Operand.Byte, Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_StartMessageWindow", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_DeleteMessageWindow", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_CE_StartVoice", new[] { Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_EndVoice", None, false, -1),
			new ScriptOp("babilCommand_BGMDivideLoadDataTypeSpecific", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_StartMessage", new[] { Operand.Word, Operand.Dword, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_DeleteMessage", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetTreasureMoney", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_StartVoice2", new[] { Operand.String, Operand.Byte, Operand.Byte, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_AddPartyPC", new[] { Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SubPartyPC", new[] { Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetRewardMessage", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetRewardMessageInterval", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_ChangePartyPC", new[] { Operand.Word, Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SyncCharacterLv", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CheckPartyMemberNum", new[] { Operand.Dword, Operand.Byte, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_ExecuteRewardMessageWindow", None, false, -1),
			new ScriptOp("babilCommand_SetVehicleRot", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BootInn", new[] { Operand.Word, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCharacter_CheckTurnType", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SubItem", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_UseItem_FlagOnJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("babilCommand_UseItem_FlagOffJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("babilCommand_CheckUseItem_Id", new[] { Operand.Word, Operand.Dword }, false, 1),
			new ScriptOp("babilCommand_CheckItem_Num", new[] { Operand.Word, Operand.Dword, Operand.Byte, Operand.Dword }, false, 3),
			new ScriptOp("babilCommand_TouchOnJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("babilCommand_TouchOffJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("babilCommand_ButtonOnJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("babilCommand_ButtonOffJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("babilCommand_SelectEndWait", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, 4),
			new ScriptOp("babilCommand_SetCharacter_TalkMotion", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_MoveCamera_LookPlayer2", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetCamera_PositionOffset", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCamera_TargetOffset", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_CameraPos", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_CameraTarget", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommands_WaitByLocale", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_SetCamera_BeforeEvent", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCharacter_Collision", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCharacter_GroundCollision", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCharacter_WallCollision", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCharacter_CharaCollision", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BudgetAdjust", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCharacter_FixedTurn", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_CheckCharacterStatusJump", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, 2),
			new ScriptOp("babilCommand_CheckPartyPCMemberEnaleOnJump", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CheckPartyPCMemberEnaleOffJump", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_SetCharacter_MotionSpeed", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCharacter_Alpha", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_BootNameEntry", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_CheckCharacter_StatusJump", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_AutoRotation", new[] { Operand.Byte, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_ClearCountJump", new[] { Operand.Byte, Operand.Dword }, false, 1),
			new ScriptOp("babilCommand_TurnCharacter_AbsoluteAngle2", new[] { Operand.Word, Operand.Dword, Operand.Word, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_TurnCharacter_RelativeAngle2", new[] { Operand.Word, Operand.Dword, Operand.Word, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_TurnCharacter_AbsoluteCoordination2", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_TurnCharacter_LookCharacter2", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_TurnCharacter_StartLoop2", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetCharacter_ShadowAlpha", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetCharacter_TurnTargetCharacter", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_StartMotionCharacterDX", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_WorldMapWarp", new[] { Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommands_ChangeLocalizeDirectory", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommands_ChangeGlobalDirectory", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommands_JumpByLocale", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, 2),
			new ScriptOp("babilCommands_SetMessageAlignment", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetPartyPCEquipItem", new[] { Operand.Dword, Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetMapRotation", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_ChangeFaceEye", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_ChangeFaceMouth", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_MessagePermission", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_MessageWait", None, false, -1),
			new ScriptOp("babilCommand_EndMotionCharacterDX", new[] { Operand.Word, Operand.Byte, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetVehiclePosition", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_SetBattleEscape", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetUpCharacter_FaceData", new[] { Operand.Word, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CleanUpCharacter_FaceData", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_MoveVolumeSE", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetCharacterDetectionRadius", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_StopSE", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetPartyMember_AllParameter", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetPartyMember_DefaultParameter", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetPartyMember_PhysicsAttackParameter", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetPartyMember_PhysicsDefenseParameter", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetPartyMember_MagicDefenseParameter", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_PlayEffectEx", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCharacterCollisionRadius_Sphere", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetCharacterCollisionRadius_Box", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetSymbolCharacter", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCamera_Collision", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetUpBGM_Data", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_CleanUpBGM_Data", None, false, -1),
			new ScriptOp("babilCommand_SetHalfWayBGM_Save", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetHalfWayBGM_Play", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetUpSE_Data", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_CleanUpSE_Data", None, false, -1),
			new ScriptOp("babilCommand_SetBGM_Volume", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetHalfWayBGM_Start", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetUpEffectData", new[] { Operand.String }, false, -1),
			new ScriptOp("babilCommand_CleanUpEffectData", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_LabelRandomJump", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1, true),
			new ScriptOp("babilCommand_SetRecovery2", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetConditionRecovery", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetMessagePosition", new[] { Operand.Dword, Operand.Word, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetMessageShadow", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetUpPochka", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_CheckMapName", new[] { Operand.String, Operand.Dword, Operand.Dword }, false, 2),
			new ScriptOp("babilCommand_SetMapJump_SE", new[] { Operand.Byte, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_SetCamera_FOV", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetDispSelect", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetMessageColor", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_StartConnectionMenu", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_DisplayMapName", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_HideMapName", None, false, -1),
			new ScriptOp("babilCommand_NavimapFullDisclosure", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_NavimapSetDisclosureRateVisibility", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SlotSEPlay", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SlotSEStop", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SlotSESetVolume", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SlotBGMPlay", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SlotBGMStop", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SlotBGMSetVolume", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_LoadWorldOBJ", new[] { Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("babilCommand_SetPositionWorldOBJ", new[] { Operand.Byte, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_AddPositionWorldOBJ", new[] { Operand.Byte, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetAlphaWorldOBJ", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetAutoAlphaWorldOBJ", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetVisibleWorldOBJ", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_AssginBGForMessage", new[] { Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetAutoAlphaMessage", new[] { Operand.Byte, Operand.Byte, Operand.Word, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetAutoBrightnessWorldBG", new[] { Operand.Byte, Operand.Byte, Operand.Word, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetBattleType", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetCamera_NearFarClip", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_ChangeStage", new[] { Operand.String }, false, -1),
			new ScriptOp("babilCommand_DisplayAllMessage", None, false, -1),
			new ScriptOp("babilCommand_ChangeColorCharacter", new[] { Operand.Word, Operand.String }, false, -1),
			new ScriptOp("babilCommand_GoToTitle", None, false, -1),
			new ScriptOp("babilCommand_MoveFixedSpeedCharacter_AbsoluteCoordination", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_MoveFixedSpeedCharacter_RelativeCoordination", new[] { Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCanBoardVehicle", new[] { Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetSendMessage", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_WaitInputSendMessage", None, false, -1),
			new ScriptOp("babilCommand_SetSignEffect", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetAreaChangeShutterFlag", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CustomFadeSetting", new[] { Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_StartRotateMove", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_EndRotateMove", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_StartWaveGravity", new[] { Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_EndWaveGravity", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetPlayerLevel", new[] { Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_ReleaseStageMap", None, false, -1),
			new ScriptOp("babilCommand_SetVehicleFieldNo", new[] { Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_MoveCharacter_AbsoluteCoordination2", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetItemUseMenuManager", None, false, -1),
			new ScriptOp("babilCommand_RestrictionItemUse", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_ChocoboBank", None, false, -1),
			new ScriptOp("babilCommand_CE_CharaAlpha", new[] { Operand.Byte, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_CreateBindObject", new[] { Operand.Word, Operand.String, Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BindMotion", new[] { Operand.Word, Operand.String }, false, -1),
			new ScriptOp("babilCommand_SetVisibleBindObject", new[] { Operand.Word, Operand.String, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_PlayStream", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_StopStream", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_StonePartySetting", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CallSpecialMode", None, false, -1),
			new ScriptOp("babilCommand_CallSave", None, false, -1),
			new ScriptOp("babilCommand_CancelSetupMapSound", None, false, -1),
			new ScriptOp("babilCommand_RemoveMotion", new[] { Operand.Word, Operand.String }, false, -1),
			new ScriptOp("babilCommand_BootCharacterAsTopPlayer", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_CheckTopPlayer", new[] { Operand.Dword, Operand.Dword }, false, 1),
			new ScriptOp("babilCommand_CallEndRoll", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetRestartAfterBattle", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_UnUseCommand", None, false, -1),
			new ScriptOp("babilCommand_PlayNaviSE", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetEnableVehicleCamHeight", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_CreateToonTable", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SetHalfWayBGM_Start2", None, false, -1),
			new ScriptOp("babilCommand_SetPreRideVehicle", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetBeforeFieldNameJumpIndex", new[] { Operand.String, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetEnableViewVolumeClip", new[] { Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_WithInCharacterJump2", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, 7),
			new ScriptOp("babilCommand_WithOutCharacterJump2", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, 7),
			new ScriptOp("babilCommand_SetPosition", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_StartRotateMoveSyncRotate", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Word, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_AllEffectFinishWait", None, false, -1),
			new ScriptOp("babilCommand_CE_EventSkipJump", new[] { Operand.Dword }, false, 0),
			new ScriptOp("babilCommand_CE_SetupCharacter", new[] { Operand.Byte, Operand.String, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_CleanupCharacter", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_SetupMotion", new[] { Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_CleanupMotion", new[] { Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_StartMotion", new[] { Operand.Byte, Operand.Dword, Operand.Byte, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetMap", new[] { Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_CleanupMap", None, false, -1),
			new ScriptOp("babilCommand_SetMapJumpObject", new[] { Operand.String, Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetMapJumpObjectValidity", new[] { Operand.String, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetupCameraMotion", new[] { Operand.Dword, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_CleanupCameraMotion", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_PlayCameraMotion", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_WaitTillEndOfCameraMotion", None, false, -1),
			new ScriptOp("babilCommand_CE_StartAnimation", new[] { Operand.Byte, Operand.Dword, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_PauseAnimation", new[] { Operand.Byte, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_WaitTillEndOfMotion", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_SetEnbleViewClip", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_SetupExpression", new[] { Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_CleanupExpression", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_ChangeExpression", new[] { Operand.Byte, Operand.Byte, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetLightForCharacter", new[] { Operand.Byte, Operand.Byte, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Byte, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_SetLightEnableForCharacter", new[] { Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_SetShadingMode", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_SetToonTable", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_StartEvent", None, false, -1),
			new ScriptOp("babilCommand_CE_EndEvent", None, false, -1),
			new ScriptOp("babilCommand_CE_ShowMessageWindow", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_StartMapAnimation", new[] { Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_MapStartMotion", new[] { Operand.Dword, Operand.Byte, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetMapMotion", new[] { Operand.Dword, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_SetSkip", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_StopSkip", None, false, -1),
			new ScriptOp("babilCommand_CE_DisplayCharacter", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_EndMotionCharacter", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_AddShadowVolume", new[] { Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_ShadowVolumeONOFF", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetInsideMapJump", new[] { Operand.String, Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetOutsideMapJump", new[] { Operand.String, Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_OpenCharacterNameWindow", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CloseCharacterNameWindow", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_ConteEventJumpAndReturnMapJamp", new[] { Operand.Byte, Operand.Byte, Operand.String, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_Confirm", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_ConfirmWait", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, 3),
			new ScriptOp("babilCommand_CE_SetBindObject", new[] { Operand.String, Operand.Byte, Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_LoadBG", new[] { Operand.Dword, Operand.String, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_setBGAlpha", new[] { Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_setTelopMassage", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_setWorldCameraPosAndTargetOffset", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_setPosition", new[] { Operand.Byte, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_setRotation", new[] { Operand.Byte, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_CE_setFog", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_SetMapjumpBGMOperation", new[] { Operand.String, Operand.Dword, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_CE_StopBGM_Streaming", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_VoiceSkipOn", None, false, -1),
			new ScriptOp("babilCommand_CE_SetCharecterAsync", new[] { Operand.Byte, Operand.String, Operand.String, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetMotionAsync", new[] { Operand.Byte, Operand.String, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_WaitSetCharacter", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_CE_WaitSetMotion", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_EffectFollow", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Byte, Operand.String, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_CallProgram", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_CallProgParam", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_EffectFollowCamera", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CleanUpEffectData2", new[] { Operand.String }, false, -1),
			new ScriptOp("babilCommand_SoundReset", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SEDivideLoad", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_BGMDivideLoad", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_SoundDataDivideLoadWait", None, false, -1),
			new ScriptOp("babilCommand_CE_SetPauseMotion", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_3DSSetup", new[] { Operand.Word, Operand.String, Operand.String, Operand.String, Operand.String }, false, -1),
			new ScriptOp("babilCommand_3DSRelease", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_3DSSetVisiblity", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_3DSSetPosition", new[] { Operand.Word, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_3DSSetAlpha", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetChacterOffset", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_bootAlarmAttrSE", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_bootTrapInAttrSE", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_bootTrapOutAttrSE", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_bootActionMovingAttrSE", new[] { Operand.Word, Operand.Word, Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_AttrSEPresetting", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_EffectLoadAsync", new[] { Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_CallBattle", new[] { Operand.Word, Operand.Byte, Operand.Byte, Operand.String, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_setConteNextPart", new[] { Operand.String, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CancelCameraControl", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_AddAbility", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_RemoveAbility", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCameraOffset", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetCondition", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CallPaint", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_EventStart", None, false, -1),
			new ScriptOp("babilCommand_BTL_EventEnd", None, false, -1),
			new ScriptOp("babilCommand_BTL_SetupCharacter", new[] { Operand.Byte, Operand.String, Operand.String }, false, -1),
			new ScriptOp("babilCommand_BTL_CleanupCharacter", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_SetCharecterAsync", new[] { Operand.Byte, Operand.String, Operand.String, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_WaitSetCharacter", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_DisplayCharacter", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_SetupMotion", new[] { Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("babilCommand_BTL_CleanupMotion", new[] { Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("babilCommand_BTL_StartMotion", new[] { Operand.Byte, Operand.Dword, Operand.Byte, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_EndMotionCharacter", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_SetMotionAsync", new[] { Operand.Byte, Operand.String, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_WaitSetMotion", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_SetMap", new[] { Operand.String }, false, -1),
			new ScriptOp("babilCommand_BTL_CleanupMap", None, false, -1),
			new ScriptOp("babilCommand_BTL_StartMapAnimation", new[] { Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_MapStartMotion", new[] { Operand.Dword, Operand.Byte, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_SetMapMotion", new[] { Operand.Dword, Operand.String }, false, -1),
			new ScriptOp("babilCommand_BTL_SetupCameraMotion", new[] { Operand.Dword, Operand.String }, false, -1),
			new ScriptOp("babilCommand_BTL_CleanupCameraMotion", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_PlayCameraMotion", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_StartAnimation", new[] { Operand.Byte, Operand.Dword, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_SetEnbleViewClip", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_SetupExpression", new[] { Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("babilCommand_BTL_CleanupExpression", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_ChangeExpression", new[] { Operand.Byte, Operand.Byte, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_SetLightForCharacter", new[] { Operand.Byte, Operand.Byte, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Byte, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_SetLightEnableForCharacter", new[] { Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_SetShadingMode", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_SetToonTable", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_ShowHelpMessage", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_EraseHelpMessage", None, false, -1),
			new ScriptOp("babilCommand_SetRelationMapjumpToDoorAttr", new[] { Operand.String, Operand.String, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetDoor", new[] { Operand.String, Operand.String, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetupBGM", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_CleanupBGM", None, false, -1),
			new ScriptOp("babilCommand_CE_PlayBGM", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_StopBGM", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetVolumeBGM", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetupSE", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_CleanupSE", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_PlaySE", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_StopSE", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetVolumeSE", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetTelepo", new[] { Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetBattleBGM", new[] { Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_DeleteBindObject", new[] { Operand.Word, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_SetMapAsysnc", new[] { Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_AsysncMapSetUp", None, false, -1),
			new ScriptOp("babilCommand_ShiftState", new[] { Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_setMapMaterialAlpha", new[] { Operand.String, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_3DSSetup", new[] { Operand.Word, Operand.String, Operand.String, Operand.String, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_3DSRelease", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_CE_3DSSetVisiblity", new[] { Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_3DSSetPosition", new[] { Operand.Word, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_3DSSetAlpha", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_savePartySetting", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_restorePartySetting", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_setRelationOfMapjumpobjAndFlag", new[] { Operand.String, Operand.Word, Operand.Word, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_setFrameWait", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_PlaySE_slot", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_StopSE_slot", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetVolumeSE_slot", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SymbolCharacterResetting", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_setSound", new[] { Operand.Byte, Operand.Byte, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_StoreMagishipPos", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_LoadMagishipPos", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_DecantLevelChekcJump", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, 2),
			new ScriptOp("babilCommand_SetBackChocoboBackPoint", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetTresureBattleMapID", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_WaitTillEndOfCameraMotion", None, false, -1),
			new ScriptOp("babilCommand_BTL_SetSkip", new[] { Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_BTL_StopSkip", None, false, -1),
			new ScriptOp("babilCommand_FreeFileTable", None, false, -1),
			new ScriptOp("babilCommand_AllocFileTable", None, false, -1),
			new ScriptOp("babilCommand_BTL_SetupCharacterCustom", new[] { Operand.Byte, Operand.String, Operand.String, Operand.String }, false, -1),
			new ScriptOp("babilCommand_BTL_SetCharecterAsyncCustom", new[] { Operand.Byte, Operand.String, Operand.String, Operand.String, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetNextPart", None, false, -1),
			new ScriptOp("babilCommand_SymbolCharacterStore", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SymbolCharacterLoad", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CopyDecantAbility", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SaveCameraPosAndTarget", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_setScale", new[] { Operand.Byte, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CreateEffectTaskWalk", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CreateEffectTaskRun", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CreateEffectTaskWait", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_HPSetting", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_MPSetting", new[] { Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BGLoad", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.String, Operand.String, Operand.String }, false, -1),
			new ScriptOp("babilCommand_BGAlphaBlendSetting", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetVisiblePlane", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CreateBGAlphaBlendControlTask", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BGMContinueForConteEvent", new[] { Operand.Byte, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_NewTBoxIcon", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_EventCameraVibratLoopSetting", new[] { Operand.Dword, Operand.Byte, Operand.Byte }, false, -1),
			new ScriptOp("babilCommand_EventCameraSetFovyMove", new[] { Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_EvaluateMagneticEquipment", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetBindObject2", new[] { Operand.Byte, Operand.Byte, Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_BindObjectVisiblity", new[] { Operand.Byte, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_SetupExpressionAsync", new[] { Operand.Byte, Operand.String }, false, -1),
			new ScriptOp("babilCommand_CE_ShadowSetting", new[] { Operand.Byte, Operand.Byte, Operand.String, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_ShadowVisiblity", new[] { Operand.Byte, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CE_ShadowOffset", new[] { Operand.Byte, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_SetupSE", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_CleanupSE", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_PlaySE", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_BTL_StopSE", new[] { Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_ResetNaviMap", new[] { Operand.String, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_CreateCharacterFollowEffectTask", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetShadowScale", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_SetBGMDownParam", new[] { Operand.Word, Operand.Word, Operand.Word }, false, -1),
			new ScriptOp("babilCommand_StartBGMDown", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_ReverseBGMDown", new[] { Operand.Word }, false, -1),
			new ScriptOp("babilCommand_GURUGURUCameraPreset", new[] { Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
			new ScriptOp("babilCommand_GURUGURUCameraDo", new[] { Operand.Word, Operand.Dword, Operand.Dword, Operand.Dword, Operand.Dword }, false, -1),
		};
	}
}
