// Generated: what each script operand means - see Docs/Script-Language.md.
//
// The operand table says an instruction takes a word and three dwords. This says the
// word is a character and the dwords are a position, which is the difference between
// reading a script and staring at it.
//
// The names are not invented. Each operand is followed to the call it ends up in and
// the name is taken from the other side: ff3Command_PlaySE hands its four operands to
// MtxSENDS_Play(int SeqArcNo, int SeqNo, int Volume, int Pan), so that is what they
// are called. Operands that cannot be followed are left null rather than guessed at.
//
// Fixed is set where a value reaches VecFx32, which holds NDS fixed point - 1/4096ths
// of a unit, so 0x64000 is 100.0.
//
// Do not edit by hand - run Tools/gen_operand_names.py.

namespace FF3.Script
{
	internal static class ScriptOperands
	{
		/// <summary>Operand names per opcode; an entry or a name may be null.</summary>
		public static readonly string[][] Names =
		{
			new string[0],
			new string[0],
			new string[0],
			new string[0],
			new string[0],
			new string[0],
			new string[] { null, null },
			new string[] { null, null },
			new string[] { "frame" },
			new string[] { null, null },
			new string[] { null, null },
			new string[] { "toPC" },
			new string[] { null, null, "toPC" },
			new string[] { null, null, "toPC" },
			new string[] { "library", null },
			new string[] { null, null, "library", "id" },
			new string[] { null, null, "library", "id" },
			new string[0],
			new string[] { null, null },
			new string[] { null, null },
			new string[] { "group", "index" },
			new string[] { "group", "index" },
			new string[] { "group", "index" },
			new string[] { "group", "index", null },
			new string[] { "group", "index" },
			new string[] { "group", "index" },
			new string[] { "group", "index", null },
			new string[] { "group", "index", null },
			new string[] { "group", "index", null },
			new string[] { null, null, null, null, "toPC" },
			new string[] { "castNo" },
			new string[] { "castNo" },
			new string[] { null, null },
			new string[] { null, null },
			new string[] { null },
			new string[] { null },
			new string[] { null, "time", null },
			new string[] { null, "time", null },
			new string[] { null, "time", "r", "g", null, "shadow" },
			new string[] { null, "alpha" },
			new string[] { "id", null },
			new string[] { "id", "x", "y", "z", null },
			new string[] { "id", "hichIndex", "x", "y", "z", null },
			new string[] { "hichIndex", "autoDeleteFrame" },
			new string[] { "hichIndex", "hidden", null },
			new string[] { "hichIndex", null, null },
			new string[] { "hichIndex", "index", null, "blendFrame", "frame" },
			new string[] { "hichIndex" },
			new string[] { "hichIndex", "x", "y", "z", "frame" },
			new string[] { "hichIndex", "hichIndex", "x", "y", "z", "frame" },
			new string[] { "hichIndex" },
			new string[] { "hichIndex", null, null },
			new string[] { "hichIndex" },
			new string[] { "hichIndex", "rad", null, null },
			new string[] { "hichIndex", "rad", null, null },
			new string[] { "hichIndex", "x", "y", "z", null, null },
			new string[] { "hichIndex", "hichIndex", null, null },
			new string[] { null, null, null },
			new string[] { "hichIndex", "frame", null },
			new string[] { "hichIndex" },
			new string[] { null },
			new string[] { null },
			new string[] { null, null },
			new string[] { "messageColor" },
			new string[] { null, "toPC" },
			new string[] { null, null },
			new string[] { "id", "battleMapId" },
			new string[] { null, "x", "y", "z", null, "characterType", null },
			new string[] { null, null },
			new string[] { "hichIndex", "itemId", "flagGroup", "flagIndex", "enCountIndex", null },
			new string[] { null, null },
			new string[] { null, null },
			new string[] { "x", "y", "z", null, null },
			new string[] { "x", "y", "z", null, null },
			new string[] { "id" },
			new string[] { null, null },
			new string[] { "hichIndex", "x", "y", "z", "x", "y", "z", "toPC" },
			new string[] { "hichIndex", "x", "y", "z", "x", "y", "z", "toPC" },
			new string[] { "category", "member", null, null, "x", "y", "z" },
			new string[] { "category", "member", null, null, "hichIndex", "x", "y", "z" },
			new string[] { "id", null },
			new string[] { null, null },
			new string[] { null, null, "x", "y", "z" },
			new string[] { null },
			new string[] { null },
			new string[] { "x", "y", "z", null, null },
			new string[] { "x", "y", "z", null, null },
			new string[] { null },
			new string[] { null },
			new string[] { "x", "y", "z", null },
			new string[] { "hichIndex", "x", "y", "z", "autoScaleFrame" },
			new string[] { "BGMNo", "volume", "fadeinFrame" },
			new string[] { "fadeoutFrame" },
			new string[] { "seqArcNo", "seqNo", "volume", "pan" },
			new string[] { null, "frame", "speed", "x", "y", "z", null },
			new string[] { "pos" },
			new string[] { null },
			new string[] { null },
			new string[] { null, "toPC", null },
			new string[] { null },
			new string[] { "font", "msg_number", null, "m_MesDeleteFrame" },
			new string[] { null },
			new string[] { "hichIndex", "gold", "flagGroup", "flagIndex", null, null },
			new string[] { "hichIndex", "hichIndex", null },
			new string[] { null, null },
			new string[] { null, null },
			new string[] { null, null },
			new string[] { null, null },
			new string[] { null, null, null },
			new string[] { null, null, "toPC" },
			new string[] { null, null, "toPC" },
			new string[] { null, null, "toPC" },
			new string[] { null },
			new string[] { "type" },
			new string[] { "hichIndex", null },
			new string[] { null, null },
			new string[] { "toPC" },
			new string[] { "toPC" },
			new string[] { null, "toPC" },
			new string[] { "itemId", null, null, "toPC" },
			new string[] { "toPC" },
			new string[] { "toPC" },
			new string[] { "toPC" },
			new string[] { "toPC" },
			new string[] { "toPC" },
			new string[] { "hichIndex", "invalidActionMotion" },
			new string[] { "id", null, null },
			new string[] { "x", "y", "z", null, null, null },
			new string[] { "x", "y", "z", null, null, null },
			new string[] { null },
			new string[] { null },
			new string[] { null, "wasDown" },
			new string[] { null, "wasDown" },
			new string[] { null, "wasDown" },
			new string[] { null, "wasDown" },
			new string[] { null, null, null },
			new string[] { "hichIndex", null },
			new string[] { "hichIndex", null },
			new string[] { "hichIndex", null },
			new string[] { "hichIndex", null },
			new string[] { "hichIndex", null },
			new string[] { "hichIndex", null },
			new string[] { null, null },
			new string[] { "hichIndex" },
			new string[] { "toPC" },
			new string[] { "toPC" },
			new string[] { "playerId", null, "toPC" },
			new string[] { null, "toPC" },
			new string[] { null, "toPC" },
			new string[] { null, "toPC" },
			new string[] { null, "toPC" },
			new string[] { null },
			new string[] { null },
			new string[] { "hichIndex", "motionSpeed" },
			new string[] { "hichIndex", "rate", "autoAlphaFrame" },
			new string[] { null },
			new string[] { "playerId", null, null, null, null, "toPC" },
			new string[] { null },
			new string[] { null },
			new string[] { "hichIndex", "deg", null, null, null },
			new string[] { "hichIndex", "deg", null, null, null },
			new string[] { "hichIndex", "x", "y", "z", null, null, null },
			new string[] { "hichIndex", "hichIndex", null, null, null },
			new string[] { "hichIndex", "frame", null, null },
			new string[] { "hichIndex", "alpha", "autoShadowAlphaFrame" },
			new string[] { "hichIndex", "hichIndex", "targetLookFrame", null },
			new string[] { "hichIndex", "motionIndex", null, "motionBlend", "playFrame", "index" },
			new string[] { null, "x", "y", "z", null, "characterType", null },
			new string[] { null, "wasDown" },
			new string[] { null, "toPC" },
			new string[] { null, null, null, null, null, null },
			new string[0],
			new string[] { null, null, null, null, null, null },
			new string[] { null, null, null },
			new string[] { "hichIndex", null },
			new string[] { "hichIndex", null },
			new string[] { null },
			new string[0],
			new string[] { "hichIndex", null, null },
			new string[] { "index", "x", "y", "z", "x", "y", "z" },
			new string[] { "hichIndex", null },
			new string[] { "wasDown" },
			new string[] { "id", null },
			new string[] { "hichIndex" },
			new string[] { "wasDown" },
			new string[] { "hichIndex", null },
			new string[] { null, null, "fadeoutFrame" },
			new string[] { null },
			new string[] { null, null, null, null },
			new string[] { null, null, null, null },
			new string[] { null, null, null, null },
			new string[] { null, null, null, null },
			new string[] { null, null, null, null },
			new string[] { "hichIndex", null },
			new string[] { "hichIndex", "x", "y", "z" },
			new string[] { "hichIndex", null },
			new string[] { null },
			new string[] { "BGMNo" },
			new string[0],
			new string[0],
			new string[] { "leftVolume", "rightVolume" },
			new string[] { "SEGroupNo" },
			new string[0],
			new string[] { "leftVolume", "rightVolume", null },
			new string[] { "BGMNo", "volume", "fadeinFrame", null },
			new string[] { null },
			new string[] { null, null },
			new string[] { null, null, null, null, null, null },
			new string[] { null, null, null, null },
			new string[] { null, null, null, null, null, null },
			new string[] { null, null, null, null },
			new string[] { null },
			new string[] { "messageStyle", null },
			new string[] { null, null, "toPC" },
			new string[] { "args", null },
			new string[] { "x", "y", "z", null, null, null, null, null },
			new string[] { "x", "y", "z", null, null, null, null, null },
			new string[] { null, null },
			new string[] { "sel" },
			new string[] { "messageColor" },
			new string[] { null },
			new string[] { "szFilename" },
			new string[0],
			new string[] { "pFilename" },
			new string[] { null, null, null, null },
			new string[] { null, null, null, null },
			new string[] { null, "frame", null, null, null },
			new string[] { null, "visible" },
			new string[] { "time", null },
			new string[] { "time" },
			new string[] { "toPC" },
			new string[] { "idx", "filename" },
			new string[] { "idx", null, null, null },
			new string[] { "idx", null, null, null },
			new string[] { "alpha" },
			new string[] { "frame", "alpha" },
			new string[] { "idx", null },
			new string[] { null, "bGNumber", "x", "y", "w", "h" },
			new string[] { null, null, "frame", "startValue", "endValue" },
			new string[] { null, "planeA", "frame", null, null },
			new string[] { "battleType" },
			new string[] { "near", "far" },
			new string[] { null },
			new string[0],
			new string[] { "hichIndex", null },
			new string[0],
			new string[] { null, "x", "y", "z", null },
			new string[] { null, null, "x", "y", "z", null },
			new string[] { null, "can" },
			new string[] { "sendMessage" },
			new string[0],
			new string[] { "hichIndex", "eveFlagGroup", "eveFlagIndex", "x", "y", "z", null, null },
			new string[] { null },
			new string[] { null, null },
			new string[] { "hichIndex", "x", "y", "z", "x", "y", "z", "frame", "dir" },
			new string[] { "hichIndex" },
			new string[] { "hichIndex", "frame", null },
			new string[] { "hichIndex" },
			new string[] { null, null },
			new string[0],
			new string[] { null, "fieldNo" },
			new string[] { "hichIndex", "x", "y", "z", null },
			new string[0],
			new string[] { null },
			new string[0],
			new string[] { "id", null, null },
			new string[] { "hichIndex", null, "pObjname" },
			new string[] { "hichIndex", "pMotname" },
			new string[] { "hichIndex", "locate", "visible" },
			new string[] { null, null, null },
			new string[] { null },
			new string[0],
			new string[0],
			new string[0],
			new string[0],
			new string[] { "hichIndex", "motname" },
			new string[] { "id" },
			new string[] { null, "toPC" },
			new string[] { null, "toPC" },
			new string[] { null, "toPC" },
			new string[] { "showOnePicture" },
			new string[] { "wasDown" },
			new string[] { "wasDown", null, "toPC" },
			new string[] { "wasDown", null, null, "toPC" },
			new string[] { "wasDown", "frame" },
			new string[] { "enableCalcCamHeight" },
			new string[] { "playerId", null, "data" },
			new string[] { null, null, null },
			new string[] { null },
			new string[] { null, null },
			new string[] { "hichIndex", "enable" },
			new string[] { "hichIndex", "x", "y", "z", "x", "y", "z", "toPC" },
			new string[] { "hichIndex", "x", "y", "z", "x", "y", "z", "toPC" },
			new string[] { "hichIndex", "x", "y", "z" },
			new string[] { "hichIndex", "x", "y", "z", "x", "y", "z", "frame", "dir", null },
			new string[0],
			new string[] { "index" },
			new string[0],
		};

		/// <summary>Which operands are NDS fixed point, 1/4096ths of a unit.</summary>
		public static readonly bool[][] Fixed =
		{
			new bool[0],
			new bool[0],
			new bool[0],
			new bool[0],
			new bool[0],
			new bool[0],
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, false },
			new bool[0],
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false, false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false, false, false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, true, true, true, false },
			new bool[] { false, false, true, true, true, false },
			new bool[] { false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false, false, false },
			new bool[] { false },
			new bool[] { false, true, true, true, false },
			new bool[] { false, false, true, true, true, false },
			new bool[] { false },
			new bool[] { false, false, false },
			new bool[] { false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, true, true, true, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, true, true, true, false, false, false },
			new bool[] { false, false },
			new bool[] { false, false, false, false, false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { true, true, true, false, false },
			new bool[] { true, true, true, false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, true, true, true, true, true, true, false },
			new bool[] { false, true, true, true, true, true, true, false },
			new bool[] { false, false, false, false, true, true, true },
			new bool[] { false, false, false, false, false, true, true, true },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false, true, true, true },
			new bool[] { false },
			new bool[] { false },
			new bool[] { true, true, true, false, false },
			new bool[] { true, true, true, false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { true, true, true, false },
			new bool[] { false, true, true, true, false },
			new bool[] { false, false, false },
			new bool[] { false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, true, true, true, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false, false },
			new bool[] { false },
			new bool[] { false, false, false, false },
			new bool[] { false },
			new bool[] { false, false, false, false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false, false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false, false },
			new bool[] { true, true, true, false, false, false },
			new bool[] { true, true, true, false, false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false, false },
			new bool[] { false },
			new bool[] { false, false, false, false, false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false, false, false, false },
			new bool[] { false, false, false, false, false },
			new bool[] { false, true, true, true, false, false, false },
			new bool[] { false, false, false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, false, false, false },
			new bool[] { false, true, true, true, false, false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false, false, false, false, false },
			new bool[0],
			new bool[] { false, false, false, false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[0],
			new bool[] { false, false, false },
			new bool[] { false, true, true, true, true, true, true },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false, false },
			new bool[] { false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false },
			new bool[] { false, true, true, true },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[0],
			new bool[0],
			new bool[] { false, false },
			new bool[] { false },
			new bool[0],
			new bool[] { false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false, false, false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false, false },
			new bool[] { false, false },
			new bool[] { true, true, true, false, false, false, false, false },
			new bool[] { true, true, true, false, false, false, false, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false },
			new bool[0],
			new bool[] { false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false, false, false, false, false },
			new bool[] { false, false, false, false, false },
			new bool[] { false, false, false, false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[0],
			new bool[] { false, false },
			new bool[0],
			new bool[] { false, true, true, true, false },
			new bool[] { false, false, true, true, true, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[0],
			new bool[] { false, false, false, true, true, true, false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, true, true, true, true, true, true, false, false },
			new bool[] { false },
			new bool[] { false, false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[0],
			new bool[] { false, false },
			new bool[] { false, true, true, true, false },
			new bool[0],
			new bool[] { false },
			new bool[0],
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false, false },
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false },
			new bool[0],
			new bool[0],
			new bool[0],
			new bool[0],
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false },
			new bool[] { false, false, false },
			new bool[] { false, false, false, false },
			new bool[] { false, false },
			new bool[] { false },
			new bool[] { false, false, false },
			new bool[] { false, false, false },
			new bool[] { false },
			new bool[] { false, false },
			new bool[] { false, false },
			new bool[] { false, true, true, true, true, true, true, false },
			new bool[] { false, true, true, true, true, true, true, false },
			new bool[] { false, true, true, true },
			new bool[] { false, true, true, true, true, true, true, false, false, false },
			new bool[0],
			new bool[] { false },
			new bool[0],
		};

		public static string Name(int opcode, int operand)
		{
			return opcode >= 0 && opcode < Names.Length && Names[opcode] != null
				&& operand >= 0 && operand < Names[opcode].Length
				? Names[opcode][operand] : null;
		}

		public static bool IsFixed(int opcode, int operand)
		{
			return opcode >= 0 && opcode < Fixed.Length && Fixed[opcode] != null
				&& operand >= 0 && operand < Fixed[opcode].Length
				&& Fixed[opcode][operand];
		}
	}
}
