// The modding API reference, generated:
//
//   crystal api-docs [Docs/API.md] [--engine=<OpenFF.Engine.dll>]
//
// Reflects over the built OpenFF.Engine assembly - every public type and member, whether or not
// it carries a doc comment - and merges the summaries from the XML documentation file beside
// it. The output is Markdown, grouped the way a modder meets the API: the Game entry point,
// the services behind it, the handles and data they hand out, the object model, coroutines,
// events, saving, the mod loader, and the enumerations. Members without a summary are listed
// with an empty description and counted at the end, so a gap in the comments shows up in the
// document rather than as a missing type.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Xml.Linq;
using Crystal.Editor;

namespace Crystal
{
	internal static class ApiDocs
	{
		public static int Write(string output, string assemblyPath)
		{
			assemblyPath ??= OpenFFClient.EngineAssembly();
			if (assemblyPath == null || !File.Exists(assemblyPath))
			{
				Console.Error.WriteLine("OpenFF.Engine.dll was not found - build the solution first, or pass --engine=<path to the dll>");
				return 1;
			}
			Assembly assembly = Assembly.LoadFrom(Path.GetFullPath(assemblyPath));
			string xmlPath = Path.ChangeExtension(assemblyPath, ".xml");
			Dictionary<string, XElement> docs = LoadDocs(xmlPath);

			Type[] types = assembly.GetExportedTypes()
				.Where(t => !t.IsNested || t.DeclaringType.IsPublic)
				.OrderBy(t => t.FullName, StringComparer.Ordinal)
				.ToArray();
			List<(string Title, string Intro, List<Type> Types)> groups = Group(types);

			StringBuilder md = new StringBuilder();
			int memberCount = 0, undocumented = 0;
			md.AppendLine("# The OpenFF modding API");
			md.AppendLine();
			md.AppendLine("Generated by `crystal api-docs` from `" + Path.GetFileName(assemblyPath) + "` " + assembly.GetName().Version
				+ " and its XML documentation - do not edit by hand; run the command after changing the engine.");
			md.AppendLine("Everything here is reached from a mod through `using OpenFF;` (events under `OpenFF.Events`, the loader under");
			md.AppendLine("`OpenFF.Modding`). `Docs/Modding.md` is the tutorial; this is the reference.");
			md.AppendLine();
			md.AppendLine("## Contents");
			md.AppendLine();
			foreach ((string title, _, List<Type> members) in groups)
			{
				if (members.Count == 0) continue;
				md.AppendLine("- [" + title + "](#" + Anchor(title) + "): " + string.Join(", ", members.Select(t => "[`" + Display(t) + "`](#" + Anchor(Display(t)) + ")")));
			}
			md.AppendLine();
			foreach ((string title, string intro, List<Type> members) in groups)
			{
				if (members.Count == 0) continue;
				md.AppendLine("## " + title);
				md.AppendLine();
				if (!string.IsNullOrEmpty(intro))
				{
					md.AppendLine(intro);
					md.AppendLine();
				}
				foreach (Type type in members)
				{
					WriteType(md, type, docs, ref memberCount, ref undocumented);
				}
			}
			md.AppendLine("---");
			md.AppendLine();
			md.AppendLine(types.Length + " types, " + memberCount + " members" + (undocumented > 0 ? "; " + undocumented + " without a summary yet." : "."));

			Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(output)));
			File.WriteAllText(output, md.ToString().Replace("\r\n", "\n"));
			Console.WriteLine(types.Length + " type(s), " + memberCount + " member(s) -> " + output + (undocumented > 0 ? "; " + undocumented + " without a summary" : ""));
			return 0;
		}

		// ---- grouping ----

		private static List<(string, string, List<Type>)> Group(Type[] types)
		{
			List<(string, string, List<Type>)> groups = new List<(string, string, List<Type>)>
			{
				("The entry point", "`Game` is the one static class a mod starts from: every service is a property on it, and the world, events, saves and log hang off it.", new List<Type>()),
				("Services", "What the game does for a mod, as interfaces the client implements over the running game. A mod that registers its own implementation later in the load order replaces one for everybody.", new List<Type>()),
				("Handles and data", "What the services hand out: a character on the map, a party member, an item, a spell, a monster, the input state, a texture to draw.", new List<Type>()),
				("Services you write, objects and scenes", "A `GameService` lives as long as its mod; `Behaviour`s attach to `GameObject`s in a `Scene`, with `Awake`/`Start`/`Update` in the Unity manner. Scene files (`scenes/<map>.json`) put behaviours and points on a map without code.", new List<Type>()),
				("Coroutines and time", "`Game.Run(IEnumerator)` steps a routine once per frame; it yields a `Wait`.", new List<Type>()),
				("Events", "Published on `Game.Events` as the game runs; subscribe with `Game.Events.Subscribe<T>(handler)`.", new List<Type>()),
				("Saving", "A service that implements `ISaveable` gets a chunk of its own in every save slot, kept even when the mod is absent.", new List<Type>()),
				("Mods and loading", "How the client finds, loads and hot-reloads mod assemblies; `mod.json` is `ModDefinition`.", new List<Type>()),
				("Constants", "Enumerations and named ids.", new List<Type>()),
				("Other", "", new List<Type>()),
			};
			foreach (Type t in types)
			{
				string ns = t.Namespace ?? "";
				string name = Display(t);
				int index;
				if (t.FullName == "OpenFF.Game") index = 0;
				else if (ns == "OpenFF.Events" || name == "EventBus") index = 5;
				else if (ns == "OpenFF.Modding") index = 7;
				else if (name == "ISaveable" || name == "SaveChunks") index = 6;
				else if (t.IsEnum || name == "HeroMotion" || name == "MonsterMotion") index = 8;
				else if (t.IsInterface) index = 1;
				else if (name == "Wait" || name == "Coroutine" || name == "CoroutineRunner" || name == "GameTime") index = 4;
				else if (name == "GameService" || name == "ServiceRegistry" || name == "GameObject" || name == "Component" || name == "Behaviour" || name == "Transform"
					|| name == "Scene" || name == "World" || name == "MapObject" || name == "ScenePoint" || name == "SceneAttachment" || name == "SceneFile" || name == "SceneLoader" || name == "SceneInfo") index = 3;
				else if (t.IsClass || t.IsValueType) index = 2;
				else index = 9;
				groups[index].Item3.Add(t);
			}
			// The services in the order a mod meets them: talking and moving first, data next, the frame last.
			List<string> order = new List<string> { "IDialogue", "IHero", "INpcs", "IParty", "IItems", "IMagic", "IMonsters", "IShops", "IBattle", "IField", "ICamera", "IEffects", "IAudio", "IScreen", "IFlags" };
			groups[1].Item3.Sort((a, b) =>
			{
				int ia = order.IndexOf(a.Name), ib = order.IndexOf(b.Name);
				if (ia < 0) ia = int.MaxValue;
				if (ib < 0) ib = int.MaxValue;
				return ia != ib ? ia.CompareTo(ib) : string.CompareOrdinal(a.Name, b.Name);
			});
			return groups;
		}

		// ---- one type ----

		private static void WriteType(StringBuilder md, Type type, Dictionary<string, XElement> docs, ref int memberCount, ref int undocumented)
		{
			md.AppendLine("### " + Display(type));
			md.AppendLine();
			string kind = type.IsEnum ? "enum" : type.IsInterface ? "interface" : type.IsValueType ? "struct" : type.IsAbstract && type.IsSealed ? "static class" : type.IsAbstract ? "abstract class" : "class";
			string bases = "";
			if (!type.IsEnum && !type.IsInterface && type.BaseType != null && type.BaseType != typeof(object) && type.BaseType != typeof(ValueType))
			{
				bases = " : " + Display(type.BaseType);
			}
			Type[] interfaces = type.GetInterfaces().Where(i => i.IsPublic && (i.Namespace ?? "").StartsWith("OpenFF", StringComparison.Ordinal)).ToArray();
			if (interfaces.Length > 0)
			{
				bases += (bases.Length > 0 ? ", " : " : ") + string.Join(", ", interfaces.Select(Display));
			}
			md.AppendLine("`" + kind + " " + Display(type) + bases + "`" + (type.Namespace != "OpenFF" ? " - `" + type.Namespace + "`" : ""));
			md.AppendLine();
			string summary = Summary(docs, "T:" + DocName(type));
			if (!string.IsNullOrEmpty(summary))
			{
				md.AppendLine(summary);
				md.AppendLine();
			}

			if (type.IsEnum)
			{
				md.AppendLine("| Value | Meaning |");
				md.AppendLine("| --- | --- |");
				foreach (FieldInfo field in type.GetFields(BindingFlags.Public | BindingFlags.Static))
				{
					memberCount++;
					string text = Summary(docs, "F:" + DocName(type) + "." + field.Name);
					if (text.Length == 0) undocumented++;
					md.AppendLine("| `" + field.Name + "` = " + Convert.ToInt64(field.GetRawConstantValue()) + " | " + text + " |");
				}
				md.AppendLine();
				return;
			}

			List<(string Signature, string Text)> rows = new List<(string, string)>();
			BindingFlags flags = BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly;
			foreach (FieldInfo field in type.GetFields(flags).OrderBy(f => f.Name, StringComparer.Ordinal))
			{
				string mod = field.IsLiteral ? "const " : field.IsStatic ? "static " : field.IsInitOnly ? "readonly " : "";
				rows.Add((mod + Display(field.FieldType) + " " + field.Name, Summary(docs, "F:" + DocName(type) + "." + field.Name)));
			}
			foreach (PropertyInfo property in type.GetProperties(flags).OrderBy(p => p.Name, StringComparer.Ordinal))
			{
				MethodInfo accessor = property.GetGetMethod() ?? property.GetSetMethod();
				string mod = accessor != null && accessor.IsStatic ? "static " : "";
				string access = (property.CanRead && property.GetGetMethod() != null ? "get; " : "") + (property.CanWrite && property.GetSetMethod() != null ? "set; " : "");
				ParameterInfo[] indexParameters = property.GetIndexParameters();
				string name = indexParameters.Length > 0 ? "this[" + Parameters(indexParameters) + "]" : property.Name;
				rows.Add((mod + Display(property.PropertyType) + " " + name + " { " + access + "}", Summary(docs, "P:" + DocName(type) + "." + property.Name)));
			}
			foreach (EventInfo evt in type.GetEvents(flags).OrderBy(e => e.Name, StringComparer.Ordinal))
			{
				string mod = evt.GetAddMethod() != null && evt.GetAddMethod().IsStatic ? "static " : "";
				rows.Add((mod + "event " + Display(evt.EventHandlerType) + " " + evt.Name, Summary(docs, "E:" + DocName(type) + "." + evt.Name)));
			}
			foreach (MethodInfo method in type.GetMethods(flags).Where(m => !m.IsSpecialName).OrderBy(m => m.Name, StringComparer.Ordinal).ThenBy(m => m.GetParameters().Length))
			{
				if (method.DeclaringType == typeof(object)) continue;
				string mod = method.IsStatic ? "static " : "";
				string generic = method.IsGenericMethodDefinition ? "<" + string.Join(", ", method.GetGenericArguments().Select(a => a.Name)) + ">" : "";
				string id = "M:" + DocName(type) + "." + method.Name + (method.IsGenericMethodDefinition ? "``" + method.GetGenericArguments().Length : "") + ParameterIds(method.GetParameters());
				string text = Summary(docs, id);
				if (text.Length == 0)
				{
					// The parameter spelling is the fussy part of a doc id: fall back to the name alone.
					string prefix = "M:" + DocName(type) + "." + method.Name;
					KeyValuePair<string, XElement> near = docs.FirstOrDefault(d => d.Key == prefix || d.Key.StartsWith(prefix + "(", StringComparison.Ordinal) || d.Key.StartsWith(prefix + "`", StringComparison.Ordinal));
					if (near.Value != null) text = Text(near.Value.Element("summary"));
				}
				rows.Add((mod + Display(method.ReturnType) + " " + method.Name + generic + "(" + Parameters(method.GetParameters()) + ")", text));
			}
			foreach (Type nested in type.GetNestedTypes(BindingFlags.Public).OrderBy(n => n.Name, StringComparer.Ordinal))
			{
				rows.Add(((nested.IsEnum ? "enum " : "class ") + nested.Name, Summary(docs, "T:" + DocName(nested))));
			}

			if (rows.Count > 0)
			{
				md.AppendLine("| Member | What it does |");
				md.AppendLine("| --- | --- |");
				foreach ((string signature, string text) in rows)
				{
					memberCount++;
					if (text.Length == 0) undocumented++;
					md.AppendLine("| `" + signature.Replace("|", "\\|") + "` | " + text.Replace("|", "\\|") + " |");
				}
				md.AppendLine();
			}
		}

		// ---- names ----

		private static readonly Dictionary<Type, string> Keywords = new Dictionary<Type, string>
		{
			{ typeof(void), "void" }, { typeof(bool), "bool" }, { typeof(byte), "byte" }, { typeof(sbyte), "sbyte" }, { typeof(short), "short" },
			{ typeof(ushort), "ushort" }, { typeof(int), "int" }, { typeof(uint), "uint" }, { typeof(long), "long" }, { typeof(ulong), "ulong" },
			{ typeof(float), "float" }, { typeof(double), "double" }, { typeof(decimal), "decimal" }, { typeof(string), "string" }, { typeof(object), "object" }, { typeof(char), "char" },
		};

		private static string Display(Type type)
		{
			if (type.IsByRef) return Display(type.GetElementType());
			if (type.IsArray) return Display(type.GetElementType()) + "[]";
			if (Keywords.TryGetValue(type, out string keyword)) return keyword;
			if (type.IsGenericParameter) return type.Name;
			if (type.IsGenericType)
			{
				Type definition = type.GetGenericTypeDefinition();
				Type[] args = type.GetGenericArguments();
				if (definition == typeof(Nullable<>)) return Display(args[0]) + "?";
				string name = definition.Name;
				int tick = name.IndexOf('`');
				if (tick >= 0) name = name.Substring(0, tick);
				return name + "<" + string.Join(", ", args.Select(Display)) + ">";
			}
			if (type.IsNested) return Display(type.DeclaringType) + "." + type.Name;
			return type.Name;
		}

		private static string Parameters(ParameterInfo[] parameters)
		{
			return string.Join(", ", parameters.Select(p =>
			{
				string prefix = p.IsOut ? "out " : p.ParameterType.IsByRef ? "ref " : p.GetCustomAttributes(typeof(ParamArrayAttribute), false).Length > 0 ? "params " : "";
				string suffix = p.HasDefaultValue ? " = " + (p.DefaultValue == null ? "null" : p.DefaultValue is string s ? "\"" + s + "\"" : p.DefaultValue is bool b ? (b ? "true" : "false") : p.DefaultValue.ToString()) : "";
				return prefix + Display(p.ParameterType) + " " + p.Name + suffix;
			}));
		}

		/// <summary>The type's name as the XML documentation spells it (nested types with '.', generics with `N).</summary>
		private static string DocName(Type type)
		{
			if (type.IsGenericType && !type.IsGenericTypeDefinition) type = type.GetGenericTypeDefinition();
			return type.FullName.Replace('+', '.');
		}

		/// <summary>A method's parameter list as the XML documentation spells it.</summary>
		private static string ParameterIds(ParameterInfo[] parameters)
		{
			if (parameters.Length == 0) return "";
			return "(" + string.Join(",", parameters.Select(p => ParameterId(p.ParameterType))) + ")";
		}

		private static string ParameterId(Type type)
		{
			if (type.IsByRef) return ParameterId(type.GetElementType()) + "@";
			if (type.IsArray) return ParameterId(type.GetElementType()) + "[]";
			if (type.IsGenericParameter) return (type.DeclaringMethod != null ? "``" : "`") + type.GenericParameterPosition;
			if (type.IsGenericType)
			{
				string name = type.GetGenericTypeDefinition().FullName;
				int tick = name.IndexOf('`');
				if (tick >= 0) name = name.Substring(0, tick);
				return name.Replace('+', '.') + "{" + string.Join(",", type.GetGenericArguments().Select(ParameterId)) + "}";
			}
			return type.FullName.Replace('+', '.');
		}

		private static string Anchor(string title)
		{
			StringBuilder anchor = new StringBuilder();
			foreach (char c in title.ToLowerInvariant())
			{
				if (char.IsLetterOrDigit(c)) anchor.Append(c);
				else if (c == ' ' || c == '-') anchor.Append('-');
			}
			return anchor.ToString();
		}

		// ---- the XML ----

		private static Dictionary<string, XElement> LoadDocs(string path)
		{
			Dictionary<string, XElement> docs = new Dictionary<string, XElement>(StringComparer.Ordinal);
			if (!File.Exists(path)) return docs;
			XDocument document = XDocument.Load(path);
			foreach (XElement member in document.Descendants("member"))
			{
				string name = member.Attribute("name")?.Value;
				if (!string.IsNullOrEmpty(name)) docs[name] = member;
			}
			return docs;
		}

		private static string Summary(Dictionary<string, XElement> docs, string id)
		{
			return docs.TryGetValue(id, out XElement member) ? Text(member.Element("summary")) : "";
		}

		/// <summary>A doc comment's text on one line: `see` and `paramref` as code, whitespace folded.</summary>
		private static string Text(XElement element)
		{
			if (element == null) return "";
			StringBuilder text = new StringBuilder();
			foreach (XNode node in element.Nodes())
			{
				if (node is XText t)
				{
					text.Append(t.Value);
				}
				else if (node is XElement e)
				{
					switch (e.Name.LocalName)
					{
						case "see":
						case "seealso":
						{
							string cref = e.Attribute("cref")?.Value ?? e.Attribute("langword")?.Value ?? e.Value;
							int colon = cref.IndexOf(':');
							if (colon == 1) cref = cref.Substring(2);
							int dot = cref.LastIndexOf('.');
							int paren = cref.IndexOf('(');
							if (paren >= 0) cref = cref.Substring(0, paren);
							if (dot >= 0 && dot < cref.Length - 1) cref = cref.Substring(dot + 1);
							text.Append('`').Append(cref).Append('`');
							break;
						}
						case "paramref":
						case "typeparamref":
							text.Append('`').Append(e.Attribute("name")?.Value).Append('`');
							break;
						case "c":
							text.Append('`').Append(e.Value).Append('`');
							break;
						case "para":
							text.Append(' ').Append(Text(e)).Append(' ');
							break;
						default:
							text.Append(Text(e));
							break;
					}
				}
			}
			return string.Join(" ", text.ToString().Split(new[] { ' ', '\t', '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries));
		}
	}
}
