// Generated by Tools/gen_cast_args.py - do not edit.
//
// Which arguments of which script commands name a cast. Read out of the
// game: a command resolves a cast by handing one of its arguments to
// changeHichNumber, so the position is whichever read produced it.
//
// 73 commands take a cast. 6 of them take a second one as well, which is
// the part a hand written list would have got wrong.

using System.Collections.Generic;

namespace Crystal
{
	internal static class CastArgs
	{
		/// <summary>Command name to the argument positions that are cast numbers.</summary>
		public static readonly IReadOnlyDictionary<string, int[]> Positions =
			new Dictionary<string, int[]>
			{
				{ "bindMotion", new[] { 0 } },
				{ "bootCharacter", new[] { 0 } },
				{ "bootCharacterAsTopPlayer", new[] { 0 } },
				{ "bootCharacter_AbsoluteCoordination", new[] { 0 } },
				{ "bootCharacter_RelativeCoordination", new[] { 0, 1 } },
				{ "bootPlainCharacter", new[] { 0 } },
				{ "changeColorCharacter", new[] { 0 } },
				{ "changeFaceEye", new[] { 0 } },
				{ "changeFaceMouth", new[] { 0 } },
				{ "cleanUpCharacter_FaceData", new[] { 0 } },
				{ "createBindObject", new[] { 0 } },
				{ "deleteBindObject", new[] { 0 } },
				{ "deleteCharacter", new[] { 0 } },
				{ "displayCharacter", new[] { 0 } },
				{ "endBalloon", new[] { 0 } },
				{ "endMotionCharacter", new[] { 0 } },
				{ "endMotionCharacterDX", new[] { 0 } },
				{ "endRotateMove", new[] { 0 } },
				{ "endWaveGravity", new[] { 0 } },
				{ "gravityCharacter", new[] { 0 } },
				{ "moveCamera_LookPlayer", new[] { 0 } },
				{ "moveCamera_LookPlayer2", new[] { 0 } },
				{ "moveCharacter_AbsoluteCoordination", new[] { 0 } },
				{ "moveCharacter_EndAutoIdle", new[] { 0 } },
				{ "moveCharacter_EndRandom", new[] { 0 } },
				{ "moveCharacter_RelativeCoordination", new[] { 0, 1 } },
				{ "moveCharacter_StartRandom", new[] { 0 } },
				{ "removeMotion", new[] { 0 } },
				{ "setCharacterCollisionRadius_Box", new[] { 0 } },
				{ "setCharacterCollisionRadius_Sphere", new[] { 0 } },
				{ "setCharacterDetectionRadius", new[] { 0 } },
				{ "setCharacterTouchRadius_Sphere", new[] { 0 } },
				{ "setCharacter_Alpha", new[] { 0 } },
				{ "setCharacter_CharaCollision", new[] { 0 } },
				{ "setCharacter_CheckTurnType", new[] { 0 } },
				{ "setCharacter_Collision", new[] { 0 } },
				{ "setCharacter_FixedTurn", new[] { 0 } },
				{ "setCharacter_GroundCollision", new[] { 0 } },
				{ "setCharacter_ItemEvent", new[] { 0 } },
				{ "setCharacter_MapJump", new[] { 0 } },
				{ "setCharacter_MotionSpeed", new[] { 0 } },
				{ "setCharacter_Scale", new[] { 0 } },
				{ "setCharacter_ShadowAlpha", new[] { 0 } },
				{ "setCharacter_TalkMotion", new[] { 0 } },
				{ "setCharacter_TurnTargetCharacter", new[] { 0, 1 } },
				{ "setCharacter_WallCollision", new[] { 0 } },
				{ "setEnableViewVolumeClip", new[] { 0 } },
				{ "setNPCAiType", new[] { 0, 1 } },
				{ "setPosition", new[] { 0 } },
				{ "setSignEffect", new[] { 0 } },
				{ "setTreasureItem", new[] { 0 } },
				{ "setTreasureMoney", new[] { 0 } },
				{ "setUpCharacter_FaceData", new[] { 0 } },
				{ "setVisibleBindObject", new[] { 0 } },
				{ "startMotionCharacter", new[] { 0 } },
				{ "startMotionCharacterDX", new[] { 0 } },
				{ "startRotateMove", new[] { 0 } },
				{ "startRotateMoveSyncRotate", new[] { 0 } },
				{ "startWaveGravity", new[] { 0 } },
				{ "turnCharacter_AbsoluteAngle", new[] { 0 } },
				{ "turnCharacter_AbsoluteAngle2", new[] { 0 } },
				{ "turnCharacter_AbsoluteCoordination", new[] { 0 } },
				{ "turnCharacter_EndLoop", new[] { 0 } },
				{ "turnCharacter_LookCharacter", new[] { 0, 1 } },
				{ "turnCharacter_LookCharacter2", new[] { 0, 1 } },
				{ "turnCharacter_RelativeAngle", new[] { 0 } },
				{ "turnCharacter_RelativeAngle2", new[] { 0 } },
				{ "turnCharacter_StartLoop", new[] { 0 } },
				{ "turnCharacter_StartLoop2", new[] { 0 } },
				{ "withInCharacterJump", new[] { 0 } },
				{ "withInCharacterJump2", new[] { 0 } },
				{ "withOutCharacterJump", new[] { 0 } },
				{ "withOutCharacterJump2", new[] { 0 } },
			};
	}
}
