// Which picture each cell bank draws from.
//
// GENERATED by Tools/gen_cell_pairs.py from the game's own source. Do not edit.
//
// A cell bank says "copy this rectangle to that position" and never names the
// sheet it copies from - the game names it at the call site. These are those
// call sites, read out of 1116 C# files, following the arrays the menus
// index rather than only the names written at the call.
//
// 14 of the 43 pair with the sheet of the same name, which is also the fallback
// for a bank that is never loaded by name. The rest do not, and those are the
// ones worth having this table for: every menu background draws from a single
// shared sheet.

using System;
using System.Collections.Generic;

namespace Crystal
{
	internal static class CellPairs
	{
		/// <summary>Cell bank file name -> the sheet it copies from.</summary>
		public static readonly Dictionary<string, string> Sheet =
			new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
			{
				["about.NCER"] = "about.NCGR",
				["chocobo_bank.NSCR"] = "menu_bg_01.NCGR",
				["clear.NCER"] = "clear.NCGR",
				["icon_8dot.NCER"] = "icon_8dot.NCGR",
				["link.NSCR"] = "menu_bg_01.NCGR",
				["m000_window.NCER"] = "m000_window.NCBR",
				["m008_volume.NCER"] = "m008_volume.NCBR",
				["m008_volume_2.NCER"] = "m008_volume_2.NCBR",
				["m014_button.NCER"] = "m014_button.NCBR",
				["m015_bar.NCER"] = "m015_bar.NCBR",
				["menu_000_main.NSCR"] = "menu_bg_01.NCGR",
				["menu_001_item.NSCR"] = "menu_bg_01.NCGR",
				["menu_001_item_01.NSCR"] = "menu_bg_01.NCGR",
				["menu_002_magic.NSCR"] = "menu_bg_01.NCGR",
				["menu_002_magic_01.NSCR"] = "menu_bg_01.NCGR",
				["menu_002_magic_02.NSCR"] = "menu_bg_01.NCGR",
				["menu_003_soubi_01.NSCR"] = "menu_bg_01.NCGR",
				["menu_004_status.NSCR"] = "menu_bg_01.NCGR",
				["menu_006_job.NSCR"] = "menu_bg_01.NCGR",
				["menu_008_tyudan.NSCR"] = "menu_bg_01.NCGR",
				["menu_009_save.NSCR"] = "menu_bg_01.NCGR",
				["menu_010_config.NSCR"] = "menu_bg_01.NCGR",
				["menu_010_config_2.NSCR"] = "menu_bg_01.NCGR",
				["menu_011_save02.NSCR"] = "menu_bg_01.NCGR",
				["menu_012_plane.NSCR"] = "menu_bg_01.NCGR",
				["menu_013_plane.NSCR"] = "menu_bg_01.NCGR",
				["mog_maillist.NSCR"] = "menu_bg_01.NCGR",
				["mog_nomal.NSCR"] = "menu_bg_01.NCGR",
				["mog_okurisaki.NSCR"] = "menu_bg_01.NCGR",
				["monsterbook.NSCR"] = "menu_bg_01.NCGR",
				["monsterbook_2.NSCR"] = "menu_bg_01.NCGR",
				["name_i.NCER"] = "name_i.NCGR",
				["new_i.NCER"] = "new_i.NCGR",
				["ok.NCER"] = "ok.NCGR",
				["repair.NCER"] = "repair.NCGR",
				["shop_bg00.NSCR"] = "menu_bg_01.NCGR",
				["shop_bg01.NSCR"] = "menu_bg_01.NCGR",
				["tips_00.NSCR"] = "menu_bg_01.NCGR",
				["tips_01.NSCR"] = "menu_bg_01.NCGR",
				["title_gousei_new.NCER"] = "title_gousei_new.NCBR",
				["title_gousei_new_jp.NCER"] = "title_gousei_new.NCBR",
				["title_items_i.NCER"] = "title_items_i.NCGR",
				["yarikomi.NSCR"] = "menu_bg_01.NCGR",
			};
	}
}
