using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.IsolatedStorage;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.GamerServices;
using Microsoft.Xna.Framework.Graphics;
using android.content;
using android.text;
using android.widget;
using syrcusW.res.raw;
using syrcusW.res.values;

internal static partial class GlobalScope
{
	public static partial class chr
	{
		public const CHARACTER_KIND CHARACTER_KIND_ERR = CHARACTER_KIND.CHARACTER_KIND_ERR;

		public const CHARACTER_KIND CHARACTER_KIND_PLAYER_HUMAN = CHARACTER_KIND.CHARACTER_KIND_PLAYER_HUMAN;

		public const CHARACTER_KIND CHARACTER_KIND_PLAYER_VEHICLE = CHARACTER_KIND.CHARACTER_KIND_PLAYER_VEHICLE;

		public const CHARACTER_KIND CHARACTER_KIND_MAP_OBJECT = CHARACTER_KIND.CHARACTER_KIND_MAP_OBJECT;

		public const CHARACTER_KIND CHARACTER_KIND_MAX = CHARACTER_KIND.CHARACTER_KIND_MAX;

		public const CHARACTER_CHECK_TYPE CHARACTER_CHECK_TYPE_ERR = CHARACTER_CHECK_TYPE.CHARACTER_CHECK_TYPE_ERR;

		public const CHARACTER_CHECK_TYPE CHARACTER_CHECK_TYPE_TALK = CHARACTER_CHECK_TYPE.CHARACTER_CHECK_TYPE_TALK;

		public const CHARACTER_CHECK_TYPE CHARACTER_CHECK_TYPE_CHECK = CHARACTER_CHECK_TYPE.CHARACTER_CHECK_TYPE_CHECK;

		public const CHARACTER_CHECK_TYPE CHARACTER_CHECK_TYPE_MAX = CHARACTER_CHECK_TYPE.CHARACTER_CHECK_TYPE_MAX;

		public const CHARACTER_COLLISION_TYPE COL_TYPE_ERR = CHARACTER_COLLISION_TYPE.COL_TYPE_ERR;

		public const CHARACTER_COLLISION_TYPE COL_TYPE_NONE = CHARACTER_COLLISION_TYPE.COL_TYPE_NONE;

		public const CHARACTER_COLLISION_TYPE COL_TYPE_COLLISION = CHARACTER_COLLISION_TYPE.COL_TYPE_COLLISION;

		public const CHARACTER_COLLISION_TYPE COL_TYPE_CHECK = CHARACTER_COLLISION_TYPE.COL_TYPE_CHECK;

		public const CHARACTER_COLLISION_TYPE COL_TYPE_TOUCH = CHARACTER_COLLISION_TYPE.COL_TYPE_TOUCH;

		public const CHARACTER_COLLISION_TYPE COL_TYPE_MAX = CHARACTER_COLLISION_TYPE.COL_TYPE_MAX;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_NONE = CHARACTER_COLLISION_FLAG.COL_FLAG_NONE;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_TOUCH = CHARACTER_COLLISION_FLAG.COL_FLAG_TOUCH;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_CHARACTER = CHARACTER_COLLISION_FLAG.COL_FLAG_CHARACTER;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_GROUND = CHARACTER_COLLISION_FLAG.COL_FLAG_GROUND;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_WALL = CHARACTER_COLLISION_FLAG.COL_FLAG_WALL;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_WALL_01 = CHARACTER_COLLISION_FLAG.COL_FLAG_WALL_01;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_WALL_02 = CHARACTER_COLLISION_FLAG.COL_FLAG_WALL_02;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_WALL_03 = CHARACTER_COLLISION_FLAG.COL_FLAG_WALL_03;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_WALL_04 = CHARACTER_COLLISION_FLAG.COL_FLAG_WALL_04;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_WALL_05 = CHARACTER_COLLISION_FLAG.COL_FLAG_WALL_05;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_LANDFORM = CHARACTER_COLLISION_FLAG.COL_FLAG_LANDFORM;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MONSTER = CHARACTER_COLLISION_FLAG.COL_FLAG_MONSTER;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_01 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_01;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_02 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_02;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_03 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_03;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_04 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_04;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_05 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_05;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_06 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_06;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_07 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_07;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_08 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_08;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_09 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_09;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_10 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_10;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_11 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_11;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAPJUMP_12 = CHARACTER_COLLISION_FLAG.COL_FLAG_MAPJUMP_12;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_DAMAGE = CHARACTER_COLLISION_FLAG.COL_FLAG_DAMAGE;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_DAMAGE_01 = CHARACTER_COLLISION_FLAG.COL_FLAG_DAMAGE_01;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_DAMAGE_02 = CHARACTER_COLLISION_FLAG.COL_FLAG_DAMAGE_02;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_DAMAGE_03 = CHARACTER_COLLISION_FLAG.COL_FLAG_DAMAGE_03;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_DAMAGE_04 = CHARACTER_COLLISION_FLAG.COL_FLAG_DAMAGE_04;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_DAMAGE_05 = CHARACTER_COLLISION_FLAG.COL_FLAG_DAMAGE_05;

		public const CHARACTER_COLLISION_FLAG COL_FLAG_MAX = CHARACTER_COLLISION_FLAG.COL_FLAG_MAX;

		private static readonly int[] MAP_WALL_COLLISION_FLAG = new int[5] { 16, 32, 64, 128, 256 };

		private static readonly int[] CHARA_WALL_COLLISION_FLAG = new int[5] { 32, 64, 128, 256, 512 };

		private static readonly int[] WALL_ATTRIBUTE = new int[5]
		{
			static_cast<int>(mcl.MCL_ATTRIBUTE.ATTRIBUTE_WALL_01),
			static_cast<int>(mcl.MCL_ATTRIBUTE.ATTRIBUTE_WALL_02),
			static_cast<int>(mcl.MCL_ATTRIBUTE.ATTRIBUTE_WALL_03),
			static_cast<int>(mcl.MCL_ATTRIBUTE.ATTRIBUTE_WALL_04),
			static_cast<int>(mcl.MCL_ATTRIBUTE.ATTRIBUTE_WALL_05)
		};

		private static readonly mcl.MCL_ATTRIBUTE[] attr_jump = new mcl.MCL_ATTRIBUTE[12]
		{
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_01,
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_02,
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_03,
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_04,
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_05,
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_06,
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_07,
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_08,
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_09,
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_10,
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_11,
			mcl.MCL_ATTRIBUTE.ATTRIBUTE_MAPJUMP_12
		};

		private static readonly int[] MAP_JUMP_COLLISION_FLAG = new int[12]
		{
			4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576, 2097152,
			4194304, 8388608
		};

		private static readonly VecFx32 normDir = new VecFx32(0, -4096, 0);

		private static VecFx32 chr_reuse_dir_ = new VecFx32();

		private static VecFx32 chr_reuse_dir_2 = new VecFx32();

		private static VecFx32 chr_reuse_currentPos_ = new VecFx32();

		private static VecFx32 chr_reuse_currentPos_2 = new VecFx32();

		private static VecFx32 chr_reuse_oldPos_ = new VecFx32();

		private static MtxFx43 chr_reuse_invMtx = new MtxFx43();

		private static MtxFx43 chr_reuse_mtx = new MtxFx43();

		private static mcl.CollisionResult chr_reuse_result = new mcl.CollisionResult();

		private static mcl.CollisionResult chr_reuse_result2 = new mcl.CollisionResult();

		private static mcl.CollisionResult chr_reuse_result3 = new mcl.CollisionResult();

		private static VecFx32 chr_reuse_edgePos = new VecFx32();

		private static VecFx32 chr_reuse_toVert = new VecFx32();

		private static VecFx32 chr_reuse_v0 = new VecFx32();

		private static VecFx32 chr_reuse_v1 = new VecFx32();

		private static VecFx32 chr_reuse_v2 = new VecFx32();

		public static int PI = 32768;

		private static int GRAVITY_ACC = FX_F32_TO_FX32(0.98f);

		private static int GRAVITY_ACC_MAX = FX_F32_TO_FX32(2f);

		private static uint CHARACTER_EUREKA_NUM = 16u;

		private static uint CHARACTER_NUM = CHARACTER_EUREKA_NUM;

		internal static int fitRadian(int rad)
		{
			while (rad < -PI)
			{
				rad += PI * 2;
			}
			while (PI < rad)
			{
				rad -= PI * 2;
			}
			return rad;
		}

	}
}
