"""Generates MenuBackgrounds.cs: which cell bank is drawn behind each menu screen.

Nothing in a .xbn says what its screen looks like. The game decides, in three steps that
are each in a different place, so this follows them rather than matching names by eye:

    buildMenu("equip")                       is called inside class CWMenuEquip
    this.m_pCurrent[2] = this.m_MenuEquip    fixes CWMenuEquip as WMENU_KIND index 2
    main_bg_nscr[2] = "menu_003_soubi_01"    is the background for that index

Which gives equip -> menu_003_soubi_01.NSCR. Doing it by eye would get most of them and
quietly invent the rest: "equip" and "soubi" are the same word in two languages, and
half_save maps to tyudan.

    python Tools/gen_menu_backgrounds.py > FF3.ContentTool/Editor/MenuBackgrounds.cs
"""
import io
import re
import sys

SOURCE = r'C:\Users\KarlJ\Downloads\FF3\Decompiled\syrcusW\GlobalScope.cs'

BUILD = re.compile(r'buildMenu\("([^"]+)"\)')
SLOT = re.compile(r'this\.m_pCurrent\[(\d+)\]\s*=\s*\([^)]*\)\s*this\.(\w+)\s*;')
FIELD = re.compile(r'private\s+GlobalScope\.wmenu\.(\w+)\s+(m_Menu\w+)\s*=')
ARRAY = re.compile(r'(main_bg_nscr|sub_bg_nscr)\s*=\s*new string\[\d+\]\s*\{([^}]*)\}')


def main():
    src = io.open(SOURCE, encoding='utf-8', errors='replace').read()

    classes = [(m.start(), m.group(1)) for m in re.finditer(r'\bclass\s+(\w+)', src)]

    def enclosing(pos):
        found = None
        for at, name in classes:
            if at < pos:
                found = name
            else:
                break
        return found

    # Which class builds which .xbn screen.
    screenOf = {}
    for m in BUILD.finditer(src):
        screenOf.setdefault(enclosing(m.start()), []).append(m.group(1))

    # Field name to class, then slot index to class.
    fieldClass = {m.group(2): m.group(1) for m in FIELD.finditer(src)}
    slotClass = {}
    for m in SLOT.finditer(src):
        cls = fieldClass.get(m.group(2))
        if cls:
            slotClass[int(m.group(1))] = cls

    arrays = {m.group(1): [s.strip().strip('"') for s in m.group(2).split(',') if s.strip()]
              for m in ARRAY.finditer(src)}
    main_bg = arrays.get('main_bg_nscr', [])

    # Only where a class builds exactly one screen. CWMenuConfig builds both "config"
    # and "tips_list", and they do not share a background - tips_list is kind 13, which
    # this chain cannot see. Emitting the class's background for both would put the
    # config panel behind the tips list and look like it had worked.
    pairs = []
    skipped = []
    for index, cls in sorted(slotClass.items()):
        if index >= len(main_bg):
            continue
        nscr = main_bg[index]
        if not nscr or nscr == 'null':
            continue
        screens = sorted(set(screenOf.get(cls, [])))
        if len(screens) == 1:
            pairs.append((screens[0], nscr, cls, index))
        elif screens:
            skipped.append((cls, index, nscr, screens))

    out = sys.stdout
    out.write('// Generated by Tools/gen_menu_backgrounds.py - do not edit.\n')
    out.write('//\n')
    out.write('// What is drawn behind each menu screen. Followed through the game rather\n')
    out.write('// than matched by name: buildMenu("<screen>") says which class owns a\n')
    out.write('// screen, m_pCurrent[i] = m_MenuX fixes that class as WMENU_KIND i, and\n')
    out.write('// main_bg_nscr[i] is the cell bank for it.\n')
    out.write('//\n')
    out.write('// The bank is drawn from a shared sheet - bgLoad names menu_bg_01.NCGR for\n')
    out.write('// all of them - which is why these never appeared: the cell reader looks\n')
    out.write('// for a sheet of the same name and there is none.\n\n')
    out.write('using System;\nusing System.Collections.Generic;\n\n')
    out.write('namespace FF3.ContentTool.Editor\n{\n')
    out.write('\tinternal static class MenuBackgrounds\n\t{\n')
    out.write('\t\t/// <summary>Screen name in a .xbn to the cell bank drawn behind it.</summary>\n')
    out.write('\t\tpublic static readonly IReadOnlyDictionary<string, string> ForScreen =\n')
    out.write('\t\t\tnew Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)\n\t\t\t{\n')
    for screen, nscr, cls, index in sorted(pairs):
        out.write('\t\t\t\t{ "%s", "files/%s" },   // %s, kind %d\n'
                  % (screen, nscr, cls, index))
    out.write('\t\t\t};\n')
    if skipped:
        out.write('\n\t\t// Left out on purpose. These classes build more than one screen,\n')
        out.write('\t\t// and which background belongs to which is not in this chain - the\n')
        out.write('\t\t// class only pins down one WMENU_KIND:\n')
        for cls, index, nscr, screens in skipped:
            out.write('\t\t//   %s (kind %d, %s) builds %s\n'
                      % (cls, index, nscr, ', '.join(screens)))
    out.write('\t}\n}\n')


if __name__ == '__main__':
    main()
