"""Generates CastArgs.cs: which arguments of which script commands are cast numbers.

A cast number is how a script names a placed character, and 73 commands take one. Most
take it as their first argument, but six take a second one as well - turnCharacter_
LookCharacter names both the character turning and the one it turns towards - so a
search for "what mentions cast 21" that only looked at the first argument would quietly
miss them.

Rather than write that list by hand, this reads the game. A command's body reads its
arguments in order with getWord/getByte/getDword, and resolves a cast by handing one of
them to changeHichNumber or getManCastIndex; so the argument position is found by seeing
which read produced the variable that gets passed.

    python Tools/gen_cast_args.py > Crystal.Editor/CastArgs.cs
"""
import io
import re
import sys

# The decompiled game as one file (the raw ILSpy output, kept outside the repository); or pass a path.
SOURCE = sys.argv[1] if len(sys.argv) > 1 else r'..\Decompiled\syrcusW\GlobalScope.cs'

READ = re.compile(r'(\w+)\s*=\s*(?:\(\w+\)\s*)?engine\.get(Word|Byte|Dword)\(\)')
RESOLVE = re.compile(
    r'(?:changeHichNumber|getManCastIndex)\(\s*(?:\(\w+\)\s*)?(\w+)\s*\)')
COMMAND = re.compile(
    r'internal static void (ff3Command_\w+)\(GlobalScope\.ScriptEngine engine\)\s*\{')


def bodies(src):
    for m in COMMAND.finditer(src):
        start = m.end()
        depth, i = 1, start
        while depth and i < len(src):
            if src[i] == '{':
                depth += 1
            elif src[i] == '}':
                depth -= 1
            i += 1
        yield m.group(1), src[start:i]


def main():
    src = io.open(SOURCE, encoding='utf-8', errors='replace').read()
    found = {}
    for name, body in bodies(src):
        if 'changeHichNumber' not in body and 'getManCastIndex' not in body:
            continue
        order = {n: i for i, (n, _) in enumerate(READ.findall(body))}
        at = sorted({order[v] for v in RESOLVE.findall(body) if v in order})
        if not at:
            raise SystemExit('could not tell which argument of %s is a cast' % name)
        mnemonic = name.replace('ff3Command_', '')
        found[mnemonic[0].lower() + mnemonic[1:]] = at

    out = sys.stdout
    out.write('// Generated by Tools/gen_cast_args.py - do not edit.\n')
    out.write('//\n')
    out.write('// Which arguments of which script commands name a cast. Read out of the\n')
    out.write('// game: a command resolves a cast by handing one of its arguments to\n')
    out.write('// changeHichNumber, so the position is whichever read produced it.\n')
    out.write('//\n')
    out.write('// %d commands take a cast. %d of them take a second one as well, which is\n'
              % (len(found), sum(1 for v in found.values() if len(v) > 1)))
    out.write('// the part a hand written list would have got wrong.\n\n')
    out.write('using System.Collections.Generic;\n\n')
    out.write('namespace Crystal.Editor\n{\n')
    out.write('\tinternal static class CastArgs\n\t{\n')
    out.write('\t\t/// <summary>Command name to the argument positions that are cast numbers.</summary>\n')
    out.write('\t\tpublic static readonly IReadOnlyDictionary<string, int[]> Positions =\n')
    out.write('\t\t\tnew Dictionary<string, int[]>\n\t\t\t{\n')
    for name in sorted(found):
        out.write('\t\t\t\t{ "%s", new[] { %s } },\n'
                  % (name, ', '.join(str(i) for i in found[name])))
    out.write('\t\t\t};\n\t}\n}\n')


if __name__ == '__main__':
    main()
