"""Writes OpenFF/Data/hud/ff4_menu.xml: FF4's field menu as Steam draws it - the root, the member panel and the question
here, the full screens (Inventory, Magic, Status, Equipment, Abilities, Gambits, Party, Settings) in gen_ff4_menu_screens.py.
Every place and size is Steam's 1080p pixels, measured off its draws (Tools/ff4hook: `draws <name>`). Run it after changing
either file:  python Tools/gen_ff4_menu.py   (the stylesheet, OpenFF/Data/hud/styles/ff4_menu.css, is written by hand)."""
import os

def f(n):
    return ('%.2f' % n).rstrip('0').rstrip('.')

def frame(id_, x, y, w, h, cls=None, attrs='', inner='', style=None):
    a = ''
    if cls: a += ' class="%s"' % cls
    if attrs: a += ' ' + attrs
    if style: a += ' style="%s"' % style
    body = '<id>%s</id><x>%s</x><y>%s</y><width>%s</width><height>%s</height>' % (id_, f(x), f(y), f(w), f(h))
    if inner:
        return '<frame%s>\n%s\n%s\n</frame>' % (a, body, inner)
    return '<frame%s>%s</frame>' % (a, body)

def indent(s, n):
    return '\n'.join(('  ' * n + l) if l else l for l in s.split('\n'))

out = []
out.append('''<?xml version="1.0" encoding="utf-8"?>
<!--
  FF4's field menu (OpenFF.Client.Ff4Menu draws it through LayoutScreen), written in Steam's 1080p pixels - the places,
  sizes and colours read off the Steam game's own draws (Tools/ff4hook's draws, the menu opened from a quicksave);
  generated by Tools/gen_ff4_menu.py - change that and run it rather than this file. Its
  look is in styles/ff4_menu.css. A mod reshapes it with menus/hud/ff4_menu.xml (a copy of this, changed), or restyles
  it with menus/hud/styles/*.css.

  Everything binds to the root "menu" (Ff4MenuHud.Data):
    menu.root               the main menu is up (the command column, the place and the gil, the key hints)
    menu.command[0..5]      the six rows in view: present, name, lit (the hand on it), disabled (greyed: Save away from a
                            save point)
    menu.scroll             shown, top and size (percent of the track)
    menu.location, gil, gilLabel   the place's name; the gil and its word
    menu.bubble, thought    the lead's thought over the field (babil_speculation.bbd's line for where the story stands)
    menu.picking            the member panel is up: a command wants a member
    menu.member[0..4]       the party's five places: present, name, level, hp, maxHp, mp, maxMp, face (face.NCER's
                            cell), lit (the hand on it), dim (greyed: the command is nothing to them), low (HP a quarter
                            or less)
    menu.confirm, back      the key hints' words
    menu.question, questionText, yes, no   a Yes / No window (Quicksave's "Quicksave game and quit?"); yes: the hand on Yes
    menu.full, title        a full screen is up (the wallpaper, the title bar, the footer) and its title
    menu.help               the help line: the lit item's caption, the lit spell's cost and line
    menu.inventory          Inventory: menu.item[0..13] the cells in view (present, name, count, icon: the symbol's cell,
                            lit, dim: not usable here), menu.itemScroll (shown, knob, knobTop, knobHeight)
    menu.using, useName, useCount, useIcon, target[0..4]   an item being used: it, and the party's places to use it on
    menu.magic              Magic: menu.head (the member: name, level, hp, maxHp, mp, maxMp, face), menu.spell[0..14],
                            menu.spellScroll, menu.schoolLabel (C's school), menu.changeLabel
    menu.keyItemsLabel, sortLabel, useLabel   the other key hints' words
-->
<menu style="width: 1920px; height: 1080px">
  <name>ff4_menu</name>
''')

# The lead's thought: balloon.NCBR's cloud at its own size (1.6875 a picture pixel) and three puffs toward the lead.
bubble = [
    frame('cloud', 162.3, 54, 946.4, 269.1, 'm-cloud'),
    frame('thought', 202.8, 111.4, 860, 60.75, 'm-thought', 'bind-text="{menu.thought}"'),
    frame('puff0', 926.2, 337.5, 67.6, 32.9, 'm-puff0'),
    frame('puff1', 905.9, 391.5, 54.1, 32.9, 'm-puff1'),
    frame('puff2', 892.4, 445.5, 33.8, 32.9, 'm-puff2'),
]
out.append(indent('<!-- The lead\'s thought over the field (MSSRoot\'s balloon). -->', 1))
out.append(indent('<frame bind-display="menu.bubble">\n<id>bubble</id><x>0</x><y>0</y><width>1920</width><height>1080</height>\n' + '\n'.join(bubble) + '\n</frame>', 1))

# The command column: the window (raised frame round two bands), six rows 135 high, the scroll bar beside them.
rows = []
for i in range(6):
    inner = '\n'.join([
        frame('band', 0, 0, 567.9, 135, 'lit-band', 'bind-visible="lit"'),
        frame('edge', 0, 0, 567.9, 135, 'm-edge'),
        frame('name', 0, 0, 567.9, 135, 'm-label', 'bind-text="{name}"'),
        frame('hand', 87.8, 0, 1, 135, 'hand', 'bind-visible="lit"'),
    ])
    rows.append(frame('command%d' % i, 0, i * 135, 567.9, 135, 'm-command',
                      'data-source="menu.command[%d]" bind-display="present" bind-class="lit: lit; disabled: disabled"' % i, indent(inner, 1)))
scroll = '\n'.join([
    frame('up', 0, 0, 60.75, 32.9, 'm-scroll-up'),
    frame('track', 0, 33.75, 60.75, 742.5, 'm-scroll-track'),
    frame('down', 0, 776.25, 60.75, 33.75, 'm-scroll-down'),
    frame('knob', 3.4, 33.75, 54, 742.5, 'm-scroll-knob', 'bind-style="top: {menu.scroll.knobTop}px; height: {menu.scroll.knobHeight}px"'),
])
column = '\n'.join([
    frame('frame', -6.75, -6.75, 649, 823.5, 'm-window'),
    '\n'.join(rows),
    frame('scroll', 571.3, 0, 60.75, 810, None, 'bind-display="menu.scroll.shown"', indent(scroll, 1)),
])
out.append(indent('<!-- The commands: rows 567.9 x 135 under the window\'s bands, the hand on the lit one; the scroll bar beside them. -->', 1))
out.append(indent(frame('commands', 1129, 6.75, 635.5, 810, None, 'bind-display="menu.root"', indent(column, 1)), 1))

# The place and the gil.
place = '\n'.join([
    frame('frame', -6.75, -6.75, 649, 135, 'm-window'),
    frame('location', 60.9, -3.4, 560, 60.75, 'm-text', 'bind-text="{menu.location}"'),
    frame('gil', 0, 64.1, 567.9, 60.75, 'm-text m-right', 'bind-text="{menu.gil}{menu.gilLabel}"'),
])
out.append(indent('<!-- The place and the gil. -->', 1))
out.append(indent(frame('place', 1129, 830.25, 635.5, 121.5, None, 'bind-display="menu.root"', indent(place, 1)), 1))

# The member panel: the party's five places, 189 high.
mrows = []
for i in range(5):
    inner = '\n'.join([
        frame('band', 0, 0, 960, 189, 'lit-band m-member-band', 'bind-visible="lit"'),
        frame('edge', 0, 0, 960, 189, 'm-edge'),
        frame('face', 13.5, 27, 135, 135, 'm-face', 'bind-display="present" bind-style="-ff-cell: face {face}"'),
        frame('name', 189.3, 20.25, 400, 60.75, 'm-text', 'bind-text="{name}"'),
        frame('lv', 189.3, 74.25, 120, 60.75, 'm-text', 'bind-display="present" bind-text="{menu.lvLabel}"'),
        frame('level', 324.5, 74.25, 120, 60.75, 'm-text', 'bind-text="{level}"'),
        frame('hpLabel', 540.8, 20.25, 120, 60.75, 'm-text', 'bind-display="present" bind-text="{menu.hpLabel}"'),
        frame('hp', 600, 20.25, 166, 60.75, 'm-text m-right m-hp', 'bind-text="{hp}"'),
        frame('hpSlash', 774.1, 20.25, 30, 60.75, 'm-text', 'bind-display="present" bind-text="/"'),
        frame('maxHp', 797.7, 20.25, 140, 60.75, 'm-text', 'bind-text="{maxHp}"'),
        frame('mpLabel', 540.8, 74.25, 120, 60.75, 'm-text', 'bind-display="present" bind-text="{menu.mpLabel}"'),
        frame('mp', 600, 74.25, 166, 60.75, 'm-text m-right', 'bind-text="{mp}"'),
        frame('mpSlash', 774.1, 74.25, 30, 60.75, 'm-text', 'bind-display="present" bind-text="/"'),
        frame('maxMp', 797.7, 74.25, 140, 60.75, 'm-text', 'bind-text="{maxMp}"'),
        frame('hand', 81, 0, 1, 189, 'hand m-member-hand', 'bind-visible="lit"'),
    ])
    mrows.append(frame('member%d' % i, 0, i * 189, 960, 189, 'm-member',
                       'data-source="menu.member[%d]" bind-class="lit: lit; dim: dim; low: low; back: back; picked: picked"' % i, indent(inner, 1)))
panel = '\n'.join([frame('frame', -6.75, -6.75, 973.5, 958.5, 'm-window'), '\n'.join(mrows)])
out.append(indent('<!-- The member panel: the party\'s five places (a command wants a member). -->', 1))
out.append(indent(frame('members', 155.5, 6.75, 960, 945, None, 'bind-display="menu.picking"', indent(panel, 1)), 1))

# The key hints, bottom right.
keys = '\n'.join([
    frame('confirmKey', 0, 0, 60.75, 60.75, 'key-cap', '', '', '-ff-cell: key 43'),
    frame('confirm', 60.8, 0, 200, 60.75, 'm-key-label', 'bind-text="{menu.confirm}"'),
    frame('backKey', 219.7, 0, 60.75, 60.75, 'key-cap', '', '', '-ff-cell: key 15'),
    frame('back', 280.5, 0, 200, 60.75, 'm-key-label', 'bind-text="{menu.back}"'),
])
out.append(indent('<!-- The key hints: Enter Confirm, Backspace Back. -->', 1))
out.append(indent(frame('keys', 1497.5, 995.6, 480, 60.75, None, 'bind-display="menu.root"', indent(keys, 1)), 1))

# The Yes / No question (Quicksave's): the screen dimmed, a window, the question, two pills (button_00), the hand on one.
def pill(id_, x):
    inner = '\n'.join([
        frame('art', 0, 0, 405.5, 121.5, 'm-pill-art'),
        frame('label', 0, 30.4, 405.5, 60.75, 'm-text m-centre', 'bind-text="{menu.%sLabel}"' % id_),
        frame('hand', 81, 0, 1, 121.5, 'hand m-pill-hand', 'bind-visible="menu.%s"' % id_),
    ])
    return frame(id_, x, 594, 405.5, 121.5, 'm-pill', '', indent(inner, 1))
q = '\n'.join([
    frame('dim', 0, 0, 1920, 1080, 'm-dim'),
    frame('window', 358.3, 276.8, 1203.4, 526.4, 'm-question-window'),
    frame('text', 358.3, 401.6, 1203.4, 60.75, 'm-text m-centre', 'bind-text="{menu.questionText}"'),
    pill('yes', 486.8),
    pill('no', 1027.6),
])
question_frame = frame('question', 0, 0, 1920, 1080, None, 'bind-display="menu.question"', indent(q, 1))

# The full screens (Inventory, Magic, ...): gen_menu_screens.py, with this file's helpers.
_scope = {'frame': frame, 'indent': indent, 'f': f, 'member_panel': panel, 'pill': pill}
exec(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'gen_ff4_menu_screens.py'), encoding='utf-8').read(), _scope)
out.append(indent("<!-- The full screens: the wallpaper, a title bar and a footer of key hints round each screen's windows. -->", 1))
for sc in _scope['screens']: out.append(indent(sc, 1))
# The question over everything (Quicksave's, Settings' Quit).
out.append(indent('<!-- A Yes / No question over the menu (Quicksave: "Quicksave game and quit?"; Settings: Quit). -->', 1))
out.append(indent(question_frame, 1))

# Everything inside one frame that carries the window design the settings chose (design-1 .. design-6): a sheet's
# .design-N rules put MENU_Common's set N - 1 on the windows, scroll bars, buttons and wallpaper.
head, body = out[0], out[1:]
classes = '; '.join('design-%d: menu.design == %d' % (n, n) for n in range(1, 7))
out = [head, '  <frame bind-class="%s">' % classes, '    <id>design</id><x>0</x><y>0</y><width>1920</width><height>1080</height>']
out += [indent(b, 1) for b in body]
out.append('  </frame>')
out.append('</menu>\n')
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'OpenFF', 'Data', 'hud', 'ff4_menu.xml')
open(path, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
print('written', path)
