using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.IsolatedStorage;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.GamerServices;
using Microsoft.Xna.Framework.Graphics;
using android.content;
using syrcusW.res.raw;
using syrcusW.res.values;

internal static partial class GlobalScope
{
	public static partial class btl
	{
		public const SUMMON_BEHAVIOR SET_DARK_SCREEN = SUMMON_BEHAVIOR.SET_DARK_SCREEN;

		public const SUMMON_BEHAVIOR IS_DARK_SCREEN = SUMMON_BEHAVIOR.IS_DARK_SCREEN;

		public const SUMMON_BEHAVIOR SET_NORMAL_SCREEN = SUMMON_BEHAVIOR.SET_NORMAL_SCREEN;

		public const SUMMON_BEHAVIOR IS_NORMAL_SCREEN = SUMMON_BEHAVIOR.IS_NORMAL_SCREEN;

		public const SUMMON_BEHAVIOR SET_FADE_OUT = SUMMON_BEHAVIOR.SET_FADE_OUT;

		public const SUMMON_BEHAVIOR IS_FADE_OUT = SUMMON_BEHAVIOR.IS_FADE_OUT;

		public const SUMMON_BEHAVIOR SET_FADE_IN = SUMMON_BEHAVIOR.SET_FADE_IN;

		public const SUMMON_BEHAVIOR IS_FADE_IN = SUMMON_BEHAVIOR.IS_FADE_IN;

		public const SUMMON_BEHAVIOR SET_MODEL = SUMMON_BEHAVIOR.SET_MODEL;

		public const SUMMON_BEHAVIOR IS_MODEL = SUMMON_BEHAVIOR.IS_MODEL;

		public const SUMMON_BEHAVIOR SET_MOTION = SUMMON_BEHAVIOR.SET_MOTION;

		public const SUMMON_BEHAVIOR IS_MOTION = SUMMON_BEHAVIOR.IS_MOTION;

		public const SUMMON_BEHAVIOR START_MOTION = SUMMON_BEHAVIOR.START_MOTION;

		public const SUMMON_BEHAVIOR IS_MOTION_FRAME = SUMMON_BEHAVIOR.IS_MOTION_FRAME;

		public const SUMMON_BEHAVIOR DEL_SUMMON = SUMMON_BEHAVIOR.DEL_SUMMON;

		public const SUMMON_BEHAVIOR REGISTER_PLAYERS = SUMMON_BEHAVIOR.REGISTER_PLAYERS;

		public const SUMMON_BEHAVIOR SET_EFFECT = SUMMON_BEHAVIOR.SET_EFFECT;

		public const SUMMON_BEHAVIOR CLEAR_EFFECT = SUMMON_BEHAVIOR.CLEAR_EFFECT;

		public const SUMMON_BEHAVIOR IS_EFFECT = SUMMON_BEHAVIOR.IS_EFFECT;

		public const SUMMON_BEHAVIOR DRAW_SUMMON_EFFECT = SUMMON_BEHAVIOR.DRAW_SUMMON_EFFECT;

		public const SUMMON_BEHAVIOR DRAW_SUMMON_EFFECT_TARGET_ALL = SUMMON_BEHAVIOR.DRAW_SUMMON_EFFECT_TARGET_ALL;

		public const SUMMON_BEHAVIOR IS_END_SUMMON_EFFECT = SUMMON_BEHAVIOR.IS_END_SUMMON_EFFECT;

		public const SUMMON_BEHAVIOR CHANGE_CAMERA = SUMMON_BEHAVIOR.CHANGE_CAMERA;

		public const SUMMON_BEHAVIOR SET_CAMERA_POSITION = SUMMON_BEHAVIOR.SET_CAMERA_POSITION;

		public const SUMMON_BEHAVIOR SET_CAMERA_TARGET = SUMMON_BEHAVIOR.SET_CAMERA_TARGET;

		public const SUMMON_BEHAVIOR SET_MOVE_CAMERA_FRAME = SUMMON_BEHAVIOR.SET_MOVE_CAMERA_FRAME;

		public const SUMMON_BEHAVIOR MOVING_CAMERA = SUMMON_BEHAVIOR.MOVING_CAMERA;

		public const SUMMON_BEHAVIOR SET_BATTLE_CAMERA = SUMMON_BEHAVIOR.SET_BATTLE_CAMERA;

		public const SUMMON_BEHAVIOR SET_SUMMON_PARAMETER = SUMMON_BEHAVIOR.SET_SUMMON_PARAMETER;

		public const SUMMON_BEHAVIOR SET_POSITION_AND_ROTATION = SUMMON_BEHAVIOR.SET_POSITION_AND_ROTATION;

		public const SUMMON_BEHAVIOR SHOW_MONSTERS = SUMMON_BEHAVIOR.SHOW_MONSTERS;

		public const SUMMON_BEHAVIOR HIDE_MONSTERS = SUMMON_BEHAVIOR.HIDE_MONSTERS;

		public const SUMMON_BEHAVIOR SHOW_SUMMON = SUMMON_BEHAVIOR.SHOW_SUMMON;

		public const SUMMON_BEHAVIOR HIDE_SUMMON = SUMMON_BEHAVIOR.HIDE_SUMMON;

		public const SUMMON_BEHAVIOR SUMMON_ALPHA_RATE = SUMMON_BEHAVIOR.SUMMON_ALPHA_RATE;

		public const SUMMON_BEHAVIOR SET_PLAYERS_ALPHA = SUMMON_BEHAVIOR.SET_PLAYERS_ALPHA;

		public const SUMMON_BEHAVIOR APPEAR_PLAYERS = SUMMON_BEHAVIOR.APPEAR_PLAYERS;

		public const SUMMON_BEHAVIOR SET_TURN_FLAG = SUMMON_BEHAVIOR.SET_TURN_FLAG;

		public const SUMMON_BEHAVIOR IS_TURN_FLAG = SUMMON_BEHAVIOR.IS_TURN_FLAG;

		public const SUMMON_BEHAVIOR MOVE_CAMERA_AND_SUMMON_ALPHA = SUMMON_BEHAVIOR.MOVE_CAMERA_AND_SUMMON_ALPHA;

		public const SUMMON_BEHAVIOR FRAME_COUNT = SUMMON_BEHAVIOR.FRAME_COUNT;

		public const SUMMON_BEHAVIOR SET_2D = SUMMON_BEHAVIOR.SET_2D;

		public const SUMMON_BEHAVIOR IS_2D = SUMMON_BEHAVIOR.IS_2D;

		public const SUMMON_BEHAVIOR DEAD_CHARACTERS = SUMMON_BEHAVIOR.DEAD_CHARACTERS;

		public const SUMMON_BEHAVIOR SUMMON_BEHAVIOR_END = SUMMON_BEHAVIOR.SUMMON_BEHAVIOR_END;

		public const SUMMON_BEHAVIOR SHAKE_CAMERA = SUMMON_BEHAVIOR.SHAKE_CAMERA;

		public const SUMMON_BEHAVIOR ROTATE_CHARACTER = SUMMON_BEHAVIOR.ROTATE_CHARACTER;

		public const SUMMON_BEHAVIOR READY_MOVE_CHARACTER = SUMMON_BEHAVIOR.READY_MOVE_CHARACTER;

		public const SUMMON_BEHAVIOR MOVE_CHARACTER = SUMMON_BEHAVIOR.MOVE_CHARACTER;

		public const SUMMON_BEHAVIOR SET_FLASH = SUMMON_BEHAVIOR.SET_FLASH;

		public const SUMMON_BEHAVIOR READY_AUTO_CAMERA = SUMMON_BEHAVIOR.READY_AUTO_CAMERA;

		public const SUMMON_BEHAVIOR IS_AUTO_CAMERA = SUMMON_BEHAVIOR.IS_AUTO_CAMERA;

		public const SUMMON_BEHAVIOR DRAW_TARGET_EFFECT = SUMMON_BEHAVIOR.DRAW_TARGET_EFFECT;

		public const SUMMON_BEHAVIOR IS_SHAKE_CAMERA = SUMMON_BEHAVIOR.IS_SHAKE_CAMERA;

		public const SUMMON_BEHAVIOR SET_SHOW_PLAYER_WINDOW = SUMMON_BEHAVIOR.SET_SHOW_PLAYER_WINDOW;

		public const SUMMON_BEHAVIOR CRAETE_EFFECT_AND_SET_POSITION = SUMMON_BEHAVIOR.CRAETE_EFFECT_AND_SET_POSITION;

		public const SUMMON_BEHAVIOR IS_END_MONSTER_EFFECT = SUMMON_BEHAVIOR.IS_END_MONSTER_EFFECT;

		public const SUMMON_BEHAVIOR IS_END_PLAYER_EFFECT = SUMMON_BEHAVIOR.IS_END_PLAYER_EFFECT;

		public const SUMMON_BEHAVIOR SET_MONSTERS_ALPHA = SUMMON_BEHAVIOR.SET_MONSTERS_ALPHA;

		public const SUMMON_BEHAVIOR APPEAR_MONSTERS = SUMMON_BEHAVIOR.APPEAR_MONSTERS;

		public const SUMMON_BEHAVIOR DISAPPEAR_MONSTERS = SUMMON_BEHAVIOR.DISAPPEAR_MONSTERS;

		public const SUMMON_BEHAVIOR SET_SE = SUMMON_BEHAVIOR.SET_SE;

		public const SUMMON_BEHAVIOR PLAY_SE = SUMMON_BEHAVIOR.PLAY_SE;

		public const SUMMON_BEHAVIOR CLEAR_SE = SUMMON_BEHAVIOR.CLEAR_SE;

		public const SUMMON_BEHAVIOR SUMMON_BEHAVIOR_MAX = SUMMON_BEHAVIOR.SUMMON_BEHAVIOR_MAX;

		public const int TARGET_ALL_ENEMY = 0;

		public const int TARGET_ALL_PLAYER = 1;

		public const int TARGET_ALL_TYPE_MAX = 2;

		private const int BattlePlayerMax = 4;

		private const int BattleMonsterMax = 6;

		private const int BattleNPCMax = 1;

		private const int SummonMax = 1;

		public const int BattleCharMax = 12;

		private const int MonsterAlphaMax = 31;

		private const int StartFormationFrontMonster = 3;

		private const int EndFormationFrontMonster = 5;

		private const int MostUpFormationFrontMonster = 4;

		private const int MostDownFormationFrontMonster = 5;

		private const int StartFormationBackMonster = 0;

		private const int EndFormationBackMonster = 2;

		private const int MostUpFormationBackMonster = 1;

		private const int MostDownFormationBackMonster = 2;

		private const int GapFormationMonster = 3;

		private const int FrontMonsterMax = 3;

		private const int BackMonsterMax = 3;

		private const int EffectCharMax = 13;

		private const int FILE_NAME_MAX = 32;

		private const int PLAYER_EFFECTS_MAX = 2;

		private const int USE_MAGIC_NUMBER_MAX = 2;

		public const BATTLE_TYPE NORMAL_BATTLE = BATTLE_TYPE.NORMAL_BATTLE;

		public const BATTLE_TYPE EVENT_BATTLE = BATTLE_TYPE.EVENT_BATTLE;

		public const BATTLE_TYPE BOSS_BATTLE = BATTLE_TYPE.BOSS_BATTLE;

		public const BATTLE_TYPE LAST_BOSS_BATTLE = BATTLE_TYPE.LAST_BOSS_BATTLE;

		public const BATTLE_TYPE EVENT_BATTLE_MAX = BATTLE_TYPE.EVENT_BATTLE_MAX;

		public const BATTLE_CAMERA FREE_CAMERA = BATTLE_CAMERA.FREE_CAMERA;

		public const BATTLE_CAMERA OPENING_CAMERA = BATTLE_CAMERA.OPENING_CAMERA;

		public const BATTLE_CAMERA COMMAND_CAMERA = BATTLE_CAMERA.COMMAND_CAMERA;

		public const BATTLE_CAMERA MAIN_CAMERA = BATTLE_CAMERA.MAIN_CAMERA;

		public const BATTLE_CAMERA MOVE_CAMERA = BATTLE_CAMERA.MOVE_CAMERA;

		public const BATTLE_CAMERA RETURN_CAMERA = BATTLE_CAMERA.RETURN_CAMERA;

		public const BATTLE_CAMERA ENDING_CAMERA = BATTLE_CAMERA.ENDING_CAMERA;

		public const BATTLE_CAMERA BATTLE_CAMERA_MAX = BATTLE_CAMERA.BATTLE_CAMERA_MAX;

		public const CHARACTER_BREED BREED_PLAYER = CHARACTER_BREED.BREED_PLAYER;

		public const CHARACTER_BREED BREED_MONSTER = CHARACTER_BREED.BREED_MONSTER;

		public const CHARACTER_BREED BREED_NPC = CHARACTER_BREED.BREED_NPC;

		public const CHARACTER_BREED BREED_SUMMON = CHARACTER_BREED.BREED_SUMMON;

		public const CHARACTER_BREED CHARACTER_BREED_MAX = CHARACTER_BREED.CHARACTER_BREED_MAX;

		public const BATTLE_SYSTEM_STATE OPENING = BATTLE_SYSTEM_STATE.OPENING;

		public const BATTLE_SYSTEM_STATE MAIN = BATTLE_SYSTEM_STATE.MAIN;

		public const BATTLE_SYSTEM_STATE ENDING = BATTLE_SYSTEM_STATE.ENDING;

		public const BATTLE_SYSTEM_STATE BATTLE_SYSTEM_STATE_MAX = BATTLE_SYSTEM_STATE.BATTLE_SYSTEM_STATE_MAX;

		public const BATTLE_OPENING_TYPE NORMAL_ATTACK = BATTLE_OPENING_TYPE.NORMAL_ATTACK;

		public const BATTLE_OPENING_TYPE INITIATLVE_ATTACK = BATTLE_OPENING_TYPE.INITIATLVE_ATTACK;

		public const BATTLE_OPENING_TYPE BACK_ATTACK = BATTLE_OPENING_TYPE.BACK_ATTACK;

		public const BATTLE_OPENING_TYPE BATTLE_OPENING_TYPE_MAX = BATTLE_OPENING_TYPE.BATTLE_OPENING_TYPE_MAX;

		public const BATTLE_OPENING_TYPE CALC_BATTLE_OPENING_TYPE = BATTLE_OPENING_TYPE.CALC_BATTLE_OPENING_TYPE;

		public const BATTLE_MAIN_STATE SETUP_PLAYER = BATTLE_MAIN_STATE.SETUP_PLAYER;

		public const BATTLE_MAIN_STATE SETUP_ENEMY = BATTLE_MAIN_STATE.SETUP_ENEMY;

		public const BATTLE_MAIN_STATE TURN_EXECUTE = BATTLE_MAIN_STATE.TURN_EXECUTE;

		public const BATTLE_MAIN_STATE BATTLE_MAIN_STATE_MAX = BATTLE_MAIN_STATE.BATTLE_MAIN_STATE_MAX;

		public const BATTLE_RESULT WIN = BATTLE_RESULT.WIN;

		public const BATTLE_RESULT LOSE = BATTLE_RESULT.LOSE;

		public const BATTLE_RESULT PLAYER_ESCAPE = BATTLE_RESULT.PLAYER_ESCAPE;

		public const BATTLE_RESULT BATTLE_RESULT_MAX = BATTLE_RESULT.BATTLE_RESULT_MAX;

		public const BATTLE_RESULT ERR_RESULT = BATTLE_RESULT.ERR_RESULT;

		public const int MEMBER_POISON = 3;

		public const int MEMBER_DARKNESS = 4;

		public const int MEMBER_SILENCE = 6;

		public const int MEMBER_NEAR_STONE = 10;

		public const int MEMBER_SLEEP = 12;

		public const int MEMBER_PARALYSIS = 13;

		public const int MEMBER_CONFUSION = 11;

		public const PLAYER_FLAG PF_ESCAPE = PLAYER_FLAG.PF_ESCAPE;

		public const PLAYER_FLAG PF_GUARD = PLAYER_FLAG.PF_GUARD;

		public const PLAYER_FLAG PF_DEAD = PLAYER_FLAG.PF_DEAD;

		public const PLAYER_FLAG PF_MISS = PLAYER_FLAG.PF_MISS;

		public const PLAYER_FLAG PF_BERSERK = PLAYER_FLAG.PF_BERSERK;

		public const PLAYER_FLAG PF_EFFECT = PLAYER_FLAG.PF_EFFECT;

		public const PLAYER_FLAG PF_CREATE_EFFECT = PLAYER_FLAG.PF_CREATE_EFFECT;

		public const PLAYER_FLAG PF_RECOVER = PLAYER_FLAG.PF_RECOVER;

		public const PLAYER_FLAG PF_FINISH = PLAYER_FLAG.PF_FINISH;

		public const PLAYER_FLAG PF_2D = PLAYER_FLAG.PF_2D;

		public const PLAYER_FLAG PF_MAGIC_LOOP_END = PLAYER_FLAG.PF_MAGIC_LOOP_END;

		public const PLAYER_FLAG PF_CRITICAL = PLAYER_FLAG.PF_CRITICAL;

		public const PLAYER_FLAG PF_CREATE_2D = PLAYER_FLAG.PF_CREATE_2D;

		public const PLAYER_FLAG PF_TARGET_PLAYER = PLAYER_FLAG.PF_TARGET_PLAYER;

		public const PLAYER_FLAG PF_TARGET_MONSTER = PLAYER_FLAG.PF_TARGET_MONSTER;

		public const PLAYER_FLAG PF_COUNTER = PLAYER_FLAG.PF_COUNTER;

		public const PLAYER_FLAG PF_ATTACKED = PLAYER_FLAG.PF_ATTACKED;

		public const PLAYER_FLAG PF_MORE_GUARD = PLAYER_FLAG.PF_MORE_GUARD;

		public const PLAYER_FLAG PF_JUMP = PLAYER_FLAG.PF_JUMP;

		public const PLAYER_FLAG PF_DARK = PLAYER_FLAG.PF_DARK;

		public const PLAYER_FLAG PF_ROLL_UP = PLAYER_FLAG.PF_ROLL_UP;

		public const PLAYER_FLAG PF_EXPLOSION = PLAYER_FLAG.PF_EXPLOSION;

		public const PLAYER_FLAG PF_COVER = PLAYER_FLAG.PF_COVER;

		public const PLAYER_FLAG PF_OVERISSUE = PLAYER_FLAG.PF_OVERISSUE;

		public const PLAYER_FLAG PF_PITCH = PLAYER_FLAG.PF_PITCH;

		public const PLAYER_FLAG PF_PROVOCATION = PLAYER_FLAG.PF_PROVOCATION;

		public const PLAYER_FLAG PF_ERASE = PLAYER_FLAG.PF_ERASE;

		public const PLAYER_FLAG PF_ABSORB = PLAYER_FLAG.PF_ABSORB;

		public const PLAYER_FLAG PF_KNOCK_OVER = PLAYER_FLAG.PF_KNOCK_OVER;

		public const PLAYER_FLAG PF_TAKE_A_POWDER = PLAYER_FLAG.PF_TAKE_A_POWDER;

		public const PLAYER_FLAG PF_POISON_NOW = PLAYER_FLAG.PF_POISON_NOW;

		public const MONSTER_FLAG MF_WEAK_CHANGE = MONSTER_FLAG.MF_WEAK_CHANGE;

		public const MONSTER_FLAG MF_SPECIAL_ATTACKED = MONSTER_FLAG.MF_SPECIAL_ATTACKED;

		public const MONSTER_FLAG MF_BREAK = MONSTER_FLAG.MF_BREAK;

		public const MAGIC_FLAG MF_PROTECT = MAGIC_FLAG.MF_PROTECT;

		public const MAGIC_FLAG MF_HASTE = MAGIC_FLAG.MF_HASTE;

		public const MAGIC_FLAG MF_BAHAMUT = MAGIC_FLAG.MF_BAHAMUT;

		public const MAGIC_FLAG MF_SONG1 = MAGIC_FLAG.MF_SONG1;

		public const MAGIC_FLAG MF_SONG2 = MAGIC_FLAG.MF_SONG2;

		public const MAGIC_FLAG MF_SONG5 = MAGIC_FLAG.MF_SONG5;

		public const MAGIC_FLAG MF_REFLECT = MAGIC_FLAG.MF_REFLECT;

		public const MAGIC_FLAG MF_REFLECTED = MAGIC_FLAG.MF_REFLECTED;

		public const MAGIC_FLAG MF_SLEEP = MAGIC_FLAG.MF_SLEEP;

		public const MAGIC_FLAG MF_RECOVER_SLEEP = MAGIC_FLAG.MF_RECOVER_SLEEP;

		public const MAGIC_FLAG MF_CONFUSION = MAGIC_FLAG.MF_CONFUSION;

		public const MAGIC_FLAG MF_RECOVER_CONFUSION = MAGIC_FLAG.MF_RECOVER_CONFUSION;

		public const PLAYER_BATTLE_ACTION PBA_IDLE = PLAYER_BATTLE_ACTION.PBA_IDLE;

		public const PLAYER_BATTLE_ACTION PBA_NORMAL_ATTACK = PLAYER_BATTLE_ACTION.PBA_NORMAL_ATTACK;

		public const PLAYER_BATTLE_ACTION PBA_ESCAPE = PLAYER_BATTLE_ACTION.PBA_ESCAPE;

		public const PLAYER_BATTLE_ACTION PBA_GUARD_START = PLAYER_BATTLE_ACTION.PBA_GUARD_START;

		public const PLAYER_BATTLE_ACTION PBA_SPECIAL_ATTACK = PLAYER_BATTLE_ACTION.PBA_SPECIAL_ATTACK;

		public const PLAYER_BATTLE_ACTION PBA_NORMAL_MAGIC = PLAYER_BATTLE_ACTION.PBA_NORMAL_MAGIC;

		public const PLAYER_BATTLE_ACTION PBA_SUMMON_MAGIC = PLAYER_BATTLE_ACTION.PBA_SUMMON_MAGIC;

		public const PLAYER_BATTLE_ACTION PBA_ITEM = PLAYER_BATTLE_ACTION.PBA_ITEM;

		public const PLAYER_BATTLE_ACTION PBA_STEAL = PLAYER_BATTLE_ACTION.PBA_STEAL;

		public const PLAYER_BATTLE_ACTION PBA_TAKE_A_POWDER = PLAYER_BATTLE_ACTION.PBA_TAKE_A_POWDER;

		public const PLAYER_BATTLE_ACTION PBA_BERSERK = PLAYER_BATTLE_ACTION.PBA_BERSERK;

		public const PLAYER_BATTLE_ACTION PBA_KNOCK_OVER = PLAYER_BATTLE_ACTION.PBA_KNOCK_OVER;

		public const PLAYER_BATTLE_ACTION PBA_POISE = PLAYER_BATTLE_ACTION.PBA_POISE;

		public const PLAYER_BATTLE_ACTION PBA_COVER_START = PLAYER_BATTLE_ACTION.PBA_COVER_START;

		public const PLAYER_BATTLE_ACTION PBA_CHECK = PLAYER_BATTLE_ACTION.PBA_CHECK;

		public const PLAYER_BATTLE_ACTION PBA_DETECT = PLAYER_BATTLE_ACTION.PBA_DETECT;

		public const PLAYER_BATTLE_ACTION PBA_JUMP_START = PLAYER_BATTLE_ACTION.PBA_JUMP_START;

		public const PLAYER_BATTLE_ACTION PBA_JUMP_END = PLAYER_BATTLE_ACTION.PBA_JUMP_END;

		public const PLAYER_BATTLE_ACTION PBA_DARK = PLAYER_BATTLE_ACTION.PBA_DARK;

		public const PLAYER_BATTLE_ACTION PBA_GEOGRAPHY = PLAYER_BATTLE_ACTION.PBA_GEOGRAPHY;

		public const PLAYER_BATTLE_ACTION PBA_SONG = PLAYER_BATTLE_ACTION.PBA_SONG;

		public const PLAYER_BATTLE_ACTION PBA_ROLL_UP = PLAYER_BATTLE_ACTION.PBA_ROLL_UP;

		public const PLAYER_BATTLE_ACTION PBA_PITCH = PLAYER_BATTLE_ACTION.PBA_PITCH;

		public const PLAYER_BATTLE_ACTION PBA_PROVOCATION = PLAYER_BATTLE_ACTION.PBA_PROVOCATION;

		public const PLAYER_BATTLE_ACTION PBA_OVERISSUE = PLAYER_BATTLE_ACTION.PBA_OVERISSUE;

		public const PLAYER_BATTLE_ACTION PBA_COUNTER = PLAYER_BATTLE_ACTION.PBA_COUNTER;

		public const PLAYER_BATTLE_ACTION PBA_CHANGE_FORMATION = PLAYER_BATTLE_ACTION.PBA_CHANGE_FORMATION;

		public const PLAYER_BATTLE_ACTION PLAYER_BATTLE_ACTION_MAX = PLAYER_BATTLE_ACTION.PLAYER_BATTLE_ACTION_MAX;

		public const BATTLE_ACTION_TYPE DBA_FRONT = BATTLE_ACTION_TYPE.DBA_FRONT;

		public const BATTLE_ACTION_TYPE DBA_BACK = BATTLE_ACTION_TYPE.DBA_BACK;

		public const BATTLE_ACTION_TYPE DBA_NORMAL_ATTACK = BATTLE_ACTION_TYPE.DBA_NORMAL_ATTACK;

		public const BATTLE_ACTION_TYPE DBA_DAMAGE = BATTLE_ACTION_TYPE.DBA_DAMAGE;

		public const BATTLE_ACTION_TYPE DBA_ESCAPE = BATTLE_ACTION_TYPE.DBA_ESCAPE;

		public const BATTLE_ACTION_TYPE DBA_FINISH = BATTLE_ACTION_TYPE.DBA_FINISH;

		public const BATTLE_ACTION_TYPE DBA_IDLE_TO_POISE = BATTLE_ACTION_TYPE.DBA_IDLE_TO_POISE;

		public const BATTLE_ACTION_TYPE DBA_POISE_TO_IDLE = BATTLE_ACTION_TYPE.DBA_POISE_TO_IDLE;

		public const BATTLE_ACTION_TYPE DBA_FRONT_ATTACK = BATTLE_ACTION_TYPE.DBA_FRONT_ATTACK;

		public const BATTLE_ACTION_TYPE DBA_BACK_ATTACK = BATTLE_ACTION_TYPE.DBA_BACK_ATTACK;

		public const BATTLE_ACTION_TYPE DBA_CHANGE_FRONT = BATTLE_ACTION_TYPE.DBA_CHANGE_FRONT;

		public const BATTLE_ACTION_TYPE DBA_CHANGE_BACK = BATTLE_ACTION_TYPE.DBA_CHANGE_BACK;

		public const BATTLE_ACTION_TYPE DBA_GUARD_START = BATTLE_ACTION_TYPE.DBA_GUARD_START;

		public const BATTLE_ACTION_TYPE DBA_GUARD = BATTLE_ACTION_TYPE.DBA_GUARD;

		public const BATTLE_ACTION_TYPE DBA_MAGIC = BATTLE_ACTION_TYPE.DBA_MAGIC;

		public const BATTLE_ACTION_TYPE DBA_MAGIC_LOOP = BATTLE_ACTION_TYPE.DBA_MAGIC_LOOP;

		public const BATTLE_ACTION_TYPE DBA_STEAL = BATTLE_ACTION_TYPE.DBA_STEAL;

		public const BATTLE_ACTION_TYPE DBA_TAKE_A_POWDER = BATTLE_ACTION_TYPE.DBA_TAKE_A_POWDER;

		public const BATTLE_ACTION_TYPE DBA_PROTECT = BATTLE_ACTION_TYPE.DBA_PROTECT;

		public const BATTLE_ACTION_TYPE DBA_ITEM = BATTLE_ACTION_TYPE.DBA_ITEM;

		public const BATTLE_ACTION_TYPE DBA_ITEM_LOOP = BATTLE_ACTION_TYPE.DBA_ITEM_LOOP;

		public const BATTLE_ACTION_TYPE DBA_KNOCK_OVER_FRONT = BATTLE_ACTION_TYPE.DBA_KNOCK_OVER_FRONT;

		public const BATTLE_ACTION_TYPE DBA_KNOCK_OVER_BACK = BATTLE_ACTION_TYPE.DBA_KNOCK_OVER_BACK;

		public const BATTLE_ACTION_TYPE DBA_POISE = BATTLE_ACTION_TYPE.DBA_POISE;

		public const BATTLE_ACTION_TYPE DBA_COVER_START = BATTLE_ACTION_TYPE.DBA_COVER_START;

		public const BATTLE_ACTION_TYPE DBA_CHECK = BATTLE_ACTION_TYPE.DBA_CHECK;

		public const BATTLE_ACTION_TYPE DBA_DETECT = BATTLE_ACTION_TYPE.DBA_DETECT;

		public const BATTLE_ACTION_TYPE DBA_JUMP_START = BATTLE_ACTION_TYPE.DBA_JUMP_START;

		public const BATTLE_ACTION_TYPE DBA_JUMP_END = BATTLE_ACTION_TYPE.DBA_JUMP_END;

		public const BATTLE_ACTION_TYPE DBA_DARK = BATTLE_ACTION_TYPE.DBA_DARK;

		public const BATTLE_ACTION_TYPE DBA_GEOGRAPHY = BATTLE_ACTION_TYPE.DBA_GEOGRAPHY;

		public const BATTLE_ACTION_TYPE DBA_SONG = BATTLE_ACTION_TYPE.DBA_SONG;

		public const BATTLE_ACTION_TYPE DBA_ROLL_UP = BATTLE_ACTION_TYPE.DBA_ROLL_UP;

		public const BATTLE_ACTION_TYPE DBA_PITCH = BATTLE_ACTION_TYPE.DBA_PITCH;

		public const BATTLE_ACTION_TYPE DBA_PROVOCATION = BATTLE_ACTION_TYPE.DBA_PROVOCATION;

		public const BATTLE_ACTION_TYPE DBA_COVER = BATTLE_ACTION_TYPE.DBA_COVER;

		public const BATTLE_ACTION_TYPE DBA_IDLE = BATTLE_ACTION_TYPE.DBA_IDLE;

		public const BATTLE_ACTION_TYPE DBA_CONDITION_MOTION = BATTLE_ACTION_TYPE.DBA_CONDITION_MOTION;

		public const BATTLE_ACTION_TYPE BATTLE_ACTION_TYPE_MAX = BATTLE_ACTION_TYPE.BATTLE_ACTION_TYPE_MAX;

		public const BATTLE_ACTION_TYPE DBA_NON_ACTION = BATTLE_ACTION_TYPE.DBA_NON_ACTION;

		public const PLAYER_BATTLE_MOTION PBM_IDLE = PLAYER_BATTLE_MOTION.PBM_IDLE;

		public const PLAYER_BATTLE_MOTION PBM_POISE = PLAYER_BATTLE_MOTION.PBM_POISE;

		public const PLAYER_BATTLE_MOTION PBM_POISE_HARP = PLAYER_BATTLE_MOTION.PBM_POISE_HARP;

		public const PLAYER_BATTLE_MOTION PBM_POISE_NEARDEATH = PLAYER_BATTLE_MOTION.PBM_POISE_NEARDEATH;

		public const PLAYER_BATTLE_MOTION PBM_POISE_NEARDEATH_AXE = PLAYER_BATTLE_MOTION.PBM_POISE_NEARDEATH_AXE;

		public const PLAYER_BATTLE_MOTION PBM_POISE_NEARDEATH_THROW = PLAYER_BATTLE_MOTION.PBM_POISE_NEARDEATH_THROW;

		public const PLAYER_BATTLE_MOTION PBM_POISE_NEARDEATH_BELL = PLAYER_BATTLE_MOTION.PBM_POISE_NEARDEATH_BELL;

		public const PLAYER_BATTLE_MOTION PBM_POISE_NEARDEATH_BOOK = PLAYER_BATTLE_MOTION.PBM_POISE_NEARDEATH_BOOK;

		public const PLAYER_BATTLE_MOTION PBM_POISE_POISON = PLAYER_BATTLE_MOTION.PBM_POISE_POISON;

		public const PLAYER_BATTLE_MOTION PBM_POISE_POISON_AXE = PLAYER_BATTLE_MOTION.PBM_POISE_POISON_AXE;

		public const PLAYER_BATTLE_MOTION PBM_POISE_POISON_BOW = PLAYER_BATTLE_MOTION.PBM_POISE_POISON_BOW;

		public const PLAYER_BATTLE_MOTION PBM_POISE_POISON_HARP = PLAYER_BATTLE_MOTION.PBM_POISE_POISON_HARP;

		public const PLAYER_BATTLE_MOTION PBM_POISE_POISON_BOOK = PLAYER_BATTLE_MOTION.PBM_POISE_POISON_BOOK;

		public const PLAYER_BATTLE_MOTION PBM_POISE_MAGIC = PLAYER_BATTLE_MOTION.PBM_POISE_MAGIC;

		public const PLAYER_BATTLE_MOTION PBM_FRONT = PLAYER_BATTLE_MOTION.PBM_FRONT;

		public const PLAYER_BATTLE_MOTION PBM_FRONT_POISE = PLAYER_BATTLE_MOTION.PBM_FRONT_POISE;

		public const PLAYER_BATTLE_MOTION PBM_FRONT_BADCONDITION = PLAYER_BATTLE_MOTION.PBM_FRONT_BADCONDITION;

		public const PLAYER_BATTLE_MOTION PBM_BACK = PLAYER_BATTLE_MOTION.PBM_BACK;

		public const PLAYER_BATTLE_MOTION PBM_BACK_POISE = PLAYER_BATTLE_MOTION.PBM_BACK_POISE;

		public const PLAYER_BATTLE_MOTION PBM_BACK_BADCONDITION = PLAYER_BATTLE_MOTION.PBM_BACK_BADCONDITION;

		public const PLAYER_BATTLE_MOTION PBM_USE_ITEM = PLAYER_BATTLE_MOTION.PBM_USE_ITEM;

		public const PLAYER_BATTLE_MOTION PBM_ESCAPE = PLAYER_BATTLE_MOTION.PBM_ESCAPE;

		public const PLAYER_BATTLE_MOTION PBM_GUARD_START = PLAYER_BATTLE_MOTION.PBM_GUARD_START;

		public const PLAYER_BATTLE_MOTION PBM_GUARD = PLAYER_BATTLE_MOTION.PBM_GUARD;

		public const PLAYER_BATTLE_MOTION PBM_DAMAGE = PLAYER_BATTLE_MOTION.PBM_DAMAGE;

		public const PLAYER_BATTLE_MOTION PBM_DEATH = PLAYER_BATTLE_MOTION.PBM_DEATH;

		public const PLAYER_BATTLE_MOTION PBM_COMEBACK = PLAYER_BATTLE_MOTION.PBM_COMEBACK;

		public const PLAYER_BATTLE_MOTION PBM_BACK_ATTACK = PLAYER_BATTLE_MOTION.PBM_BACK_ATTACK;

		public const PLAYER_BATTLE_MOTION PBM_BACK_ATTACK_FROG = PLAYER_BATTLE_MOTION.PBM_BACK_ATTACK_FROG;

		public const PLAYER_BATTLE_MOTION PBM_WIN1 = PLAYER_BATTLE_MOTION.PBM_WIN1;

		public const PLAYER_BATTLE_MOTION PBM_WIN2 = PLAYER_BATTLE_MOTION.PBM_WIN2;

		public const PLAYER_BATTLE_MOTION PBM_WIN3 = PLAYER_BATTLE_MOTION.PBM_WIN3;

		public const PLAYER_BATTLE_MOTION PBM_WIN4 = PLAYER_BATTLE_MOTION.PBM_WIN4;

		public const PLAYER_BATTLE_MOTION PBM_LEVEL_UP1 = PLAYER_BATTLE_MOTION.PBM_LEVEL_UP1;

		public const PLAYER_BATTLE_MOTION PBM_LEVEL_UP2 = PLAYER_BATTLE_MOTION.PBM_LEVEL_UP2;

		public const PLAYER_BATTLE_MOTION PBM_LEVEL_UP3 = PLAYER_BATTLE_MOTION.PBM_LEVEL_UP3;

		public const PLAYER_BATTLE_MOTION PBM_LEVEL_UP4 = PLAYER_BATTLE_MOTION.PBM_LEVEL_UP4;

		public const PLAYER_BATTLE_MOTION PBM_HAND_R1 = PLAYER_BATTLE_MOTION.PBM_HAND_R1;

		public const PLAYER_BATTLE_MOTION PBM_HAND_R2 = PLAYER_BATTLE_MOTION.PBM_HAND_R2;

		public const PLAYER_BATTLE_MOTION PBM_HAND_L1 = PLAYER_BATTLE_MOTION.PBM_HAND_L1;

		public const PLAYER_BATTLE_MOTION PBM_HAND_L2 = PLAYER_BATTLE_MOTION.PBM_HAND_L2;

		public const PLAYER_BATTLE_MOTION PBM_HAND_FINISH = PLAYER_BATTLE_MOTION.PBM_HAND_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_SSWORD_R1 = PLAYER_BATTLE_MOTION.PBM_SSWORD_R1;

		public const PLAYER_BATTLE_MOTION PBM_SSWORD_R2 = PLAYER_BATTLE_MOTION.PBM_SSWORD_R2;

		public const PLAYER_BATTLE_MOTION PBM_SSWORD_L1 = PLAYER_BATTLE_MOTION.PBM_SSWORD_L1;

		public const PLAYER_BATTLE_MOTION PBM_SSWORD_L2 = PLAYER_BATTLE_MOTION.PBM_SSWORD_L2;

		public const PLAYER_BATTLE_MOTION PBM_SSWORD_FINISH = PLAYER_BATTLE_MOTION.PBM_SSWORD_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_LSWORD_R1 = PLAYER_BATTLE_MOTION.PBM_LSWORD_R1;

		public const PLAYER_BATTLE_MOTION PBM_LSWORD_R2 = PLAYER_BATTLE_MOTION.PBM_LSWORD_R2;

		public const PLAYER_BATTLE_MOTION PBM_LSWORD_L1 = PLAYER_BATTLE_MOTION.PBM_LSWORD_L1;

		public const PLAYER_BATTLE_MOTION PBM_LSWORD_L2 = PLAYER_BATTLE_MOTION.PBM_LSWORD_L2;

		public const PLAYER_BATTLE_MOTION PBM_LSWORD_FINISH = PLAYER_BATTLE_MOTION.PBM_LSWORD_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_KATANA_R1 = PLAYER_BATTLE_MOTION.PBM_KATANA_R1;

		public const PLAYER_BATTLE_MOTION PBM_KATANA_R2 = PLAYER_BATTLE_MOTION.PBM_KATANA_R2;

		public const PLAYER_BATTLE_MOTION PBM_KATANA_L1 = PLAYER_BATTLE_MOTION.PBM_KATANA_L1;

		public const PLAYER_BATTLE_MOTION PBM_KATANA_L2 = PLAYER_BATTLE_MOTION.PBM_KATANA_L2;

		public const PLAYER_BATTLE_MOTION PBM_KATANA_FINISH = PLAYER_BATTLE_MOTION.PBM_KATANA_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_AXE_R1 = PLAYER_BATTLE_MOTION.PBM_AXE_R1;

		public const PLAYER_BATTLE_MOTION PBM_AXE_R2 = PLAYER_BATTLE_MOTION.PBM_AXE_R2;

		public const PLAYER_BATTLE_MOTION PBM_AXE_L1 = PLAYER_BATTLE_MOTION.PBM_AXE_L1;

		public const PLAYER_BATTLE_MOTION PBM_AXE_L2 = PLAYER_BATTLE_MOTION.PBM_AXE_L2;

		public const PLAYER_BATTLE_MOTION PBM_AXE_FINISH = PLAYER_BATTLE_MOTION.PBM_AXE_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_SPEAR_R1 = PLAYER_BATTLE_MOTION.PBM_SPEAR_R1;

		public const PLAYER_BATTLE_MOTION PBM_SPEAR_R2 = PLAYER_BATTLE_MOTION.PBM_SPEAR_R2;

		public const PLAYER_BATTLE_MOTION PBM_SPEAR_L1 = PLAYER_BATTLE_MOTION.PBM_SPEAR_L1;

		public const PLAYER_BATTLE_MOTION PBM_SPEAR_L2 = PLAYER_BATTLE_MOTION.PBM_SPEAR_L2;

		public const PLAYER_BATTLE_MOTION PBM_SPEAR_FINISH = PLAYER_BATTLE_MOTION.PBM_SPEAR_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_ROD_R1 = PLAYER_BATTLE_MOTION.PBM_ROD_R1;

		public const PLAYER_BATTLE_MOTION PBM_ROD_R2 = PLAYER_BATTLE_MOTION.PBM_ROD_R2;

		public const PLAYER_BATTLE_MOTION PBM_ROD_L1 = PLAYER_BATTLE_MOTION.PBM_ROD_L1;

		public const PLAYER_BATTLE_MOTION PBM_ROD_L2 = PLAYER_BATTLE_MOTION.PBM_ROD_L2;

		public const PLAYER_BATTLE_MOTION PBM_ROD_FINISH = PLAYER_BATTLE_MOTION.PBM_ROD_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_BOW1 = PLAYER_BATTLE_MOTION.PBM_BOW1;

		public const PLAYER_BATTLE_MOTION PBM_BOW_FINISH = PLAYER_BATTLE_MOTION.PBM_BOW_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_THROW1 = PLAYER_BATTLE_MOTION.PBM_THROW1;

		public const PLAYER_BATTLE_MOTION PBM_THROW2 = PLAYER_BATTLE_MOTION.PBM_THROW2;

		public const PLAYER_BATTLE_MOTION PBM_THROW_FINISH = PLAYER_BATTLE_MOTION.PBM_THROW_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_HARP1 = PLAYER_BATTLE_MOTION.PBM_HARP1;

		public const PLAYER_BATTLE_MOTION PBM_HARP_FINISH = PLAYER_BATTLE_MOTION.PBM_HARP_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_BELL_R1 = PLAYER_BATTLE_MOTION.PBM_BELL_R1;

		public const PLAYER_BATTLE_MOTION PBM_BELL_R2 = PLAYER_BATTLE_MOTION.PBM_BELL_R2;

		public const PLAYER_BATTLE_MOTION PBM_BELL_L1 = PLAYER_BATTLE_MOTION.PBM_BELL_L1;

		public const PLAYER_BATTLE_MOTION PBM_BELL_L2 = PLAYER_BATTLE_MOTION.PBM_BELL_L2;

		public const PLAYER_BATTLE_MOTION PBM_BELL_FINISH = PLAYER_BATTLE_MOTION.PBM_BELL_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_BOOK_R1 = PLAYER_BATTLE_MOTION.PBM_BOOK_R1;

		public const PLAYER_BATTLE_MOTION PBM_BOOK_R2 = PLAYER_BATTLE_MOTION.PBM_BOOK_R2;

		public const PLAYER_BATTLE_MOTION PBM_BOOK_L1 = PLAYER_BATTLE_MOTION.PBM_BOOK_L1;

		public const PLAYER_BATTLE_MOTION PBM_BOOK_L2 = PLAYER_BATTLE_MOTION.PBM_BOOK_L2;

		public const PLAYER_BATTLE_MOTION PBM_BOOK_FINISH = PLAYER_BATTLE_MOTION.PBM_BOOK_FINISH;

		public const PLAYER_BATTLE_MOTION PBM_MAGIC_POISE = PLAYER_BATTLE_MOTION.PBM_MAGIC_POISE;

		public const PLAYER_BATTLE_MOTION PBM_MAGIC_SHOT_START = PLAYER_BATTLE_MOTION.PBM_MAGIC_SHOT_START;

		public const PLAYER_BATTLE_MOTION PBM_MAGIC_SHOT = PLAYER_BATTLE_MOTION.PBM_MAGIC_SHOT;

		public const PLAYER_BATTLE_MOTION PBM_STEAL = PLAYER_BATTLE_MOTION.PBM_STEAL;

		public const PLAYER_BATTLE_MOTION PBM_CHECK = PLAYER_BATTLE_MOTION.PBM_CHECK;

		public const PLAYER_BATTLE_MOTION PBM_JUMP_START = PLAYER_BATTLE_MOTION.PBM_JUMP_START;

		public const PLAYER_BATTLE_MOTION PBM_JUMP_END = PLAYER_BATTLE_MOTION.PBM_JUMP_END;

		public const PLAYER_BATTLE_MOTION PBM_DARK = PLAYER_BATTLE_MOTION.PBM_DARK;

		public const PLAYER_BATTLE_MOTION PBM_MONK = PLAYER_BATTLE_MOTION.PBM_GUARD_START;

		public const PLAYER_BATTLE_MOTION PBM_ROLL_UP = PLAYER_BATTLE_MOTION.PBM_ROLL_UP;

		public const PLAYER_BATTLE_MOTION PBM_PROVOCATION = PLAYER_BATTLE_MOTION.PBM_PROVOCATION;

		public const PLAYER_BATTLE_MOTION PBM_COVER = PLAYER_BATTLE_MOTION.PBM_COVER;

		public const PLAYER_BATTLE_MOTION PBM_GEOGRAPHY = PLAYER_BATTLE_MOTION.PBM_GEOGRAPHY;

		public const PLAYER_BATTLE_MOTION PBM_SONG = PLAYER_BATTLE_MOTION.PBM_SONG;

		public const PLAYER_BATTLE_MOTION PBM_FROG_ATTACK = PLAYER_BATTLE_MOTION.PBM_FROG_ATTACK;

		public const PLAYER_BATTLE_MOTION PBM_FROG_ESCAPE = PLAYER_BATTLE_MOTION.PBM_FROG_ESCAPE;

		public const MONSTER_BATTLE_MOTION MBM_IDLE = MONSTER_BATTLE_MOTION.MBM_IDLE;

		public const MONSTER_BATTLE_MOTION MBM_ATTACK = MONSTER_BATTLE_MOTION.MBM_ATTACK;

		public const MONSTER_BATTLE_MOTION MBM_SPECIAL = MONSTER_BATTLE_MOTION.MBM_SPECIAL;

		public const MONSTER_BATTLE_ACTION MBA_IDLE = MONSTER_BATTLE_ACTION.MBA_IDLE;

		public const MONSTER_BATTLE_ACTION MBA_NORMAL_ATTACK = MONSTER_BATTLE_ACTION.MBA_NORMAL_ATTACK;

		public const MONSTER_BATTLE_ACTION MBA_SPECIAL_ATTACK = MONSTER_BATTLE_ACTION.MBA_SPECIAL_ATTACK;

		public const MONSTER_BATTLE_ACTION MBA_MAGIC = MONSTER_BATTLE_ACTION.MBA_MAGIC;

		public const MONSTER_BATTLE_ACTION MONSTER_BATTLE_ACTION_MAX = MONSTER_BATTLE_ACTION.MONSTER_BATTLE_ACTION_MAX;

		public const MAGIC_EFFECT MONSTER_MAGIC = MAGIC_EFFECT.MONSTER_MAGIC;

		public const MAGIC_EFFECT BLACK_MAGIC = MAGIC_EFFECT.BLACK_MAGIC;

		public const MAGIC_EFFECT WHITE_MAGIC = MAGIC_EFFECT.WHITE_MAGIC;

		public const MAGIC_EFFECT SUMMON_MAGIC = MAGIC_EFFECT.SUMMON_MAGIC;

		public const int BLACK_SE = 260;

		public const int WHITE_SE = 250;

		public const int SUMMON_SE = 270;

		public const CONDITION_TURN_TYPE DEFENSE_TURN = CONDITION_TURN_TYPE.DEFENSE_TURN;

		public const CONDITION_TURN_TYPE SPEED_TURN = CONDITION_TURN_TYPE.SPEED_TURN;

		public const CONDITION_TURN_TYPE BAHAMUT_TURN = CONDITION_TURN_TYPE.BAHAMUT_TURN;

		public const CONDITION_TURN_TYPE SONG1_TURN = CONDITION_TURN_TYPE.SONG1_TURN;

		public const CONDITION_TURN_TYPE SONG2_TURN = CONDITION_TURN_TYPE.SONG2_TURN;

		public const CONDITION_TURN_TYPE SONG5_TURN = CONDITION_TURN_TYPE.SONG5_TURN;

		public const CONDITION_TURN_TYPE CONDITION_TURN_TYPE_MAX = CONDITION_TURN_TYPE.CONDITION_TURN_TYPE_MAX;

		public const BATTLE_MESSAGE BM_COUNTER = BATTLE_MESSAGE.BM_COUNTER;

		public const BATTLE_MESSAGE BM_BACK_ATTACK = BATTLE_MESSAGE.BM_BACK_ATTACK;

		public const BATTLE_MESSAGE BM_COVER_FIRE = BATTLE_MESSAGE.BM_COVER_FIRE;

		public const BATTLE_MESSAGE BM_PLAYER_NAME = BATTLE_MESSAGE.BM_PLAYER_NAME;

		public const BATTLE_MESSAGE BM_NOT_ESCAPE = BATTLE_MESSAGE.BM_NOT_ESCAPE;

		public const BATTLE_MESSAGE BM_ESCAPE = BATTLE_MESSAGE.BM_ESCAPE;

		public const BATTLE_MESSAGE BM_GET_GILL = BATTLE_MESSAGE.BM_GET_GILL;

		public const BATTLE_MESSAGE BM_GET_CAPACITY = BATTLE_MESSAGE.BM_GET_CAPACITY;

		public const BATTLE_MESSAGE BM_GET_EXP = BATTLE_MESSAGE.BM_GET_EXP;

		public const BATTLE_MESSAGE BM_LEVEL_UP = BATTLE_MESSAGE.BM_LEVEL_UP;

		public const BATTLE_MESSAGE BM_SKILL_UP = BATTLE_MESSAGE.BM_SKILL_UP;

		public const BATTLE_MESSAGE BM_GET_TREASURE = BATTLE_MESSAGE.BM_GET_TREASURE;

		public const BATTLE_MESSAGE BM_ANNIHILATED = BATTLE_MESSAGE.BM_ANNIHILATED;

		public const BATTLE_MESSAGE BM_CHANGE = BATTLE_MESSAGE.BM_CHANGE;

		public const BATTLE_MESSAGE BM_INITIATLVE_ATTACK = BATTLE_MESSAGE.BM_INITIATLVE_ATTACK;

		public const BATTLE_MESSAGE BM_NOT_STEAL = BATTLE_MESSAGE.BM_NOT_STEAL;

		public const BATTLE_MESSAGE BM_NO_WEAK = BATTLE_MESSAGE.BM_NO_WEAK;

		public const BATTLE_MESSAGE BM_NO_ACTION = BATTLE_MESSAGE.BM_NO_ACTION;

		public const BATTLE_MESSAGE BM_NO_RESULT = BATTLE_MESSAGE.BM_NO_RESULT;

		public const BATTLE_MESSAGE BM_FINE = BATTLE_MESSAGE.BM_FINE;

		public const BATTLE_MESSAGE BM_REBIRTH = BATTLE_MESSAGE.BM_REBIRTH;

		public const BATTLE_MESSAGE BM_COME_BACK = BATTLE_MESSAGE.BM_COME_BACK;

		public const BATTLE_MESSAGE BM_POISON = BATTLE_MESSAGE.BM_POISON;

		public const BATTLE_MESSAGE BM_DARKNESS = BATTLE_MESSAGE.BM_DARKNESS;

		public const BATTLE_MESSAGE BM_POISON_DAMAGE = BATTLE_MESSAGE.BM_POISON_DAMAGE;

		public const BATTLE_MESSAGE BM_TARGET_ALL = BATTLE_MESSAGE.BM_TARGET_ALL;

		public const BATTLE_MESSAGE BM_TARGET_GROUP = BATTLE_MESSAGE.BM_TARGET_GROUP;

		public const BATTLE_MESSAGE BM_MAX_HP_AND_HP = BATTLE_MESSAGE.BM_MAX_HP_AND_HP;

		public const BATTLE_MESSAGE BM_WEAK_THUNDER = BATTLE_MESSAGE.BM_WEAK_THUNDER;

		public const BATTLE_MESSAGE BM_WEAK_ICE = BATTLE_MESSAGE.BM_WEAK_ICE;

		public const BATTLE_MESSAGE BM_WEAK_FIRE = BATTLE_MESSAGE.BM_WEAK_FIRE;

		public const BATTLE_MESSAGE BM_WEAK_WATER = BATTLE_MESSAGE.BM_WEAK_WATER;

		public const BATTLE_MESSAGE BM_WEAK_EARTH = BATTLE_MESSAGE.BM_WEAK_EARTH;

		public const BATTLE_MESSAGE BM_WEAK_HOLY = BATTLE_MESSAGE.BM_WEAK_HOLY;

		public const BATTLE_MESSAGE BM_WEAK_SKY = BATTLE_MESSAGE.BM_WEAK_SKY;

		public const BATTLE_MESSAGE BM_WEAK_DARK = BATTLE_MESSAGE.BM_WEAK_DARK;

		public const BATTLE_MESSAGE BM_INVALIDATION = BATTLE_MESSAGE.BM_INVALIDATION;

		public const BATTLE_MESSAGE BM_NOT_KNOW_HP = BATTLE_MESSAGE.BM_NOT_KNOW_HP;

		public const BATTLE_MESSAGE BM_NOT_KNOW_WEAK = BATTLE_MESSAGE.BM_NOT_KNOW_WEAK;

		public const BATTLE_MESSAGE BM_SELF_EXPLOSION = BATTLE_MESSAGE.BM_SELF_EXPLOSION;

		public const BATTLE_MESSAGE BM_NO_ITEM = BATTLE_MESSAGE.BM_NO_ITEM;

		public const BATTLE_MESSAGE BM_BREAK = BATTLE_MESSAGE.BM_BREAK;

		public const BATTLE_EFFECT_TYPE BET_GUARD = BATTLE_EFFECT_TYPE.BET_GUARD;

		public const BATTLE_EFFECT_TYPE BET_ABILITY = BATTLE_EFFECT_TYPE.BET_ABILITY;

		public const BATTLE_EFFECT_TYPE BET_ROLL_UP = BATTLE_EFFECT_TYPE.BET_ROLL_UP;

		public const BATTLE_EFFECT_TYPE BET_TAP = BATTLE_EFFECT_TYPE.BET_TAP;

		public const BATTLE_EFFECT_TYPE BET_BOOKMAN = BATTLE_EFFECT_TYPE.BET_BOOKMAN;

		public const BATTLE_EFFECT_TYPE BET_JUMP_HIT = BATTLE_EFFECT_TYPE.BET_JUMP_HIT;

		public const BATTLE_EFFECT_TYPE BET_PROVOCATION = BATTLE_EFFECT_TYPE.BET_PROVOCATION;

		public const BATTLE_EFFECT_TYPE BET_DARK = BATTLE_EFFECT_TYPE.BET_DARK;

		public const BATTLE_EFFECT_TYPE BET_SONG = BATTLE_EFFECT_TYPE.BET_SONG;

		public const BATTLE_EFFECT_TYPE BET_PITCH = BATTLE_EFFECT_TYPE.BET_PITCH;

		public const BATTLE_EFFECT_TYPE BET_COVER = BATTLE_EFFECT_TYPE.BET_COVER;

		public const BATTLE_EFFECT_TYPE BET_STEAL = BATTLE_EFFECT_TYPE.BET_STEAL;

		public const BATTLE_EFFECT_TYPE BET_KNOCK_OVER = BATTLE_EFFECT_TYPE.BET_KNOCK_OVER;

		public const BATTLE_EFFECT_TYPE BET_COVER_START = BATTLE_EFFECT_TYPE.BET_COVER_START;

		public const BATTLE_EFFECT_TYPE BET_POISE = BATTLE_EFFECT_TYPE.BET_POISE;

		private static VecFx32 CursorOffset = new VecFx32(-4096, 36864, 0);

		private static NNSG2dFVec2 TriangleSize = new NNSG2dFVec2(262144, 262144);

		private static ds.Vector2<short> HelpWindowCenterPosition = new ds.Vector2<short>(240, 16);

		private static ds.Vector2<short> HelpWindowSize = new ds.Vector2<short>(472, 24);

		private static ds.Vector2<short> HelpWindowCenterPositionS = new ds.Vector2<short>(280, 16);

		private static ds.Vector2<short> HelpWindowSizeS = new ds.Vector2<short>(392, 24);

		private static VecFx32[][] PlayerPosition = new VecFx32[2][]
		{
			new VecFx32[4]
			{
				new VecFx32(118784, 0, -106496),
				new VecFx32(118784, 0, -32768),
				new VecFx32(118784, 0, 32768),
				new VecFx32(118784, 0, 106496)
			},
			new VecFx32[4]
			{
				new VecFx32(147456, 0, -106496),
				new VecFx32(147456, 0, -32768),
				new VecFx32(147456, 0, 32768),
				new VecFx32(147456, 0, 106496)
			}
		};

		private static VecFx32[] CoverManPosition = new VecFx32[4]
		{
			new VecFx32(81920, 0, -106496),
			new VecFx32(81920, 0, -32768),
			new VecFx32(81920, 0, 32768),
			new VecFx32(81920, 0, 106496)
		};

		private static int PLAYER_MOVE_DISTANCE = 32768;

		public static VecFx32[] MonsterPosition = new VecFx32[6]
		{
			new VecFx32(-172032, 0, -32768),
			new VecFx32(-172032, 0, -118784),
			new VecFx32(-172032, 0, 53248),
			new VecFx32(-77824, 0, -32768),
			new VecFx32(-77824, 0, -118784),
			new VecFx32(-77824, 0, 53248)
		};

		private static ushort PlayerRotationY = 49152;

		private static ushort MonsterRotationY = 16384;

		private static VecFx32[] PlayerWinPosition = new VecFx32[4]
		{
			new VecFx32(114688, 0, 14336),
			new VecFx32(53248, 0, -53248),
			new VecFx32(135168, 0, -40960),
			new VecFx32(104448, 0, -108544)
		};

		private static ushort[] PlayerWinRotateY = new ushort[4] { 12470, 10376, 9102, 64390 };

		private static int CHANGE_BGM_COUNT_MAX = 30;

		private static int WAIT_BGM_MAX = 42;

		private static readonly int[] EnemyFrontBattleMonsterId = new int[3] { 4, 3, 5 };

		private static readonly int[] EnemyBackBattleMonsterId = new int[3] { 1, 0, 2 };

		private static string[] MonsterBoneName = new string[1] { "kuti" };

		private static VecFx32 btl_reuse_pos = new VecFx32();

		private static VecFx32 EffectedNpcPosition = new VecFx32(106496, 0, 40960);

		private static VecFx32 EffectedNpcTarget = new VecFx32(50744, 33792, 56080);

		private static VecFx32 EffectedNpcCamera = new VecFx32(-12344, 30576, 73536);

		private static string[] PlayerBoneName = new string[6] { "R_te", "L_te", "R_ude", "L_ude", "mune", "atama" };

		private static MtxFx43 btl_reuse_temp = new MtxFx43();

		private static MtxFx43 btl_reuse_move = new MtxFx43();

		private static MtxFx43 btl_reuse_mtx = new MtxFx43();

		private static ds.Vector3<int> btl_reuse_vec = new ds.Vector3<int>();

		private static int[] btl_reuse_player_id = new int[4];

		private static VecFx32 PlayerShadowScale = new VecFx32(5461, 4096, 5461);

		public static CommandParameter[] IfritCombineCommand = new CommandParameter[56]
		{
			new CommandParameter(15, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SET_DARK_SCREEN),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.IS_DARK_SCREEN),
			new CommandParameter(237, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SET_SUMMON_PARAMETER),
			new CommandParameter(372, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SET_EFFECT),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.IS_EFFECT),
			new CommandParameter(114, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.SET_MODEL),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.IS_MODEL),
			new CommandParameter(4, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.SET_MOTION),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.IS_MOTION),
			new CommandParameter(101, 1, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.START_MOTION),
			new CommandParameter(0, 10, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SET_FADE_OUT),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.IS_FADE_OUT),
			new CommandParameter(122880, 20480, 0, 60, 0, 0, 0, 1, SUMMON_BEHAVIOR.SET_POSITION_AND_ROTATION),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.SHOW_SUMMON),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.HIDE_MONSTERS),
			new CommandParameter(10, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SET_FADE_IN),
			new CommandParameter(394344, 134736, 114184, 338312, 115712, 85976, 0, 1, SUMMON_BEHAVIOR.CHANGE_CAMERA),
			new CommandParameter(394344, 134736, 114184, 384690, 134736, 133405, 0, 1, SUMMON_BEHAVIOR.SET_CAMERA_POSITION),
			new CommandParameter(338312, 115712, 85976, 328658, 115712, 105197, 0, 1, SUMMON_BEHAVIOR.SET_CAMERA_TARGET),
			new CommandParameter(20, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.SET_MOVE_CAMERA_FRAME),
			new CommandParameter(100, 15, 20, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.MOVE_CAMERA_AND_SUMMON_ALPHA),
			new CommandParameter(30, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.FRAME_COUNT),
			new CommandParameter(201, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.START_MOTION),
			new CommandParameter(13, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.IS_MOTION_FRAME),
			new CommandParameter(372, 1, 1, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.DRAW_SUMMON_EFFECT),
			new CommandParameter(384690, 134736, 133405, 328658, 115712, 105197, 0, 1, SUMMON_BEHAVIOR.CHANGE_CAMERA),
			new CommandParameter(384690, 134736, 133405, 529449, 157712, 206358, 0, 1, SUMMON_BEHAVIOR.SET_CAMERA_POSITION),
			new CommandParameter(328658, 115712, 105197, 472329, 143360, 177590, 0, 1, SUMMON_BEHAVIOR.SET_CAMERA_TARGET),
			new CommandParameter(10, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.SET_MOVE_CAMERA_FRAME),
			new CommandParameter(10, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.MOVING_CAMERA),
			new CommandParameter(25, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.IS_MOTION_FRAME),
			new CommandParameter(1, 7, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SET_FADE_OUT),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.IS_FADE_OUT),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.IS_END_SUMMON_EFFECT),
			new CommandParameter(320494, 177416, 189416, 258466, 152576, 158186, 0, 1, SUMMON_BEHAVIOR.CHANGE_CAMERA),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.CLEAR_EFFECT),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.SHOW_MONSTERS),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.HIDE_SUMMON),
			new CommandParameter(7, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SET_FADE_IN),
			new CommandParameter(375, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SET_EFFECT),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.IS_EFFECT),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.IS_FADE_IN),
			new CommandParameter(375, 1, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.DRAW_SUMMON_EFFECT_TARGET_ALL),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.IS_END_SUMMON_EFFECT),
			new CommandParameter(1, 0, 1, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.SET_TURN_FLAG),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.DEL_SUMMON),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SET_BATTLE_CAMERA),
			new CommandParameter(15, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SET_NORMAL_SCREEN),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.IS_NORMAL_SCREEN),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.REGISTER_PLAYERS),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 1, SUMMON_BEHAVIOR.SET_PLAYERS_ALPHA),
			new CommandParameter(30, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.APPEAR_PLAYERS),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SET_2D),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.IS_2D),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.DEAD_CHARACTERS),
			new CommandParameter(0, 0, 0, 0, 0, 0, 0, 0, SUMMON_BEHAVIOR.SUMMON_BEHAVIOR_END)
		};

		public static VecFx32 AllEnemyMagicPosition = new VecFx32(-147456, 0, -20480);

		public static VecFx32 AllPlayerMagicPosition = new VecFx32(98304, 0, 0);

		public static VecFx32[] TargetAllMagicPosition = new VecFx32[2] { AllEnemyMagicPosition, AllPlayerMagicPosition };

		public static int INITIALIZE_BATTLE_MAP_ID = 1;

		public static short INITIALIZE_MONSTER_ID = -1;

		public static short INITIALIZE_MONSTER_PARTY_ID = 1;

		private static int BATTLE_MAP_MAX = 31;

		private static int AVERAGE_DRAW_HELP_WINDOW_FRAME = 30;

		private static int ALPHA_RATE_MAX = 100;

		private static int SHADOW_ALPHA_RATE_MAX = 31;

		private static int HIT_PROBABILITY_MAX = 90;

		private static int AVOIDANCE_PROBABILITY_MAX = 100;

		private static int CRITICAL_PROBABILITY_MAX = 100;

		private static int BASE_DAMAGE_MIN = 6;

		private static int MAGIC_HIT_PROBABILITY_MAX = 100;

		private static int MAGIC_AVOIDANCE_PROBABILITY_MAX = 100;

		private static int MAGIC_LOOP_FRAME_MAX = 15;

		private static int JUMP_START_FRAME = 11;

		private static int JUMP_END_FRAME = 6;

		private static int ROOT_POSITION_FRAME = 23;

		private static int DARK_HIT_FRAME = 11;

		private static int ROLL_UP_LEVEL_MAX = 2;

		private static int OVERISSUE_MAX = 4;

		private static int PITCH_HIT_FRAME = 6;

		private static int GEOGRAPHY_MAX = 10;

		private static int GEOGRAPHY_HIT_FRAME = 17;

		private static int NPC_ATTACK_MAX = 3;

		private static int NPC_MESSAGE_MAX = 3;

		private static int NPC_APPEAR_PROBABILITY = 30;

		private static short REFLECT_ID = 4021;

		private static short REFLECT_EFP = 321;

		private static int CHANGE_MAGIC_COLOR_FRAME = 60;

		public static CBattleDisplay battleDisplay = new CBattleDisplay();

		private static VecFx32[][] AbilityCameraPosition = new VecFx32[2][]
		{
			new VecFx32[4]
			{
				new VecFx32(-1650, 31152, -65355),
				new VecFx32(1573, 39056, 7805),
				new VecFx32(3697, 39056, 72240),
				new VecFx32(-340, 31152, 145116)
			},
			new VecFx32[4]
			{
				new VecFx32(32707, 42704, -57546),
				new VecFx32(27317, 42704, 6163),
				new VecFx32(31425, 42704, 63945),
				new VecFx32(30522, 42704, 137508)
			}
		};

		private static VecFx32[][] AbilityCameraTarget = new VecFx32[2][]
		{
			new VecFx32[4]
			{
				new VecFx32(60046, 32768, -87435),
				new VecFx32(63205, 35840, -14259),
				new VecFx32(65329, 35840, 50176),
				new VecFx32(61356, 32768, 123036)
			},
			new VecFx32[4]
			{
				new VecFx32(92451, 37888, -84042),
				new VecFx32(89365, 37888, -14349),
				new VecFx32(94417, 37888, 46505),
				new VecFx32(93514, 37888, 120068)
			}
		};

		private static VecFx32[][] AbilityCameraAngle = new VecFx32[2][]
		{
			new VecFx32[4]
			{
				new VecFx32(-256, 19968, 0),
				new VecFx32(512, 19968, 0),
				new VecFx32(512, 19968, 0),
				new VecFx32(-256, 19968, 0)
			},
			new VecFx32[4]
			{
				new VecFx32(768, 20736, 0),
				new VecFx32(768, 19712, 0),
				new VecFx32(768, 19200, 0),
				new VecFx32(768, 19200, 0)
			}
		};

		private static int[][] AbilityCameraDistance = new int[2][]
		{
			new int[4] { 65536, 65536, 65536, 65536 },
			new int[4] { 65536, 65536, 65536, 65536 }
		};

		private static VecFx32 CameraOpeningPosition = new VecFx32(167731, 521824, 625215);

		private static VecFx32 CameraOpeningTarget = new VecFx32(151827, 480256, 577119);

		private static VecFx32 CameraOpeningAngle = new VecFx32(7168, -29440, 0);

		private static int CameraOpeningDistance = 65536;

		private static VecFx32 CameraBattlePosition = new VecFx32(537084, 142272, 191833);

		private static VecFx32 CameraBattleTarget = new VecFx32(478028, 131072, 165657);

		private static VecFx32 CameraBattleAngle = new VecFx32(1792, -20736, 0);

		private static int CameraBattleDistance = 65536;

		private static VecFx32 EndingStartCameraPosition = new VecFx32(463007, 68093, 165505);

		private static VecFx32 EndingStartCameraTarget = new VecFx32(378760, 56320, 120456);

		private static VecFx32 EndingStartCameraAngle = new VecFx32(1280, -21504, 0);

		private static int EndingStartCameraDistance = 96256;

		private static VecFx32 EndingFinishCameraPosition = new VecFx32(295741, 68093, 90725);

		private static VecFx32 EndingFinishCameraTarget = new VecFx32(216288, 56320, 37639);

		private static VecFx32 EndingFinishCameraAngle = new VecFx32(1280, -22528, 0);

		private static int EndingFinishCameraDistance = 96256;

		private static VecFx32[][] OpeningStartCameraPosition = new VecFx32[2][]
		{
			new VecFx32[3]
			{
				new VecFx32(170403, 116672, 189362),
				new VecFx32(234728, 116672, 44127),
				new VecFx32(CameraOpeningPosition.x, CameraOpeningPosition.y, CameraOpeningPosition.z)
			},
			new VecFx32[3]
			{
				new VecFx32(407553, 90048, 149140),
				new VecFx32(210980, 90048, 98510),
				new VecFx32(CameraOpeningPosition.x, CameraOpeningPosition.y, CameraOpeningPosition.z)
			}
		};

		private static VecFx32[][] OpeningStartCameraTarget = new VecFx32[2][]
		{
			new VecFx32[3]
			{
				new VecFx32(111347, 105472, 163186),
				new VecFx32(175672, 105472, 17951),
				new VecFx32(CameraOpeningTarget.x, CameraOpeningTarget.y, CameraOpeningTarget.z)
			},
			new VecFx32[3]
			{
				new VecFx32(345297, 81920, 131908),
				new VecFx32(150708, 81920, 75262),
				new VecFx32(CameraOpeningTarget.x, CameraOpeningTarget.y, CameraOpeningTarget.z)
			}
		};

		private static VecFx32[][] OpeningStartCameraAngle = new VecFx32[2][]
		{
			new VecFx32[3]
			{
				new VecFx32(1792, -20736, 0),
				new VecFx32(1792, -20736, 0),
				new VecFx32(0, 0, 0)
			},
			new VecFx32[3]
			{
				new VecFx32(1792, -19200, 0),
				new VecFx32(1792, -19200, 0),
				new VecFx32(1792, -19200, 0)
			}
		};

		private static int[][] OpeningStartCameraDistance = new int[2][]
		{
			new int[3] { 65536, 65536, 65536 },
			new int[3] { 65536, 65536, 65536 }
		};

		private static int[][] OpeningStartCameraFrame = new int[2][]
		{
			new int[3] { 70, 0, 0 },
			new int[3] { 70, 0, 0 }
		};

		internal static NNSG2dFVec2 CommandCursorPosition(int i)
		{
			NNSG2dFVec2 nNSG2dFVec = new NNSG2dFVec2();
			if (i < 3)
			{
				nNSG2dFVec.x = 4096 * (BATTLE_COMMAND_X() + 8);
				nNSG2dFVec.y = 4096 * (BATTLE_COMMAND_Y() + 20 + (i + 1) * 40);
			}
			else
			{
				nNSG2dFVec.x = 1671168;
				nNSG2dFVec.y = 81920;
			}
			return nNSG2dFVec;
		}

		internal static NNSG2dFVec2 TrianglePosition(int i)
		{
			return new NNSG2dFVec2(4096 * (BATTLE_COMMAND_X() + 128), 4096 * (BATTLE_COMMAND_Y() + ((i == 0) ? 38 : 98)));
		}

		internal static ds.Vector2<short> PlayerNamePosition(int i)
		{
			return new ds.Vector2<short>(284, (short)(BATTLE_PLAYER_Y() + i * 16));
		}

		internal static ds.Vector2<short> PlayerHpPosition(int i)
		{
			return new ds.Vector2<short>(424, (short)(BATTLE_PLAYER_Y() + i * 16));
		}

		internal static ds.Vector2<short> PlayerMaxHpPosition(int i)
		{
			return new ds.Vector2<short>(424, (short)(BATTLE_PLAYER_Y() + i * 16));
		}

		internal static ds.Vector2<short> CoasterPosition(int i, int j)
		{
			return new ds.Vector2<short>((short)(284 + ((j == 0) ? (-2) : 192)), (short)(BATTLE_PLAYER_Y() - 2 + (i + j) * 16));
		}

	}
}
